VACUUM Supervisor: com.gluonapplication.ControllerMiniTowerSqz Class Reference
com.gluonapplication.ControllerMiniTowerSqz Class Reference
Package Functions
void SpeedP21_Clicked (MouseEvent event)
void SpeedP21_Pressed (MouseEvent event)
void SpeedP21_Released (MouseEvent event)
void G21_Clicked (MouseEvent event)
void G21_Pressed (MouseEvent event)
void G21_Released (MouseEvent event)
void G22_Clicked (MouseEvent event)
void G22_Pressed (MouseEvent event)
void G22_Released (MouseEvent event)
void GP_Clicked (MouseEvent event)
void GP_Pressed (MouseEvent event)
void GP_Released (MouseEvent event)
void Ge1_Clicked (MouseEvent event)
void Ge1_Pressed (MouseEvent event)
void Ge1_Released (MouseEvent event)
void Ge2_Clicked (MouseEvent event)
void Ge2_Pressed (MouseEvent event)
void Ge2_Released (MouseEvent event)
void Ge3_Clicked (MouseEvent event)
void Ge3_Pressed (MouseEvent event)
void Ge3_Released (MouseEvent event)
void Ge4_Clicked (MouseEvent event)
void Ge4_Pressed (MouseEvent event)
void Ge4_Released (MouseEvent event)
void P21_Clicked (MouseEvent event)
void P21_Pressed (MouseEvent event)
void P21_Released (MouseEvent event)
void P22_Clicked (MouseEvent event)
void P22_Pressed (MouseEvent event)
void P22_Released (MouseEvent event)
void PressureG21_Clicked (MouseEvent event)
void PressureG21_Pressed (MouseEvent event)
void PressureG21_Released (MouseEvent event)
void PressureG22_Clicked (MouseEvent event)
void PressureG22_Pressed (MouseEvent event)
void PressureG22_Released (MouseEvent event)
void PressureGP_Clicked (MouseEvent event)
void PressureGP_Pressed (MouseEvent event)
void PressureGP_Released (MouseEvent event)
void PressureGe1_Clicked (MouseEvent event)
void PressureGe1_Pressed (MouseEvent event)
void PressureGe1_Released (MouseEvent event)
void PressureGe2_Clicked (MouseEvent event)
void PressureGe2_Pressed (MouseEvent event)
void PressureGe2_Released (MouseEvent event)
void PressureGe3_Clicked (MouseEvent event)
void PressureGe3_Pressed (MouseEvent event)
void PressureGe3_Released (MouseEvent event)
void V1_Clicked (MouseEvent event)
void V1_Pressed (MouseEvent event)
void V1_Released (MouseEvent event)
void V21_Clicked (MouseEvent event)
void V21_Pressed (MouseEvent event)
void V21_Released (MouseEvent event)
void V22_Clicked (MouseEvent event)
void V22_Pressed (MouseEvent event)
void V22_Released (MouseEvent event)
void V23_Clicked (MouseEvent event)
void V23_Pressed (MouseEvent event)
void V23_Released (MouseEvent event)
void V25_Clicked (MouseEvent event)
void V25_Pressed (MouseEvent event)
void V25_Released (MouseEvent event)
void VP_Clicked (MouseEvent event)
void VP_Pressed (MouseEvent event)
void VP_Released (MouseEvent event)
void Vrem_Clicked (MouseEvent event)
void Vrem_Pressed (MouseEvent event)
void Vrem_Released (MouseEvent event)
void V24_Clicked (MouseEvent event)
void V24_Pressed (MouseEvent event)
void V24_Released (MouseEvent event)
void Ve1_Clicked (MouseEvent event)
void Ve1_Pressed (MouseEvent event)
void Ve1_Released (MouseEvent event)
void Ve2_Clicked (MouseEvent event)
void Ve2_Pressed (MouseEvent event)
void Ve2_Released (MouseEvent event)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowRGALayer (String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 12 of file ControllerMiniTowerSqz.java.
Member Function Documentation
G21_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.G21_Clicked (MouseEvent event) package
Definition at line 194 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G21_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.G21_Pressed (MouseEvent event) package
Definition at line 199 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
G21_Released()
void com.gluonapplication.ControllerMiniTowerSqz.G21_Released (MouseEvent event) package
Definition at line 205 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
G22_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.G22_Clicked (MouseEvent event) package
Definition at line 210 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G22_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.G22_Pressed (MouseEvent event) package
Definition at line 215 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
G22_Released()
void com.gluonapplication.ControllerMiniTowerSqz.G22_Released (MouseEvent event) package
Definition at line 221 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ge1_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ge1_Clicked (MouseEvent event) package
Definition at line 242 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ge1_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ge1_Pressed (MouseEvent event) package
Definition at line 247 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ge1_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ge1_Released (MouseEvent event) package
Definition at line 253 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ge2_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ge2_Clicked (MouseEvent event) package
Definition at line 258 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ge2_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ge2_Pressed (MouseEvent event) package
Definition at line 263 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ge2_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ge2_Released (MouseEvent event) package
Definition at line 269 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ge3_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ge3_Clicked (MouseEvent event) package
Definition at line 274 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ge3_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ge3_Pressed (MouseEvent event) package
Definition at line 279 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ge3_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ge3_Released (MouseEvent event) package
Definition at line 285 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ge4_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ge4_Clicked (MouseEvent event) package
Definition at line 290 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowRGALayer().
Ge4_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ge4_Pressed (MouseEvent event) package
Definition at line 295 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ge4_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ge4_Released (MouseEvent event) package
Definition at line 301 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
GP_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.GP_Clicked (MouseEvent event) package
Definition at line 226 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
GP_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.GP_Pressed (MouseEvent event) package
Definition at line 231 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
GP_Released()
void com.gluonapplication.ControllerMiniTowerSqz.GP_Released (MouseEvent event) package
Definition at line 237 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
P21_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.P21_Clicked (MouseEvent event) package
Definition at line 307 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowTurboLayer().
P21_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.P21_Pressed (MouseEvent event) package
Definition at line 312 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
P21_Released()
void com.gluonapplication.ControllerMiniTowerSqz.P21_Released (MouseEvent event) package
Definition at line 318 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
P22_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.P22_Clicked (MouseEvent event) package
Definition at line 323 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P22_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.P22_Pressed (MouseEvent event) package
Definition at line 328 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
P22_Released()
void com.gluonapplication.ControllerMiniTowerSqz.P22_Released (MouseEvent event) package
Definition at line 334 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureG21_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG21_Clicked (MouseEvent event) package
Definition at line 340 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG21_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG21_Pressed (MouseEvent event) package
Definition at line 345 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureG21_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG21_Released (MouseEvent event) package
Definition at line 351 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureG22_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG22_Clicked (MouseEvent event) package
Definition at line 356 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG22_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG22_Pressed (MouseEvent event) package
Definition at line 361 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureG22_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureG22_Released (MouseEvent event) package
Definition at line 367 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe1_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe1_Clicked (MouseEvent event) package
Definition at line 388 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGe1_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe1_Pressed (MouseEvent event) package
Definition at line 393 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe1_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe1_Released (MouseEvent event) package
Definition at line 399 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe2_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe2_Clicked (MouseEvent event) package
Definition at line 404 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGe2_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe2_Pressed (MouseEvent event) package
Definition at line 409 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe2_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe2_Released (MouseEvent event) package
Definition at line 415 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe3_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe3_Clicked (MouseEvent event) package
Definition at line 420 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGe3_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe3_Pressed (MouseEvent event) package
Definition at line 425 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGe3_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGe3_Released (MouseEvent event) package
Definition at line 431 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGP_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGP_Clicked (MouseEvent event) package
Definition at line 372 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGP_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGP_Pressed (MouseEvent event) package
Definition at line 377 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
PressureGP_Released()
void com.gluonapplication.ControllerMiniTowerSqz.PressureGP_Released (MouseEvent event) package
Definition at line 383 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
SpeedP21_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.SpeedP21_Clicked (MouseEvent event) package
Definition at line 178 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
SpeedP21_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.SpeedP21_Pressed (MouseEvent event) package
Definition at line 183 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
SpeedP21_Released()
void com.gluonapplication.ControllerMiniTowerSqz.SpeedP21_Released (MouseEvent event) package
Definition at line 189 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V1_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V1_Clicked (MouseEvent event) package
Definition at line 436 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V1_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V1_Pressed (MouseEvent event) package
Definition at line 441 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V1_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V1_Released (MouseEvent event) package
Definition at line 447 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V21_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V21_Clicked (MouseEvent event) package
Definition at line 452 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V21_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V21_Pressed (MouseEvent event) package
Definition at line 457 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V21_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V21_Released (MouseEvent event) package
Definition at line 463 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V22_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V22_Clicked (MouseEvent event) package
Definition at line 468 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V22_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V22_Pressed (MouseEvent event) package
Definition at line 473 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V22_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V22_Released (MouseEvent event) package
Definition at line 479 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V23_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V23_Clicked (MouseEvent event) package
Definition at line 484 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V23_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V23_Pressed (MouseEvent event) package
Definition at line 489 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V23_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V23_Released (MouseEvent event) package
Definition at line 495 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V24_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V24_Clicked (MouseEvent event) package
Definition at line 548 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V24_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V24_Pressed (MouseEvent event) package
Definition at line 553 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V24_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V24_Released (MouseEvent event) package
Definition at line 559 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
V25_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.V25_Clicked (MouseEvent event) package
Definition at line 500 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V25_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.V25_Pressed (MouseEvent event) package
Definition at line 505 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
V25_Released()
void com.gluonapplication.ControllerMiniTowerSqz.V25_Released (MouseEvent event) package
Definition at line 511 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ve1_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ve1_Clicked (MouseEvent event) package
Definition at line 564 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Ve1_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ve1_Pressed (MouseEvent event) package
Definition at line 569 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ve1_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ve1_Released (MouseEvent event) package
Definition at line 575 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Ve2_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Ve2_Clicked (MouseEvent event) package
Definition at line 580 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Ve2_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Ve2_Pressed (MouseEvent event) package
Definition at line 585 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Ve2_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Ve2_Released (MouseEvent event) package
Definition at line 591 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
VP_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.VP_Clicked (MouseEvent event) package
Definition at line 516 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VP_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.VP_Pressed (MouseEvent event) package
Definition at line 521 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
VP_Released()
void com.gluonapplication.ControllerMiniTowerSqz.VP_Released (MouseEvent event) package
Definition at line 527 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Vrem_Clicked()
void com.gluonapplication.ControllerMiniTowerSqz.Vrem_Clicked (MouseEvent event) package
Definition at line 532 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Vrem_Pressed()
void com.gluonapplication.ControllerMiniTowerSqz.Vrem_Pressed (MouseEvent event) package
Definition at line 537 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerMiniTowerSqz.style.
Vrem_Released()
void com.gluonapplication.ControllerMiniTowerSqz.Vrem_Released (MouseEvent event) package
Definition at line 543 of file ControllerMiniTowerSqz.java.
References com.gluonapplication.ControllerMiniTowerSqz.style.
Member Data Documentation
style
String com.gluonapplication.ControllerMiniTowerSqz.style = "" package
Definition at line 174 of file ControllerMiniTowerSqz.java.
Referenced by com.gluonapplication.ControllerMiniTowerSqz.G21_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.G21_Released(), com.gluonapplication.ControllerMiniTowerSqz.G22_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.G22_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ge1_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ge1_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ge2_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ge2_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ge3_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ge3_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ge4_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ge4_Released(), com.gluonapplication.ControllerMiniTowerSqz.GP_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.GP_Released(), com.gluonapplication.ControllerMiniTowerSqz.P21_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.P21_Released(), com.gluonapplication.ControllerMiniTowerSqz.P22_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.P22_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureG21_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureG21_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureG22_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureG22_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe1_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe1_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe2_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe2_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe3_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureGe3_Released(), com.gluonapplication.ControllerMiniTowerSqz.PressureGP_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.PressureGP_Released(), com.gluonapplication.ControllerMiniTowerSqz.SpeedP21_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.SpeedP21_Released(), com.gluonapplication.ControllerMiniTowerSqz.V1_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V1_Released(), com.gluonapplication.ControllerMiniTowerSqz.V21_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V21_Released(), com.gluonapplication.ControllerMiniTowerSqz.V22_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V22_Released(), com.gluonapplication.ControllerMiniTowerSqz.V23_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V23_Released(), com.gluonapplication.ControllerMiniTowerSqz.V24_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V24_Released(), com.gluonapplication.ControllerMiniTowerSqz.V25_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.V25_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ve1_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ve1_Released(), com.gluonapplication.ControllerMiniTowerSqz.Ve2_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.Ve2_Released(), com.gluonapplication.ControllerMiniTowerSqz.VP_Pressed(), com.gluonapplication.ControllerMiniTowerSqz.VP_Released(), com.gluonapplication.ControllerMiniTowerSqz.Vrem_Pressed(), and com.gluonapplication.ControllerMiniTowerSqz.Vrem_Released().
The documentation for this class was generated from the following file:
ControllerMiniTowerSqz.java