VACUUM Supervisor: com.gluonapplication.ControllerLinkActions Class Reference
com.gluonapplication.ControllerLinkActions Class Reference
Public Member Functions
void initialize ()
Package Functions
void FanOnOff_Clicked (MouseEvent event)
void FanOnOff_Pressed (MouseEvent event)
void FanOnOff_Released (MouseEvent event)
void FanSpeed_Clicked (MouseEvent event)
void FanSpeed_Pressed (MouseEvent event)
void FanSpeed_Released (MouseEvent event)
void ByPassRemote_Clicked (MouseEvent event)
void ByPassRemote_Pressed (MouseEvent event)
void ByPassRemote_Released (MouseEvent event)
Package Attributes
String name = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 8 of file ControllerLinkActions.java.
Member Function Documentation
ByPassRemote_Clicked()
void com.gluonapplication.ControllerLinkActions.ByPassRemote_Clicked (MouseEvent event) package
Definition at line 98 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.LINKACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerLinkActions.name, and com.gluonapplication.ControlCommand.setCommand().
ByPassRemote_Pressed()
void com.gluonapplication.ControllerLinkActions.ByPassRemote_Pressed (MouseEvent event) package
Definition at line 118 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
ByPassRemote_Released()
void com.gluonapplication.ControllerLinkActions.ByPassRemote_Released (MouseEvent event) package
Definition at line 124 of file ControllerLinkActions.java.
FanOnOff_Clicked()
void com.gluonapplication.ControllerLinkActions.FanOnOff_Clicked (MouseEvent event) package
Definition at line 36 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.LINKACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerLinkActions.name, and com.gluonapplication.ControlCommand.setCommand().
FanOnOff_Pressed()
void com.gluonapplication.ControllerLinkActions.FanOnOff_Pressed (MouseEvent event) package
Definition at line 56 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
FanOnOff_Released()
void com.gluonapplication.ControllerLinkActions.FanOnOff_Released (MouseEvent event) package
Definition at line 62 of file ControllerLinkActions.java.
FanSpeed_Clicked()
void com.gluonapplication.ControllerLinkActions.FanSpeed_Clicked (MouseEvent event) package
Definition at line 67 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.LINKACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerLinkActions.name, and com.gluonapplication.ControlCommand.setCommand().
FanSpeed_Pressed()
void com.gluonapplication.ControllerLinkActions.FanSpeed_Pressed (MouseEvent event) package
Definition at line 87 of file ControllerLinkActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
FanSpeed_Released()
void com.gluonapplication.ControllerLinkActions.FanSpeed_Released (MouseEvent event) package
Definition at line 93 of file ControllerLinkActions.java.
initialize()
void com.gluonapplication.ControllerLinkActions.initialize ()
Definition at line 30 of file ControllerLinkActions.java.
References com.gluonapplication.ControllerLinkActions.name, and com.gluonapplication.ViewData.name.
Member Data Documentation
name
String com.gluonapplication.ControllerLinkActions.name = "" package
Definition at line 25 of file ControllerLinkActions.java.
Referenced by com.gluonapplication.ControllerLinkActions.ByPassRemote_Clicked(), com.gluonapplication.ControllerLinkActions.FanOnOff_Clicked(), com.gluonapplication.ControllerLinkActions.FanSpeed_Clicked(), and com.gluonapplication.ControllerLinkActions.initialize().
The documentation for this class was generated from the following file:
ControllerLinkActions.java