var hierarchy =
[
    [ "ClassLoader", null, [
      [ "com.gluonapplication.MyClassLoader", "classcom_1_1gluonapplication_1_1MyClassLoader.html", null ]
    ] ],
    [ "Cloneable", null, [
      [ "com.gluonapplication.DataSet", "classcom_1_1gluonapplication_1_1DataSet.html", [
        [ "com.gluonapplication.DataSetCentralBuilding", "classcom_1_1gluonapplication_1_1DataSetCentralBuilding.html", null ],
        [ "com.gluonapplication.DataSetCentralBuildingFlags", "classcom_1_1gluonapplication_1_1DataSetCentralBuildingFlags.html", null ],
        [ "com.gluonapplication.DataSetCryoActions", "classcom_1_1gluonapplication_1_1DataSetCryoActions.html", null ],
        [ "com.gluonapplication.DataSetCryoLinkActions", "classcom_1_1gluonapplication_1_1DataSetCryoLinkActions.html", null ],
        [ "com.gluonapplication.DataSetCryoLinkStation", "classcom_1_1gluonapplication_1_1DataSetCryoLinkStation.html", null ],
        [ "com.gluonapplication.DataSetCryoLinkStationFlags", "classcom_1_1gluonapplication_1_1DataSetCryoLinkStationFlags.html", null ],
        [ "com.gluonapplication.DataSetCryoStation", "classcom_1_1gluonapplication_1_1DataSetCryoStation.html", null ],
        [ "com.gluonapplication.DataSetCryoStationFlags", "classcom_1_1gluonapplication_1_1DataSetCryoStationFlags.html", null ],
        [ "com.gluonapplication.DataSetDry", "classcom_1_1gluonapplication_1_1DataSetDry.html", null ],
        [ "com.gluonapplication.DataSetEndBuilding", "classcom_1_1gluonapplication_1_1DataSetEndBuilding.html", null ],
        [ "com.gluonapplication.DataSetEndBuildingFlags", "classcom_1_1gluonapplication_1_1DataSetEndBuildingFlags.html", null ],
        [ "com.gluonapplication.DataSetGauge", "classcom_1_1gluonapplication_1_1DataSetGauge.html", null ],
        [ "com.gluonapplication.DataSetGlobal", "classcom_1_1gluonapplication_1_1DataSetGlobal.html", null ],
        [ "com.gluonapplication.DataSetGlobalFlags", "classcom_1_1gluonapplication_1_1DataSetGlobalFlags.html", null ],
        [ "com.gluonapplication.DataSetGlobalFlagsPlus", "classcom_1_1gluonapplication_1_1DataSetGlobalFlagsPlus.html", null ],
        [ "com.gluonapplication.DataSetIonic", "classcom_1_1gluonapplication_1_1DataSetIonic.html", null ],
        [ "com.gluonapplication.DataSetLinkActions", "classcom_1_1gluonapplication_1_1DataSetLinkActions.html", null ],
        [ "com.gluonapplication.DataSetLinkStation", "classcom_1_1gluonapplication_1_1DataSetLinkStation.html", null ],
        [ "com.gluonapplication.DataSetLinkStationFlags", "classcom_1_1gluonapplication_1_1DataSetLinkStationFlags.html", null ],
        [ "com.gluonapplication.DataSetMiniTowerSqzActions", "classcom_1_1gluonapplication_1_1DataSetMiniTowerSqzActions.html", null ],
        [ "com.gluonapplication.DataSetMiniTowerSqzStation", "classcom_1_1gluonapplication_1_1DataSetMiniTowerSqzStation.html", null ],
        [ "com.gluonapplication.DataSetMiniTowerSqzStationFlags", "classcom_1_1gluonapplication_1_1DataSetMiniTowerSqzStationFlags.html", null ],
        [ "com.gluonapplication.DataSetMobileVenting", "classcom_1_1gluonapplication_1_1DataSetMobileVenting.html", null ],
        [ "com.gluonapplication.DataSetMobileVentingActions", "classcom_1_1gluonapplication_1_1DataSetMobileVentingActions.html", null ],
        [ "com.gluonapplication.DataSetMobileVentingFlags", "classcom_1_1gluonapplication_1_1DataSetMobileVentingFlags.html", null ],
        [ "com.gluonapplication.DataSetNotification", "classcom_1_1gluonapplication_1_1DataSetNotification.html", null ],
        [ "com.gluonapplication.DataSetPlot", "classcom_1_1gluonapplication_1_1DataSetPlot.html", null ],
        [ "com.gluonapplication.DataSetRGA", "classcom_1_1gluonapplication_1_1DataSetRGA.html", null ],
        [ "com.gluonapplication.DataSetRemotePumps", "classcom_1_1gluonapplication_1_1DataSetRemotePumps.html", null ],
        [ "com.gluonapplication.DataSetRemotePumpsFlags", "classcom_1_1gluonapplication_1_1DataSetRemotePumpsFlags.html", null ],
        [ "com.gluonapplication.DataSetSensorO2", "classcom_1_1gluonapplication_1_1DataSetSensorO2.html", null ],
        [ "com.gluonapplication.DataSetSqz", "classcom_1_1gluonapplication_1_1DataSetSqz.html", null ],
        [ "com.gluonapplication.DataSetSupervisorActionsFlags", "classcom_1_1gluonapplication_1_1DataSetSupervisorActionsFlags.html", null ],
        [ "com.gluonapplication.DataSetTitane", "classcom_1_1gluonapplication_1_1DataSetTitane.html", null ],
        [ "com.gluonapplication.DataSetTowerBenchStation", "classcom_1_1gluonapplication_1_1DataSetTowerBenchStation.html", null ],
        [ "com.gluonapplication.DataSetTowerBenchStationFlags", "classcom_1_1gluonapplication_1_1DataSetTowerBenchStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTowerStation", "classcom_1_1gluonapplication_1_1DataSetTowerStation.html", null ],
        [ "com.gluonapplication.DataSetTowerStationFlags", "classcom_1_1gluonapplication_1_1DataSetTowerStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTube", "classcom_1_1gluonapplication_1_1DataSetTube.html", null ],
        [ "com.gluonapplication.DataSetTubeFlags", "classcom_1_1gluonapplication_1_1DataSetTubeFlags.html", null ],
        [ "com.gluonapplication.DataSetTubeLalStation", "classcom_1_1gluonapplication_1_1DataSetTubeLalStation.html", null ],
        [ "com.gluonapplication.DataSetTubeLalStationFlags", "classcom_1_1gluonapplication_1_1DataSetTubeLalStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTubeMCActions", "classcom_1_1gluonapplication_1_1DataSetTubeMCActions.html", null ],
        [ "com.gluonapplication.DataSetTubeMCStation", "classcom_1_1gluonapplication_1_1DataSetTubeMCStation.html", null ],
        [ "com.gluonapplication.DataSetTubeMCStationFlags", "classcom_1_1gluonapplication_1_1DataSetTubeMCStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTubeSqzActions", "classcom_1_1gluonapplication_1_1DataSetTubeSqzActions.html", null ],
        [ "com.gluonapplication.DataSetTubeSqzStation", "classcom_1_1gluonapplication_1_1DataSetTubeSqzStation.html", null ],
        [ "com.gluonapplication.DataSetTubeSqzStationFlags", "classcom_1_1gluonapplication_1_1DataSetTubeSqzStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTubeStation", "classcom_1_1gluonapplication_1_1DataSetTubeStation.html", null ],
        [ "com.gluonapplication.DataSetTubeStationFlags", "classcom_1_1gluonapplication_1_1DataSetTubeStationFlags.html", null ],
        [ "com.gluonapplication.DataSetTurbo", "classcom_1_1gluonapplication_1_1DataSetTurbo.html", null ],
        [ "com.gluonapplication.DataSetValve", "classcom_1_1gluonapplication_1_1DataSetValve.html", null ]
      ] ]
    ] ],
    [ "com.gluonapplication.ControlLayer", "classcom_1_1gluonapplication_1_1ControlLayer.html", [
      [ "com.gluonapplication.ControllerCentralBuilding", "classcom_1_1gluonapplication_1_1ControllerCentralBuilding.html", null ],
      [ "com.gluonapplication.ControllerCryo", "classcom_1_1gluonapplication_1_1ControllerCryo.html", null ],
      [ "com.gluonapplication.ControllerCryoLink", "classcom_1_1gluonapplication_1_1ControllerCryoLink.html", null ],
      [ "com.gluonapplication.ControllerGlobal", "classcom_1_1gluonapplication_1_1ControllerGlobal.html", null ],
      [ "com.gluonapplication.ControllerLink", "classcom_1_1gluonapplication_1_1ControllerLink.html", null ],
      [ "com.gluonapplication.ControllerMiniTowerSqz", "classcom_1_1gluonapplication_1_1ControllerMiniTowerSqz.html", null ],
      [ "com.gluonapplication.ControllerMobileVenting", "classcom_1_1gluonapplication_1_1ControllerMobileVenting.html", null ],
      [ "com.gluonapplication.ControllerNE", "classcom_1_1gluonapplication_1_1ControllerNE.html", null ],
      [ "com.gluonapplication.ControllerRemotePumps", "classcom_1_1gluonapplication_1_1ControllerRemotePumps.html", null ],
      [ "com.gluonapplication.ControllerSqz", "classcom_1_1gluonapplication_1_1ControllerSqz.html", null ],
      [ "com.gluonapplication.ControllerTowerBenchStation", "classcom_1_1gluonapplication_1_1ControllerTowerBenchStation.html", null ],
      [ "com.gluonapplication.ControllerTowerStation", "classcom_1_1gluonapplication_1_1ControllerTowerStation.html", null ],
      [ "com.gluonapplication.ControllerTubeLalStation", "classcom_1_1gluonapplication_1_1ControllerTubeLalStation.html", null ],
      [ "com.gluonapplication.ControllerTubeMC", "classcom_1_1gluonapplication_1_1ControllerTubeMC.html", null ],
      [ "com.gluonapplication.ControllerTubeN", "classcom_1_1gluonapplication_1_1ControllerTubeN.html", null ],
      [ "com.gluonapplication.ControllerTubeSqz", "classcom_1_1gluonapplication_1_1ControllerTubeSqz.html", null ],
      [ "com.gluonapplication.ControllerTubeStation", "classcom_1_1gluonapplication_1_1ControllerTubeStation.html", null ],
      [ "com.gluonapplication.ControllerTubeW", "classcom_1_1gluonapplication_1_1ControllerTubeW.html", null ],
      [ "com.gluonapplication.ControllerWE", "classcom_1_1gluonapplication_1_1ControllerWE.html", null ]
    ] ],
    [ "com.gluonapplication.ControllerChart", "classcom_1_1gluonapplication_1_1ControllerChart.html", null ],
    [ "com.gluonapplication.ControllerInformation", "classcom_1_1gluonapplication_1_1ControllerInformation.html", null ],
    [ "com.gluonapplication.ControllerPlot", "classcom_1_1gluonapplication_1_1ControllerPlot.html", null ],
    [ "com.gluonapplication.ControlTypes", "interfacecom_1_1gluonapplication_1_1ControlTypes.html", [
      [ "com.gluonapplication.ControllerCentralBuilding", "classcom_1_1gluonapplication_1_1ControllerCentralBuilding.html", null ],
      [ "com.gluonapplication.ControllerCryo", "classcom_1_1gluonapplication_1_1ControllerCryo.html", null ],
      [ "com.gluonapplication.ControllerCryoActions", "classcom_1_1gluonapplication_1_1ControllerCryoActions.html", null ],
      [ "com.gluonapplication.ControllerCryoLink", "classcom_1_1gluonapplication_1_1ControllerCryoLink.html", null ],
      [ "com.gluonapplication.ControllerCryoLinkActions", "classcom_1_1gluonapplication_1_1ControllerCryoLinkActions.html", null ],
      [ "com.gluonapplication.ControllerDry", "classcom_1_1gluonapplication_1_1ControllerDry.html", null ],
      [ "com.gluonapplication.ControllerGlobal", "classcom_1_1gluonapplication_1_1ControllerGlobal.html", null ],
      [ "com.gluonapplication.ControllerGlobalFlagsPlus", "classcom_1_1gluonapplication_1_1ControllerGlobalFlagsPlus.html", null ],
      [ "com.gluonapplication.ControllerITRGauge", "classcom_1_1gluonapplication_1_1ControllerITRGauge.html", null ],
      [ "com.gluonapplication.ControllerIonic", "classcom_1_1gluonapplication_1_1ControllerIonic.html", null ],
      [ "com.gluonapplication.ControllerLink", "classcom_1_1gluonapplication_1_1ControllerLink.html", null ],
      [ "com.gluonapplication.ControllerLinkActions", "classcom_1_1gluonapplication_1_1ControllerLinkActions.html", null ],
      [ "com.gluonapplication.ControllerMaxiGauge", "classcom_1_1gluonapplication_1_1ControllerMaxiGauge.html", null ],
      [ "com.gluonapplication.ControllerMiniTowerSqz", "classcom_1_1gluonapplication_1_1ControllerMiniTowerSqz.html", null ],
      [ "com.gluonapplication.ControllerMiniTowerSqzActions", "classcom_1_1gluonapplication_1_1ControllerMiniTowerSqzActions.html", null ],
      [ "com.gluonapplication.ControllerMobileVenting", "classcom_1_1gluonapplication_1_1ControllerMobileVenting.html", null ],
      [ "com.gluonapplication.ControllerMobileVentingActions", "classcom_1_1gluonapplication_1_1ControllerMobileVentingActions.html", null ],
      [ "com.gluonapplication.ControllerNE", "classcom_1_1gluonapplication_1_1ControllerNE.html", null ],
      [ "com.gluonapplication.ControllerRemotePumps", "classcom_1_1gluonapplication_1_1ControllerRemotePumps.html", null ],
      [ "com.gluonapplication.ControllerSqz", "classcom_1_1gluonapplication_1_1ControllerSqz.html", null ],
      [ "com.gluonapplication.ControllerSupervisorActions", "classcom_1_1gluonapplication_1_1ControllerSupervisorActions.html", null ],
      [ "com.gluonapplication.ControllerTitane", "classcom_1_1gluonapplication_1_1ControllerTitane.html", null ],
      [ "com.gluonapplication.ControllerTowerBenchStation", "classcom_1_1gluonapplication_1_1ControllerTowerBenchStation.html", null ],
      [ "com.gluonapplication.ControllerTowerStation", "classcom_1_1gluonapplication_1_1ControllerTowerStation.html", null ],
      [ "com.gluonapplication.ControllerTubeLalStation", "classcom_1_1gluonapplication_1_1ControllerTubeLalStation.html", null ],
      [ "com.gluonapplication.ControllerTubeMC", "classcom_1_1gluonapplication_1_1ControllerTubeMC.html", null ],
      [ "com.gluonapplication.ControllerTubeMCActions", "classcom_1_1gluonapplication_1_1ControllerTubeMCActions.html", null ],
      [ "com.gluonapplication.ControllerTubeN", "classcom_1_1gluonapplication_1_1ControllerTubeN.html", null ],
      [ "com.gluonapplication.ControllerTubeSqz", "classcom_1_1gluonapplication_1_1ControllerTubeSqz.html", null ],
      [ "com.gluonapplication.ControllerTubeSqzActions", "classcom_1_1gluonapplication_1_1ControllerTubeSqzActions.html", null ],
      [ "com.gluonapplication.ControllerTubeStation", "classcom_1_1gluonapplication_1_1ControllerTubeStation.html", null ],
      [ "com.gluonapplication.ControllerTubeW", "classcom_1_1gluonapplication_1_1ControllerTubeW.html", null ],
      [ "com.gluonapplication.ControllerTurbo", "classcom_1_1gluonapplication_1_1ControllerTurbo.html", null ],
      [ "com.gluonapplication.ControllerTurboT", "classcom_1_1gluonapplication_1_1ControllerTurboT.html", null ],
      [ "com.gluonapplication.ControllerValve", "classcom_1_1gluonapplication_1_1ControllerValve.html", null ],
      [ "com.gluonapplication.ControllerWE", "classcom_1_1gluonapplication_1_1ControllerWE.html", null ],
      [ "com.gluonapplication.ControllerWeb", "classcom_1_1gluonapplication_1_1ControllerWeb.html", null ],
      [ "com.gluonapplication.ControllerXGSGauge", "classcom_1_1gluonapplication_1_1ControllerXGSGauge.html", null ]
    ] ],
    [ "com.gluonapplication.DataTypes", "interfacecom_1_1gluonapplication_1_1DataTypes.html", [
      [ "com.gluonapplication.DataElement", "classcom_1_1gluonapplication_1_1DataElement.html", null ],
      [ "com.gluonapplication.DataSet", "classcom_1_1gluonapplication_1_1DataSet.html", null ],
      [ "com.gluonapplication.DataSetGauge", "classcom_1_1gluonapplication_1_1DataSetGauge.html", null ],
      [ "com.gluonapplication.LayerData", "classcom_1_1gluonapplication_1_1LayerData.html", [
        [ "com.gluonapplication.LayerDry", "classcom_1_1gluonapplication_1_1LayerDry.html", null ],
        [ "com.gluonapplication.LayerGauge", "classcom_1_1gluonapplication_1_1LayerGauge.html", null ],
        [ "com.gluonapplication.LayerIonic", "classcom_1_1gluonapplication_1_1LayerIonic.html", null ],
        [ "com.gluonapplication.LayerPlot", "classcom_1_1gluonapplication_1_1LayerPlot.html", null ],
        [ "com.gluonapplication.LayerRGA", "classcom_1_1gluonapplication_1_1LayerRGA.html", null ],
        [ "com.gluonapplication.LayerTitane", "classcom_1_1gluonapplication_1_1LayerTitane.html", null ],
        [ "com.gluonapplication.LayerTurbo", "classcom_1_1gluonapplication_1_1LayerTurbo.html", null ],
        [ "com.gluonapplication.LayerValve", "classcom_1_1gluonapplication_1_1LayerValve.html", null ]
      ] ],
      [ "com.gluonapplication.NotificationData", "classcom_1_1gluonapplication_1_1NotificationData.html", [
        [ "com.gluonapplication.NotificationService", "classcom_1_1gluonapplication_1_1NotificationService.html", null ]
      ] ],
      [ "com.gluonapplication.SidePopupViewData", "classcom_1_1gluonapplication_1_1SidePopupViewData.html", [
        [ "com.gluonapplication.SidePopupViewCentralBuilding", "classcom_1_1gluonapplication_1_1SidePopupViewCentralBuilding.html", null ],
        [ "com.gluonapplication.SidePopupViewCryoActions", "classcom_1_1gluonapplication_1_1SidePopupViewCryoActions.html", null ],
        [ "com.gluonapplication.SidePopupViewCryoLinkActions", "classcom_1_1gluonapplication_1_1SidePopupViewCryoLinkActions.html", null ],
        [ "com.gluonapplication.SidePopupViewCryoLinkStation", "classcom_1_1gluonapplication_1_1SidePopupViewCryoLinkStation.html", null ],
        [ "com.gluonapplication.SidePopupViewCryoStation", "classcom_1_1gluonapplication_1_1SidePopupViewCryoStation.html", null ],
        [ "com.gluonapplication.SidePopupViewEndBuilding", "classcom_1_1gluonapplication_1_1SidePopupViewEndBuilding.html", null ],
        [ "com.gluonapplication.SidePopupViewGlobal", "classcom_1_1gluonapplication_1_1SidePopupViewGlobal.html", null ],
        [ "com.gluonapplication.SidePopupViewGlobalPlus", "classcom_1_1gluonapplication_1_1SidePopupViewGlobalPlus.html", null ],
        [ "com.gluonapplication.SidePopupViewLinkActions", "classcom_1_1gluonapplication_1_1SidePopupViewLinkActions.html", null ],
        [ "com.gluonapplication.SidePopupViewLinkStation", "classcom_1_1gluonapplication_1_1SidePopupViewLinkStation.html", null ],
        [ "com.gluonapplication.SidePopupViewMiniTowerSqzActions", "classcom_1_1gluonapplication_1_1SidePopupViewMiniTowerSqzActions.html", null ],
        [ "com.gluonapplication.SidePopupViewMiniTowerSqzStation", "classcom_1_1gluonapplication_1_1SidePopupViewMiniTowerSqzStation.html", null ],
        [ "com.gluonapplication.SidePopupViewMobileVenting", "classcom_1_1gluonapplication_1_1SidePopupViewMobileVenting.html", null ],
        [ "com.gluonapplication.SidePopupViewMobileVentingActions", "classcom_1_1gluonapplication_1_1SidePopupViewMobileVentingActions.html", null ],
        [ "com.gluonapplication.SidePopupViewRemotePumps", "classcom_1_1gluonapplication_1_1SidePopupViewRemotePumps.html", null ],
        [ "com.gluonapplication.SidePopupViewSensorO2", "classcom_1_1gluonapplication_1_1SidePopupViewSensorO2.html", null ],
        [ "com.gluonapplication.SidePopupViewSupervisorActions", "classcom_1_1gluonapplication_1_1SidePopupViewSupervisorActions.html", null ],
        [ "com.gluonapplication.SidePopupViewTowerBenchStation", "classcom_1_1gluonapplication_1_1SidePopupViewTowerBenchStation.html", null ],
        [ "com.gluonapplication.SidePopupViewTowerStation", "classcom_1_1gluonapplication_1_1SidePopupViewTowerStation.html", null ],
        [ "com.gluonapplication.SidePopupViewTube", "classcom_1_1gluonapplication_1_1SidePopupViewTube.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeLalStation", "classcom_1_1gluonapplication_1_1SidePopupViewTubeLalStation.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeMCActions", "classcom_1_1gluonapplication_1_1SidePopupViewTubeMCActions.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeMCStation", "classcom_1_1gluonapplication_1_1SidePopupViewTubeMCStation.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeSqzActions", "classcom_1_1gluonapplication_1_1SidePopupViewTubeSqzActions.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeSqzStation", "classcom_1_1gluonapplication_1_1SidePopupViewTubeSqzStation.html", null ],
        [ "com.gluonapplication.SidePopupViewTubeStation", "classcom_1_1gluonapplication_1_1SidePopupViewTubeStation.html", null ]
      ] ],
      [ "com.gluonapplication.ViewData", "classcom_1_1gluonapplication_1_1ViewData.html", [
        [ "com.gluonapplication.MobileVentingView", "classcom_1_1gluonapplication_1_1MobileVentingView.html", null ],
        [ "com.gluonapplication.ViewCentralBuilding", "classcom_1_1gluonapplication_1_1ViewCentralBuilding.html", null ],
        [ "com.gluonapplication.ViewCryoLinkStation", "classcom_1_1gluonapplication_1_1ViewCryoLinkStation.html", null ],
        [ "com.gluonapplication.ViewCryoStation", "classcom_1_1gluonapplication_1_1ViewCryoStation.html", null ],
        [ "com.gluonapplication.ViewEndBuilding", "classcom_1_1gluonapplication_1_1ViewEndBuilding.html", null ],
        [ "com.gluonapplication.ViewGlobal", "classcom_1_1gluonapplication_1_1ViewGlobal.html", null ],
        [ "com.gluonapplication.ViewLinkStation", "classcom_1_1gluonapplication_1_1ViewLinkStation.html", null ],
        [ "com.gluonapplication.ViewMiniTowerSqzStation", "classcom_1_1gluonapplication_1_1ViewMiniTowerSqzStation.html", null ],
        [ "com.gluonapplication.ViewRemotePumps", "classcom_1_1gluonapplication_1_1ViewRemotePumps.html", null ],
        [ "com.gluonapplication.ViewSqz", "classcom_1_1gluonapplication_1_1ViewSqz.html", null ],
        [ "com.gluonapplication.ViewTowerBenchStation", "classcom_1_1gluonapplication_1_1ViewTowerBenchStation.html", null ],
        [ "com.gluonapplication.ViewTowerStation", "classcom_1_1gluonapplication_1_1ViewTowerStation.html", null ],
        [ "com.gluonapplication.ViewTube", "classcom_1_1gluonapplication_1_1ViewTube.html", null ],
        [ "com.gluonapplication.ViewTubeLalStation", "classcom_1_1gluonapplication_1_1ViewTubeLalStation.html", null ],
        [ "com.gluonapplication.ViewTubeMCStation", "classcom_1_1gluonapplication_1_1ViewTubeMCStation.html", null ],
        [ "com.gluonapplication.ViewTubeSqzStation", "classcom_1_1gluonapplication_1_1ViewTubeSqzStation.html", null ],
        [ "com.gluonapplication.ViewTubeStation", "classcom_1_1gluonapplication_1_1ViewTubeStation.html", null ]
      ] ]
    ] ],
    [ "Exception", null, [
      [ "com.gluonapplication.LogarithmicAxis.IllegalLogarithmicRangeException", "classcom_1_1gluonapplication_1_1LogarithmicAxis_1_1IllegalLogarithmicRangeException.html", null ]
    ] ],
    [ "Runnable", null, [
      [ "com.gluonapplication.ControlCommand", "classcom_1_1gluonapplication_1_1ControlCommand.html", null ],
      [ "com.gluonapplication.LayerData", "classcom_1_1gluonapplication_1_1LayerData.html", null ],
      [ "com.gluonapplication.NotificationData", "classcom_1_1gluonapplication_1_1NotificationData.html", null ],
      [ "com.gluonapplication.SidePopupViewData", "classcom_1_1gluonapplication_1_1SidePopupViewData.html", null ],
      [ "com.gluonapplication.ViewData", "classcom_1_1gluonapplication_1_1ViewData.html", null ]
    ] ],
    [ "RuntimeException", null, [
      [ "com.gluonapplication.LogarithmicNumberAxis.IllegalLogarithmicRangeException", "classcom_1_1gluonapplication_1_1LogarithmicNumberAxis_1_1IllegalLogarithmicRangeException.html", null ]
    ] ],
    [ "com.gluonapplication.ControlTypes.Type", "enumcom_1_1gluonapplication_1_1ControlTypes_1_1Type.html", null ],
    [ "com.gluonapplication.DataTypes.Type", "enumcom_1_1gluonapplication_1_1DataTypes_1_1Type.html", null ],
    [ "Dialog", null, [
      [ "com.gluonapplication.DialogAskMastership", "classcom_1_1gluonapplication_1_1DialogAskMastership.html", null ],
      [ "com.gluonapplication.DialogAskValue", "classcom_1_1gluonapplication_1_1DialogAskValue.html", null ],
      [ "com.gluonapplication.DialogOverTakeMastership", "classcom_1_1gluonapplication_1_1DialogOverTakeMastership.html", null ],
      [ "com.gluonapplication.DialogRefusedMastership", "classcom_1_1gluonapplication_1_1DialogRefusedMastership.html", null ]
    ] ],
    [ "Layer", null, [
      [ "com.gluonapplication.LayerData", "classcom_1_1gluonapplication_1_1LayerData.html", null ],
      [ "com.gluonapplication.LayerForm", "classcom_1_1gluonapplication_1_1LayerForm.html", null ],
      [ "com.gluonapplication.LayerMessage", "classcom_1_1gluonapplication_1_1LayerMessage.html", null ],
      [ "com.gluonapplication.LayerSplashProgress", "classcom_1_1gluonapplication_1_1LayerSplashProgress.html", null ],
      [ "com.gluonapplication.WarningLayer", "classcom_1_1gluonapplication_1_1WarningLayer.html", null ]
    ] ],
    [ "MobileApplication", null, [
      [ "com.gluonapplication.Main", "classcom_1_1gluonapplication_1_1Main.html", null ]
    ] ],
    [ "ValueAxis", null, [
      [ "com.gluonapplication.LogarithmicAxis", "classcom_1_1gluonapplication_1_1LogarithmicAxis.html", null ],
      [ "com.gluonapplication.LogarithmicNumberAxis", "classcom_1_1gluonapplication_1_1LogarithmicNumberAxis.html", null ]
    ] ],
    [ "View", null, [
      [ "com.gluonapplication.BasicView", "classcom_1_1gluonapplication_1_1BasicView.html", null ],
      [ "com.gluonapplication.ViewData", "classcom_1_1gluonapplication_1_1ViewData.html", null ]
    ] ]
];