#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
STAGE_ROOT="${REPO_ROOT}/build/windows-installer"
STAGE_DIR="${STAGE_ROOT}/stage"
OUTPUT_DIR="${STAGE_ROOT}/output"
APP_STAGE_DIR="${STAGE_DIR}/app"
RUNTIME_STAGE_DIR="${STAGE_DIR}/runtime"
TMP_DIR="${STAGE_ROOT}/tmp"
ICON_PNG_SOURCE="${REPO_ROOT}/MainApp/src/android/res/mipmap-xxxhdpi/ic_launcher.png"
ICON_PNG_STAGE="${STAGE_DIR}/vacuum-supervisor.png"
ICON_ICO_STAGE="${STAGE_DIR}/vacuum-supervisor.ico"
WRAPPER_STAGE="${STAGE_DIR}/vacuum-supervisor.cmd"
NSI_SCRIPT="${REPO_ROOT}/scripts/windows/VacuumSupervisor.nsi"
JDK_ZIP_DEFAULT="${REPO_ROOT}/Windows_Install/zulu8.92.0.21-ca-fx-jdk8.0.482-win_x64.zip"
MAKENSIS_DEFAULT="${REPO_ROOT}/Windows_Install/nsis-tool/usr/bin/makensis"
NSISDIR_DEFAULT="${REPO_ROOT}/Windows_Install/nsis-tool/usr/share/nsis"
SKIP_BUILD=0
JDK_ZIP_PATH="${JDK_ZIP_DEFAULT}"
MAKENSIS_PATH="${MAKENSIS_DEFAULT}"
NSISDIR_PATH="${NSISDIR_DEFAULT}"

usage() {
  cat <<EOF
Usage: $0 [--skip-build] [--jdk-zip /path/to/windows-javafx-jdk.zip] [--makensis /path/to/makensis] [--nsisdir /path/to/nsis/share]

Builds a Windows Setup.exe from Linux using:
  - Gradle installDist output
  - a Windows JavaFX JDK zip
  - a local NSIS toolchain
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --jdk-zip)
      JDK_ZIP_PATH="$2"
      shift 2
      ;;
    --makensis)
      MAKENSIS_PATH="$2"
      shift 2
      ;;
    --nsisdir)
      NSISDIR_PATH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "${JDK_ZIP_PATH}" ]]; then
  echo "Windows JavaFX JDK zip not found: ${JDK_ZIP_PATH}" >&2
  exit 1
fi

if [[ ! -x "${MAKENSIS_PATH}" ]]; then
  echo "makensis not found or not executable: ${MAKENSIS_PATH}" >&2
  exit 1
fi

if [[ ! -d "${NSISDIR_PATH}" ]]; then
  echo "NSISDIR not found: ${NSISDIR_PATH}" >&2
  exit 1
fi

if [[ ! -f "${ICON_PNG_SOURCE}" ]]; then
  echo "Android launcher icon not found: ${ICON_PNG_SOURCE}" >&2
  exit 1
fi

if [[ ! -f "${NSI_SCRIPT}" ]]; then
  echo "NSIS script not found: ${NSI_SCRIPT}" >&2
  exit 1
fi

if [[ "${SKIP_BUILD}" -ne 1 ]]; then
  "${REPO_ROOT}/gradlew" :MainApp:installDist
fi

if [[ ! -x "${REPO_ROOT}/MainApp/build/install/MainApp/bin/MainApp.bat" ]]; then
  echo "Windows launcher script was not generated by installDist." >&2
  exit 1
fi

APP_VERSION="$(sed -n 's/.*android:versionName=\"\([^\"]*\)\".*/\1/p' "${REPO_ROOT}/MainApp/src/android/AndroidManifest.xml" | head -n1)"
if [[ -z "${APP_VERSION}" ]]; then
  echo "Could not determine app version from AndroidManifest.xml" >&2
  exit 1
fi

rm -rf "${STAGE_ROOT}"
mkdir -p "${APP_STAGE_DIR}" "${RUNTIME_STAGE_DIR}" "${OUTPUT_DIR}" "${TMP_DIR}"

cp -a "${REPO_ROOT}/MainApp/build/install/MainApp" "${APP_STAGE_DIR}/"
cp "${ICON_PNG_SOURCE}" "${ICON_PNG_STAGE}"
convert "${ICON_PNG_STAGE}" "${ICON_ICO_STAGE}"

unzip -q "${JDK_ZIP_PATH}" -d "${TMP_DIR}/jdk"
JDK_ROOT_DIR="$(find "${TMP_DIR}/jdk" -mindepth 1 -maxdepth 1 -type d | head -n1)"
if [[ -z "${JDK_ROOT_DIR}" ]]; then
  echo "Could not determine extracted JDK directory inside ${JDK_ZIP_PATH}" >&2
  exit 1
fi
cp -a "${JDK_ROOT_DIR}/." "${RUNTIME_STAGE_DIR}/"

cat > "${WRAPPER_STAGE}" <<'EOF'
@echo off
setlocal
set "APP_HOME=%~dp0"
set "JAVA_HOME=%APP_HOME%runtime"
set "VACUUM_SUPERVISOR_DESKTOP_ICON_PATH=%APP_HOME%vacuum-supervisor.png"
set "LOG_DIR=%LOCALAPPDATA%\VacuumSupervisor\logs"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%" >NUL 2>&1
echo [%date% %time%] Launching Vacuum Supervisor %*>> "%LOG_DIR%\launcher.log"
call "%APP_HOME%app\MainApp\bin\MainApp.bat" %*
set "EXIT_CODE=%ERRORLEVEL%"
endlocal & exit /b %EXIT_CODE%
EOF

NSISDIR="${NSISDIR_PATH}" "${MAKENSIS_PATH}" \
  -DAPP_VERSION="${APP_VERSION}" \
  -DSTAGE_DIR="${STAGE_DIR}" \
  -DOUTPUT_DIR="${OUTPUT_DIR}" \
  "${NSI_SCRIPT}"

echo "Created Windows installer:"
echo "  ${OUTPUT_DIR}/VacuumSupervisorSetup-${APP_VERSION}.exe"
