VACUUM Supervisor: com.gluonapplication.ControllerSqz Class Reference
com.gluonapplication.ControllerSqz Class Reference
Package Functions
void GMid_Clicked (MouseEvent event)
void GMid_Pressed (MouseEvent event)
void GMid_Released (MouseEvent event)
void PressureGMid_Clicked (MouseEvent event)
void PressureGMid_Pressed (MouseEvent event)
void PressureGMid_Released (MouseEvent event)
void StationSqz100N_Clicked (MouseEvent event)
void StationSqz100N_Pressed (MouseEvent event)
void StationSqz100N_Released (MouseEvent event)
void StationSqz200N_Clicked (MouseEvent event)
void StationSqz200N_Pressed (MouseEvent event)
void StationSqz200N_Released (MouseEvent event)
void StationSqz0N_Clicked (MouseEvent event)
void StationSqz0N_Pressed (MouseEvent event)
void StationSqz0N_Released (MouseEvent event)
void StationSqz300N_Clicked (MouseEvent event)
void StationSqz300N_Pressed (MouseEvent event)
void StationSqz300N_Released (MouseEvent event)
void StationSqzDET1_Clicked (MouseEvent event)
void StationSqzDET1_Pressed (MouseEvent event)
void StationSqzDET1_Released (MouseEvent event)
void StationSqzDET2_Clicked (MouseEvent event)
void StationSqzDET2_Pressed (MouseEvent event)
void StationSqzDET2_Released (MouseEvent event)
void V21Sqz100N_Clicked (MouseEvent event)
void V21Sqz100N_Pressed (MouseEvent event)
void V21Sqz100N_Released (MouseEvent event)
void V21Sqz200N_Clicked (MouseEvent event)
void V21Sqz200N_Pressed (MouseEvent event)
void V21Sqz200N_Released (MouseEvent event)
void VPSqz0N_Clicked (MouseEvent event)
void VPSqz0N_Pressed (MouseEvent event)
void VPSqz0N_Released (MouseEvent event)
void VPSqz300N_Clicked (MouseEvent event)
void VPSqz300N_Pressed (MouseEvent event)
void VPSqz300N_Released (MouseEvent event)
void VPSqzDET1_Clicked (MouseEvent event)
void VPSqzDET1_Pressed (MouseEvent event)
void VPSqzDET1_Released (MouseEvent event)
void VPSqzDET2_Clicked (MouseEvent event)
void VPSqzDET2_Pressed (MouseEvent event)
void VPSqzDET2_Released (MouseEvent event)
void CreateAndShowValveLayer (String name)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowRGALayer (String name)
void CreateAndShowPlotLayer (String name)
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 11 of file ControllerSqz.java.
Member Function Documentation
CreateAndShowValveLayer()
void com.gluonapplication.ControllerSqz.CreateAndShowValveLayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 376 of file ControllerSqz.java.
Referenced by com.gluonapplication.ControllerSqz.V21Sqz100N_Clicked(), com.gluonapplication.ControllerSqz.V21Sqz200N_Clicked(), com.gluonapplication.ControllerSqz.VPSqz0N_Clicked(), com.gluonapplication.ControllerSqz.VPSqz300N_Clicked(), com.gluonapplication.ControllerSqz.VPSqzDET1_Clicked(), and com.gluonapplication.ControllerSqz.VPSqzDET2_Clicked().
GMid_Clicked()
void com.gluonapplication.ControllerSqz.GMid_Clicked (MouseEvent event) package
Definition at line 98 of file ControllerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
GMid_Pressed()
void com.gluonapplication.ControllerSqz.GMid_Pressed (MouseEvent event) package
Definition at line 103 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
GMid_Released()
void com.gluonapplication.ControllerSqz.GMid_Released (MouseEvent event) package
Definition at line 109 of file ControllerSqz.java.
PressureGMid_Clicked()
void com.gluonapplication.ControllerSqz.PressureGMid_Clicked (MouseEvent event) package
Definition at line 114 of file ControllerSqz.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGMid_Pressed()
void com.gluonapplication.ControllerSqz.PressureGMid_Pressed (MouseEvent event) package
Definition at line 119 of file ControllerSqz.java.
PressureGMid_Released()
void com.gluonapplication.ControllerSqz.PressureGMid_Released (MouseEvent event) package
Definition at line 124 of file ControllerSqz.java.
StationSqz0N_Clicked()
void com.gluonapplication.ControllerSqz.StationSqz0N_Clicked (MouseEvent event) package
Definition at line 180 of file ControllerSqz.java.
References com.gluonapplication.Main.minitowersqz0N.
StationSqz0N_Pressed()
void com.gluonapplication.ControllerSqz.StationSqz0N_Pressed (MouseEvent event) package
Definition at line 194 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqz0N_Released()
void com.gluonapplication.ControllerSqz.StationSqz0N_Released (MouseEvent event) package
Definition at line 200 of file ControllerSqz.java.
StationSqz100N_Clicked()
void com.gluonapplication.ControllerSqz.StationSqz100N_Clicked (MouseEvent event) package
Definition at line 130 of file ControllerSqz.java.
References com.gluonapplication.Main.tubesqz100N.
StationSqz100N_Pressed()
void com.gluonapplication.ControllerSqz.StationSqz100N_Pressed (MouseEvent event) package
Definition at line 144 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqz100N_Released()
void com.gluonapplication.ControllerSqz.StationSqz100N_Released (MouseEvent event) package
Definition at line 150 of file ControllerSqz.java.
StationSqz200N_Clicked()
void com.gluonapplication.ControllerSqz.StationSqz200N_Clicked (MouseEvent event) package
Definition at line 155 of file ControllerSqz.java.
References com.gluonapplication.Main.tubesqz200N.
StationSqz200N_Pressed()
void com.gluonapplication.ControllerSqz.StationSqz200N_Pressed (MouseEvent event) package
Definition at line 169 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqz200N_Released()
void com.gluonapplication.ControllerSqz.StationSqz200N_Released (MouseEvent event) package
Definition at line 175 of file ControllerSqz.java.
StationSqz300N_Clicked()
void com.gluonapplication.ControllerSqz.StationSqz300N_Clicked (MouseEvent event) package
Definition at line 205 of file ControllerSqz.java.
References com.gluonapplication.Main.minitowersqz300N.
StationSqz300N_Pressed()
void com.gluonapplication.ControllerSqz.StationSqz300N_Pressed (MouseEvent event) package
Definition at line 219 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqz300N_Released()
void com.gluonapplication.ControllerSqz.StationSqz300N_Released (MouseEvent event) package
Definition at line 225 of file ControllerSqz.java.
StationSqzDET1_Clicked()
void com.gluonapplication.ControllerSqz.StationSqzDET1_Clicked (MouseEvent event) package
Definition at line 230 of file ControllerSqz.java.
References com.gluonapplication.Main.minitowersqzdet1.
StationSqzDET1_Pressed()
void com.gluonapplication.ControllerSqz.StationSqzDET1_Pressed (MouseEvent event) package
Definition at line 244 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqzDET1_Released()
void com.gluonapplication.ControllerSqz.StationSqzDET1_Released (MouseEvent event) package
Definition at line 250 of file ControllerSqz.java.
StationSqzDET2_Clicked()
void com.gluonapplication.ControllerSqz.StationSqzDET2_Clicked (MouseEvent event) package
Definition at line 255 of file ControllerSqz.java.
References com.gluonapplication.Main.minitowersqzdet2.
StationSqzDET2_Pressed()
void com.gluonapplication.ControllerSqz.StationSqzDET2_Pressed (MouseEvent event) package
Definition at line 269 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StationSqzDET2_Released()
void com.gluonapplication.ControllerSqz.StationSqzDET2_Released (MouseEvent event) package
Definition at line 275 of file ControllerSqz.java.
V21Sqz100N_Clicked()
void com.gluonapplication.ControllerSqz.V21Sqz100N_Clicked (MouseEvent event) package
Definition at line 280 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
V21Sqz100N_Pressed()
void com.gluonapplication.ControllerSqz.V21Sqz100N_Pressed (MouseEvent event) package
Definition at line 285 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
V21Sqz100N_Released()
void com.gluonapplication.ControllerSqz.V21Sqz100N_Released (MouseEvent event) package
Definition at line 291 of file ControllerSqz.java.
V21Sqz200N_Clicked()
void com.gluonapplication.ControllerSqz.V21Sqz200N_Clicked (MouseEvent event) package
Definition at line 296 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
V21Sqz200N_Pressed()
void com.gluonapplication.ControllerSqz.V21Sqz200N_Pressed (MouseEvent event) package
Definition at line 301 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
V21Sqz200N_Released()
void com.gluonapplication.ControllerSqz.V21Sqz200N_Released (MouseEvent event) package
Definition at line 307 of file ControllerSqz.java.
VPSqz0N_Clicked()
void com.gluonapplication.ControllerSqz.VPSqz0N_Clicked (MouseEvent event) package
Definition at line 312 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
VPSqz0N_Pressed()
void com.gluonapplication.ControllerSqz.VPSqz0N_Pressed (MouseEvent event) package
Definition at line 317 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VPSqz0N_Released()
void com.gluonapplication.ControllerSqz.VPSqz0N_Released (MouseEvent event) package
Definition at line 323 of file ControllerSqz.java.
VPSqz300N_Clicked()
void com.gluonapplication.ControllerSqz.VPSqz300N_Clicked (MouseEvent event) package
Definition at line 328 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
VPSqz300N_Pressed()
void com.gluonapplication.ControllerSqz.VPSqz300N_Pressed (MouseEvent event) package
Definition at line 333 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VPSqz300N_Released()
void com.gluonapplication.ControllerSqz.VPSqz300N_Released (MouseEvent event) package
Definition at line 339 of file ControllerSqz.java.
VPSqzDET1_Clicked()
void com.gluonapplication.ControllerSqz.VPSqzDET1_Clicked (MouseEvent event) package
Definition at line 344 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
VPSqzDET1_Pressed()
void com.gluonapplication.ControllerSqz.VPSqzDET1_Pressed (MouseEvent event) package
Definition at line 349 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VPSqzDET1_Released()
void com.gluonapplication.ControllerSqz.VPSqzDET1_Released (MouseEvent event) package
Definition at line 355 of file ControllerSqz.java.
VPSqzDET2_Clicked()
void com.gluonapplication.ControllerSqz.VPSqzDET2_Clicked (MouseEvent event) package
Definition at line 360 of file ControllerSqz.java.
References com.gluonapplication.ControllerSqz.CreateAndShowValveLayer().
VPSqzDET2_Pressed()
void com.gluonapplication.ControllerSqz.VPSqzDET2_Pressed (MouseEvent event) package
Definition at line 365 of file ControllerSqz.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VPSqzDET2_Released()
void com.gluonapplication.ControllerSqz.VPSqzDET2_Released (MouseEvent event) package
Definition at line 371 of file ControllerSqz.java.
The documentation for this class was generated from the following file:
ControllerSqz.java