VACUUM Supervisor: com.gluonapplication.ControllerMobileVenting Class Reference
com.gluonapplication.ControllerMobileVenting Class Reference
Package Functions
void G1_Clicked (MouseEvent event)
void G1_Pressed (MouseEvent event)
void G1_Released (MouseEvent event)
void G2_Clicked (MouseEvent event)
void G2_Pressed (MouseEvent event)
void G2_Released (MouseEvent event)
void PressureG1_Clicked (MouseEvent event)
void PressureG1_Pressed (MouseEvent event)
void PressureG1_Released (MouseEvent event)
void PressureG2_Clicked (MouseEvent event)
void PressureG2_Pressed (MouseEvent event)
void PressureG2_Released (MouseEvent event)
void VBypass_Clicked (MouseEvent event)
void VBypass_Pressed (MouseEvent event)
void VBypass_Released (MouseEvent event)
void VMain_Clicked (MouseEvent event)
void VMain_Pressed (MouseEvent event)
void VMain_Released (MouseEvent event)
void VSoft_Clicked (MouseEvent event)
void VSoft_Pressed (MouseEvent event)
void VSoft_Released (MouseEvent event)
void VRP_Clicked (MouseEvent event)
void VRP_Pressed (MouseEvent event)
void VRP_Released (MouseEvent event)
void VDryer_Clicked (MouseEvent event)
void VDryer_Pressed (MouseEvent event)
void VDryer_Released (MouseEvent event)
void V1_Clicked (MouseEvent event)
void V1_Pressed (MouseEvent event)
void V1_Released (MouseEvent event)
void P1_Clicked (MouseEvent event)
void P1_Pressed (MouseEvent event)
void P1_Released (MouseEvent event)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowRGALayer (String name)
void CreateAndShowPlotLayer (String name)
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 9 of file ControllerMobileVenting.java.
Member Function Documentation
G1_Clicked()
void com.gluonapplication.ControllerMobileVenting.G1_Clicked (MouseEvent event) package
Definition at line 53 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G1_Pressed()
void com.gluonapplication.ControllerMobileVenting.G1_Pressed (MouseEvent event) package
Definition at line 58 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
G1_Released()
void com.gluonapplication.ControllerMobileVenting.G1_Released (MouseEvent event) package
Definition at line 64 of file ControllerMobileVenting.java.
G2_Clicked()
void com.gluonapplication.ControllerMobileVenting.G2_Clicked (MouseEvent event) package
Definition at line 69 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G2_Pressed()
void com.gluonapplication.ControllerMobileVenting.G2_Pressed (MouseEvent event) package
Definition at line 74 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
G2_Released()
void com.gluonapplication.ControllerMobileVenting.G2_Released (MouseEvent event) package
Definition at line 80 of file ControllerMobileVenting.java.
P1_Clicked()
void com.gluonapplication.ControllerMobileVenting.P1_Clicked (MouseEvent event) package
Definition at line 213 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P1_Pressed()
void com.gluonapplication.ControllerMobileVenting.P1_Pressed (MouseEvent event) package
Definition at line 218 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
P1_Released()
void com.gluonapplication.ControllerMobileVenting.P1_Released (MouseEvent event) package
Definition at line 224 of file ControllerMobileVenting.java.
PressureG1_Clicked()
void com.gluonapplication.ControllerMobileVenting.PressureG1_Clicked (MouseEvent event) package
Definition at line 85 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG1_Pressed()
void com.gluonapplication.ControllerMobileVenting.PressureG1_Pressed (MouseEvent event) package
Definition at line 90 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
PressureG1_Released()
void com.gluonapplication.ControllerMobileVenting.PressureG1_Released (MouseEvent event) package
Definition at line 96 of file ControllerMobileVenting.java.
PressureG2_Clicked()
void com.gluonapplication.ControllerMobileVenting.PressureG2_Clicked (MouseEvent event) package
Definition at line 101 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG2_Pressed()
void com.gluonapplication.ControllerMobileVenting.PressureG2_Pressed (MouseEvent event) package
Definition at line 106 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
PressureG2_Released()
void com.gluonapplication.ControllerMobileVenting.PressureG2_Released (MouseEvent event) package
Definition at line 112 of file ControllerMobileVenting.java.
V1_Clicked()
void com.gluonapplication.ControllerMobileVenting.V1_Clicked (MouseEvent event) package
Definition at line 197 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V1_Pressed()
void com.gluonapplication.ControllerMobileVenting.V1_Pressed (MouseEvent event) package
Definition at line 202 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
V1_Released()
void com.gluonapplication.ControllerMobileVenting.V1_Released (MouseEvent event) package
Definition at line 208 of file ControllerMobileVenting.java.
VBypass_Clicked()
void com.gluonapplication.ControllerMobileVenting.VBypass_Clicked (MouseEvent event) package
Definition at line 117 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VBypass_Pressed()
void com.gluonapplication.ControllerMobileVenting.VBypass_Pressed (MouseEvent event) package
Definition at line 122 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VBypass_Released()
void com.gluonapplication.ControllerMobileVenting.VBypass_Released (MouseEvent event) package
Definition at line 128 of file ControllerMobileVenting.java.
VDryer_Clicked()
void com.gluonapplication.ControllerMobileVenting.VDryer_Clicked (MouseEvent event) package
Definition at line 181 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VDryer_Pressed()
void com.gluonapplication.ControllerMobileVenting.VDryer_Pressed (MouseEvent event) package
Definition at line 186 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VDryer_Released()
void com.gluonapplication.ControllerMobileVenting.VDryer_Released (MouseEvent event) package
Definition at line 192 of file ControllerMobileVenting.java.
VMain_Clicked()
void com.gluonapplication.ControllerMobileVenting.VMain_Clicked (MouseEvent event) package
Definition at line 133 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VMain_Pressed()
void com.gluonapplication.ControllerMobileVenting.VMain_Pressed (MouseEvent event) package
Definition at line 138 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VMain_Released()
void com.gluonapplication.ControllerMobileVenting.VMain_Released (MouseEvent event) package
Definition at line 144 of file ControllerMobileVenting.java.
VRP_Clicked()
void com.gluonapplication.ControllerMobileVenting.VRP_Clicked (MouseEvent event) package
Definition at line 165 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VRP_Pressed()
void com.gluonapplication.ControllerMobileVenting.VRP_Pressed (MouseEvent event) package
Definition at line 170 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VRP_Released()
void com.gluonapplication.ControllerMobileVenting.VRP_Released (MouseEvent event) package
Definition at line 176 of file ControllerMobileVenting.java.
VSoft_Clicked()
void com.gluonapplication.ControllerMobileVenting.VSoft_Clicked (MouseEvent event) package
Definition at line 149 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
VSoft_Pressed()
void com.gluonapplication.ControllerMobileVenting.VSoft_Pressed (MouseEvent event) package
Definition at line 154 of file ControllerMobileVenting.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
VSoft_Released()
void com.gluonapplication.ControllerMobileVenting.VSoft_Released (MouseEvent event) package
Definition at line 160 of file ControllerMobileVenting.java.
The documentation for this class was generated from the following file:
ControllerMobileVenting.java