VACUUM Supervisor: com.gluonapplication.ControllerTubeN Class Reference
com.gluonapplication.ControllerTubeN Class Reference
Package Functions
void CB_Clicked (MouseEvent event)
void CB_Pressed (MouseEvent event)
void CB_Released (MouseEvent event)
void NE_Clicked (MouseEvent event)
void NE_Pressed (MouseEvent event)
void NE_Released (MouseEvent event)
void Station1200N_Clicked (MouseEvent event)
void Station1200N_Pressed (MouseEvent event)
void Station1200N_Released (MouseEvent event)
void Station2400N_Clicked (MouseEvent event)
void Station2400N_Pressed (MouseEvent event)
void Station2400N_Released (MouseEvent event)
void Station1800N_Clicked (MouseEvent event)
void Station1800N_Pressed (MouseEvent event)
void Station1800N_Released (MouseEvent event)
void Station3000N_Clicked (MouseEvent event)
void Station3000N_Pressed (MouseEvent event)
void Station3000N_Released (MouseEvent event)
void Station300N_Clicked (MouseEvent event)
void Station300N_Pressed (MouseEvent event)
void Station300N_Released (MouseEvent event)
void Station600N_Clicked (MouseEvent event)
void Station600N_Pressed (MouseEvent event)
void Station600N_Released (MouseEvent event)
void V1200N_Clicked (MouseEvent event)
void V1200N_Pressed (MouseEvent event)
void V1200N_Released (MouseEvent event)
void V1800N_Clicked (MouseEvent event)
void V1800N_Pressed (MouseEvent event)
void V1800N_Released (MouseEvent event)
void V2400N_Clicked (MouseEvent event)
void V2400N_Pressed (MouseEvent event)
void V2400N_Released (MouseEvent event)
void V3000N_Clicked (MouseEvent event)
void V3000N_Pressed (MouseEvent event)
void V3000N_Released (MouseEvent event)
void V300N_Clicked (MouseEvent event)
void V300N_Pressed (MouseEvent event)
void V300N_Released (MouseEvent event)
void V600N_Clicked (MouseEvent event)
void V600N_Pressed (MouseEvent event)
void V600N_Released (MouseEvent event)
void V1200N1_Clicked (MouseEvent event)
void V1200N1_Pressed (MouseEvent event)
void V1200N1_Released (MouseEvent event)
void V1800N1_Clicked (MouseEvent event)
void V1800N1_Pressed (MouseEvent event)
void V1800N1_Released (MouseEvent event)
void V2400N1_Clicked (MouseEvent event)
void V2400N1_Pressed (MouseEvent event)
void V2400N1_Released (MouseEvent event)
void V3000N1_Clicked (MouseEvent event)
void V3000N1_Pressed (MouseEvent event)
void V3000N1_Released (MouseEvent event)
void V300N1_Clicked (MouseEvent event)
void V300N1_Pressed (MouseEvent event)
void V300N1_Released (MouseEvent event)
void V600N1_Clicked (MouseEvent event)
void V600N1_Pressed (MouseEvent event)
void V600N1_Released (MouseEvent event)
void VNE_Clicked (MouseEvent event)
void VNE_Pressed (MouseEvent event)
void VNE_Released (MouseEvent event)
void VNI_Clicked (MouseEvent event)
void VNI_Pressed (MouseEvent event)
void VNI_Released (MouseEvent event)
void Ge4_1500N_Clicked (MouseEvent event)
void Ge4_1500N_Pressed (MouseEvent event)
void Ge4_1500N_Released (MouseEvent event)
void Gc4_1500N_Clicked (MouseEvent event)
void Gc4_1500N_Pressed (MouseEvent event)
void Gc4_1500N_Released (MouseEvent event)
void CreateAndShowValveLayer (String name)
void CreateAndShowRGALayer (String name)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 13 of file ControllerTubeN.java.
Member Function Documentation
CB_Clicked()
void com.gluonapplication.ControllerTubeN.CB_Clicked (MouseEvent event) package
Definition at line 157 of file ControllerTubeN.java.
References com.gluonapplication.Main.cb.
CB_Pressed()
void com.gluonapplication.ControllerTubeN.CB_Pressed (MouseEvent event) package
Definition at line 171 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
CB_Released()
void com.gluonapplication.ControllerTubeN.CB_Released (MouseEvent event) package
Definition at line 177 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
CreateAndShowRGALayer()
void com.gluonapplication.ControllerTubeN.CreateAndShowRGALayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 631 of file ControllerTubeN.java.
Referenced by com.gluonapplication.ControllerTubeN.Gc4_1500N_Clicked(), and com.gluonapplication.ControllerTubeN.Ge4_1500N_Clicked().
CreateAndShowValveLayer()
void com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 614 of file ControllerTubeN.java.
Referenced by com.gluonapplication.ControllerTubeN.V1200N1_Clicked(), com.gluonapplication.ControllerTubeN.V1200N_Clicked(), com.gluonapplication.ControllerTubeN.V1800N1_Clicked(), com.gluonapplication.ControllerTubeN.V1800N_Clicked(), com.gluonapplication.ControllerTubeN.V2400N1_Clicked(), com.gluonapplication.ControllerTubeN.V2400N_Clicked(), com.gluonapplication.ControllerTubeN.V3000N1_Clicked(), com.gluonapplication.ControllerTubeN.V3000N_Clicked(), com.gluonapplication.ControllerTubeN.V300N1_Clicked(), com.gluonapplication.ControllerTubeN.V300N_Clicked(), com.gluonapplication.ControllerTubeN.V600N1_Clicked(), com.gluonapplication.ControllerTubeN.V600N_Clicked(), com.gluonapplication.ControllerTubeN.VNE_Clicked(), and com.gluonapplication.ControllerTubeN.VNI_Clicked().
Gc4_1500N_Clicked()
void com.gluonapplication.ControllerTubeN.Gc4_1500N_Clicked (MouseEvent event) package
Definition at line 598 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowRGALayer().
Gc4_1500N_Pressed()
void com.gluonapplication.ControllerTubeN.Gc4_1500N_Pressed (MouseEvent event) package
Definition at line 603 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Gc4_1500N_Released()
void com.gluonapplication.ControllerTubeN.Gc4_1500N_Released (MouseEvent event) package
Definition at line 609 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Ge4_1500N_Clicked()
void com.gluonapplication.ControllerTubeN.Ge4_1500N_Clicked (MouseEvent event) package
Definition at line 582 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowRGALayer().
Ge4_1500N_Pressed()
void com.gluonapplication.ControllerTubeN.Ge4_1500N_Pressed (MouseEvent event) package
Definition at line 587 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Ge4_1500N_Released()
void com.gluonapplication.ControllerTubeN.Ge4_1500N_Released (MouseEvent event) package
Definition at line 593 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
NE_Clicked()
void com.gluonapplication.ControllerTubeN.NE_Clicked (MouseEvent event) package
Definition at line 182 of file ControllerTubeN.java.
References com.gluonapplication.Main.ne.
NE_Pressed()
void com.gluonapplication.ControllerTubeN.NE_Pressed (MouseEvent event) package
Definition at line 196 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
NE_Released()
void com.gluonapplication.ControllerTubeN.NE_Released (MouseEvent event) package
Definition at line 202 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station1200N_Clicked()
void com.gluonapplication.ControllerTubeN.Station1200N_Clicked (MouseEvent event) package
Definition at line 208 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube1200N.
Station1200N_Pressed()
void com.gluonapplication.ControllerTubeN.Station1200N_Pressed (MouseEvent event) package
Definition at line 222 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station1200N_Released()
void com.gluonapplication.ControllerTubeN.Station1200N_Released (MouseEvent event) package
Definition at line 228 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station1800N_Clicked()
void com.gluonapplication.ControllerTubeN.Station1800N_Clicked (MouseEvent event) package
Definition at line 258 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube1800N.
Station1800N_Pressed()
void com.gluonapplication.ControllerTubeN.Station1800N_Pressed (MouseEvent event) package
Definition at line 272 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station1800N_Released()
void com.gluonapplication.ControllerTubeN.Station1800N_Released (MouseEvent event) package
Definition at line 278 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station2400N_Clicked()
void com.gluonapplication.ControllerTubeN.Station2400N_Clicked (MouseEvent event) package
Definition at line 233 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube2400N.
Station2400N_Pressed()
void com.gluonapplication.ControllerTubeN.Station2400N_Pressed (MouseEvent event) package
Definition at line 247 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station2400N_Released()
void com.gluonapplication.ControllerTubeN.Station2400N_Released (MouseEvent event) package
Definition at line 253 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station3000N_Clicked()
void com.gluonapplication.ControllerTubeN.Station3000N_Clicked (MouseEvent event) package
Definition at line 283 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube3000N.
Station3000N_Pressed()
void com.gluonapplication.ControllerTubeN.Station3000N_Pressed (MouseEvent event) package
Definition at line 297 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station3000N_Released()
void com.gluonapplication.ControllerTubeN.Station3000N_Released (MouseEvent event) package
Definition at line 303 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station300N_Clicked()
void com.gluonapplication.ControllerTubeN.Station300N_Clicked (MouseEvent event) package
Definition at line 308 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube300N.
Station300N_Pressed()
void com.gluonapplication.ControllerTubeN.Station300N_Pressed (MouseEvent event) package
Definition at line 322 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station300N_Released()
void com.gluonapplication.ControllerTubeN.Station300N_Released (MouseEvent event) package
Definition at line 328 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Station600N_Clicked()
void com.gluonapplication.ControllerTubeN.Station600N_Clicked (MouseEvent event) package
Definition at line 333 of file ControllerTubeN.java.
References com.gluonapplication.Main.tube600N.
Station600N_Pressed()
void com.gluonapplication.ControllerTubeN.Station600N_Pressed (MouseEvent event) package
Definition at line 347 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
Station600N_Released()
void com.gluonapplication.ControllerTubeN.Station600N_Released (MouseEvent event) package
Definition at line 353 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V1200N1_Clicked()
void com.gluonapplication.ControllerTubeN.V1200N1_Clicked (MouseEvent event) package
Definition at line 454 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V1200N1_Pressed()
void com.gluonapplication.ControllerTubeN.V1200N1_Pressed (MouseEvent event) package
Definition at line 459 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V1200N1_Released()
void com.gluonapplication.ControllerTubeN.V1200N1_Released (MouseEvent event) package
Definition at line 465 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V1200N_Clicked()
void com.gluonapplication.ControllerTubeN.V1200N_Clicked (MouseEvent event) package
Definition at line 358 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V1200N_Pressed()
void com.gluonapplication.ControllerTubeN.V1200N_Pressed (MouseEvent event) package
Definition at line 363 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V1200N_Released()
void com.gluonapplication.ControllerTubeN.V1200N_Released (MouseEvent event) package
Definition at line 369 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V1800N1_Clicked()
void com.gluonapplication.ControllerTubeN.V1800N1_Clicked (MouseEvent event) package
Definition at line 470 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V1800N1_Pressed()
void com.gluonapplication.ControllerTubeN.V1800N1_Pressed (MouseEvent event) package
Definition at line 475 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V1800N1_Released()
void com.gluonapplication.ControllerTubeN.V1800N1_Released (MouseEvent event) package
Definition at line 481 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V1800N_Clicked()
void com.gluonapplication.ControllerTubeN.V1800N_Clicked (MouseEvent event) package
Definition at line 374 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V1800N_Pressed()
void com.gluonapplication.ControllerTubeN.V1800N_Pressed (MouseEvent event) package
Definition at line 379 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V1800N_Released()
void com.gluonapplication.ControllerTubeN.V1800N_Released (MouseEvent event) package
Definition at line 385 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V2400N1_Clicked()
void com.gluonapplication.ControllerTubeN.V2400N1_Clicked (MouseEvent event) package
Definition at line 486 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V2400N1_Pressed()
void com.gluonapplication.ControllerTubeN.V2400N1_Pressed (MouseEvent event) package
Definition at line 491 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V2400N1_Released()
void com.gluonapplication.ControllerTubeN.V2400N1_Released (MouseEvent event) package
Definition at line 497 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V2400N_Clicked()
void com.gluonapplication.ControllerTubeN.V2400N_Clicked (MouseEvent event) package
Definition at line 390 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V2400N_Pressed()
void com.gluonapplication.ControllerTubeN.V2400N_Pressed (MouseEvent event) package
Definition at line 395 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V2400N_Released()
void com.gluonapplication.ControllerTubeN.V2400N_Released (MouseEvent event) package
Definition at line 401 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V3000N1_Clicked()
void com.gluonapplication.ControllerTubeN.V3000N1_Clicked (MouseEvent event) package
Definition at line 502 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V3000N1_Pressed()
void com.gluonapplication.ControllerTubeN.V3000N1_Pressed (MouseEvent event) package
Definition at line 507 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V3000N1_Released()
void com.gluonapplication.ControllerTubeN.V3000N1_Released (MouseEvent event) package
Definition at line 513 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V3000N_Clicked()
void com.gluonapplication.ControllerTubeN.V3000N_Clicked (MouseEvent event) package
Definition at line 406 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V3000N_Pressed()
void com.gluonapplication.ControllerTubeN.V3000N_Pressed (MouseEvent event) package
Definition at line 411 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V3000N_Released()
void com.gluonapplication.ControllerTubeN.V3000N_Released (MouseEvent event) package
Definition at line 417 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V300N1_Clicked()
void com.gluonapplication.ControllerTubeN.V300N1_Clicked (MouseEvent event) package
Definition at line 518 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V300N1_Pressed()
void com.gluonapplication.ControllerTubeN.V300N1_Pressed (MouseEvent event) package
Definition at line 523 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V300N1_Released()
void com.gluonapplication.ControllerTubeN.V300N1_Released (MouseEvent event) package
Definition at line 529 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V300N_Clicked()
void com.gluonapplication.ControllerTubeN.V300N_Clicked (MouseEvent event) package
Definition at line 422 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V300N_Pressed()
void com.gluonapplication.ControllerTubeN.V300N_Pressed (MouseEvent event) package
Definition at line 427 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V300N_Released()
void com.gluonapplication.ControllerTubeN.V300N_Released (MouseEvent event) package
Definition at line 433 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V600N1_Clicked()
void com.gluonapplication.ControllerTubeN.V600N1_Clicked (MouseEvent event) package
Definition at line 534 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V600N1_Pressed()
void com.gluonapplication.ControllerTubeN.V600N1_Pressed (MouseEvent event) package
Definition at line 539 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V600N1_Released()
void com.gluonapplication.ControllerTubeN.V600N1_Released (MouseEvent event) package
Definition at line 545 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
V600N_Clicked()
void com.gluonapplication.ControllerTubeN.V600N_Clicked (MouseEvent event) package
Definition at line 438 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
V600N_Pressed()
void com.gluonapplication.ControllerTubeN.V600N_Pressed (MouseEvent event) package
Definition at line 443 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
V600N_Released()
void com.gluonapplication.ControllerTubeN.V600N_Released (MouseEvent event) package
Definition at line 449 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
VNE_Clicked()
void com.gluonapplication.ControllerTubeN.VNE_Clicked (MouseEvent event) package
Definition at line 550 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
VNE_Pressed()
void com.gluonapplication.ControllerTubeN.VNE_Pressed (MouseEvent event) package
Definition at line 555 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
VNE_Released()
void com.gluonapplication.ControllerTubeN.VNE_Released (MouseEvent event) package
Definition at line 561 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
VNI_Clicked()
void com.gluonapplication.ControllerTubeN.VNI_Clicked (MouseEvent event) package
Definition at line 566 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.CreateAndShowValveLayer().
VNI_Pressed()
void com.gluonapplication.ControllerTubeN.VNI_Pressed (MouseEvent event) package
Definition at line 571 of file ControllerTubeN.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeN.style.
VNI_Released()
void com.gluonapplication.ControllerTubeN.VNI_Released (MouseEvent event) package
Definition at line 577 of file ControllerTubeN.java.
References com.gluonapplication.ControllerTubeN.style.
Member Data Documentation
style
String com.gluonapplication.ControllerTubeN.style = "" package
Definition at line 153 of file ControllerTubeN.java.
Referenced by com.gluonapplication.ControllerTubeN.CB_Pressed(), com.gluonapplication.ControllerTubeN.CB_Released(), com.gluonapplication.ControllerTubeN.Gc4_1500N_Pressed(), com.gluonapplication.ControllerTubeN.Gc4_1500N_Released(), com.gluonapplication.ControllerTubeN.Ge4_1500N_Pressed(), com.gluonapplication.ControllerTubeN.Ge4_1500N_Released(), com.gluonapplication.ControllerTubeN.NE_Pressed(), com.gluonapplication.ControllerTubeN.NE_Released(), com.gluonapplication.ControllerTubeN.Station1200N_Pressed(), com.gluonapplication.ControllerTubeN.Station1200N_Released(), com.gluonapplication.ControllerTubeN.Station1800N_Pressed(), com.gluonapplication.ControllerTubeN.Station1800N_Released(), com.gluonapplication.ControllerTubeN.Station2400N_Pressed(), com.gluonapplication.ControllerTubeN.Station2400N_Released(), com.gluonapplication.ControllerTubeN.Station3000N_Pressed(), com.gluonapplication.ControllerTubeN.Station3000N_Released(), com.gluonapplication.ControllerTubeN.Station300N_Pressed(), com.gluonapplication.ControllerTubeN.Station300N_Released(), com.gluonapplication.ControllerTubeN.Station600N_Pressed(), com.gluonapplication.ControllerTubeN.Station600N_Released(), com.gluonapplication.ControllerTubeN.V1200N1_Pressed(), com.gluonapplication.ControllerTubeN.V1200N1_Released(), com.gluonapplication.ControllerTubeN.V1200N_Pressed(), com.gluonapplication.ControllerTubeN.V1200N_Released(), com.gluonapplication.ControllerTubeN.V1800N1_Pressed(), com.gluonapplication.ControllerTubeN.V1800N1_Released(), com.gluonapplication.ControllerTubeN.V1800N_Pressed(), com.gluonapplication.ControllerTubeN.V1800N_Released(), com.gluonapplication.ControllerTubeN.V2400N1_Pressed(), com.gluonapplication.ControllerTubeN.V2400N1_Released(), com.gluonapplication.ControllerTubeN.V2400N_Pressed(), com.gluonapplication.ControllerTubeN.V2400N_Released(), com.gluonapplication.ControllerTubeN.V3000N1_Pressed(), com.gluonapplication.ControllerTubeN.V3000N1_Released(), com.gluonapplication.ControllerTubeN.V3000N_Pressed(), com.gluonapplication.ControllerTubeN.V3000N_Released(), com.gluonapplication.ControllerTubeN.V300N1_Pressed(), com.gluonapplication.ControllerTubeN.V300N1_Released(), com.gluonapplication.ControllerTubeN.V300N_Pressed(), com.gluonapplication.ControllerTubeN.V300N_Released(), com.gluonapplication.ControllerTubeN.V600N1_Pressed(), com.gluonapplication.ControllerTubeN.V600N1_Released(), com.gluonapplication.ControllerTubeN.V600N_Pressed(), com.gluonapplication.ControllerTubeN.V600N_Released(), com.gluonapplication.ControllerTubeN.VNE_Pressed(), com.gluonapplication.ControllerTubeN.VNE_Released(), com.gluonapplication.ControllerTubeN.VNI_Pressed(), and com.gluonapplication.ControllerTubeN.VNI_Released().
The documentation for this class was generated from the following file:
ControllerTubeN.java