VACUUM Supervisor: com.gluonapplication.ControllerValve Class Reference
com.gluonapplication.ControllerValve Class Reference
Public Member Functions
void initialize ()
Static Public Member Functions
static final byte setBit (byte _byte, int bitPosition, boolean bitValue)
static final int getBit (int n, int k)
Package Functions
void CLOSE_Clicked (MouseEvent event)
void CLOSE_Pressed (MouseEvent event)
void CLOSE_Released (MouseEvent event)
void OPEN_Clicked (MouseEvent event)
void OPEN_Pressed (MouseEvent event)
void OPEN_Released (MouseEvent event)
Package Attributes
String style = ""
String name = ""
DataSet data
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 8 of file ControllerValve.java.
Member Function Documentation
CLOSE_Clicked()
void com.gluonapplication.ControllerValve.CLOSE_Clicked (MouseEvent event) package
Definition at line 38 of file ControllerValve.java.
References com.gluonapplication.ControllerValve.data, com.gluonapplication.DataSet.getDataElement(), com.gluonapplication.ControllerValve.name, com.gluonapplication.DataElement.name, com.gluonapplication.ControllerValve.setBit(), com.gluonapplication.ControlCommand.setCommand(), com.gluonapplication.DataElement.svrName, com.gluonapplication.DataElement.svrValue, and com.gluonapplication.ControlTypes.VALVE_COMMAND_CHANNELS.
CLOSE_Pressed()
void com.gluonapplication.ControllerValve.CLOSE_Pressed (MouseEvent event) package
Definition at line 114 of file ControllerValve.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerValve.style.
CLOSE_Released()
void com.gluonapplication.ControllerValve.CLOSE_Released (MouseEvent event) package
Definition at line 120 of file ControllerValve.java.
References com.gluonapplication.ControllerValve.style.
getBit()
static final int com.gluonapplication.ControllerValve.getBit (int n, int k) static
Definition at line 218 of file ControllerValve.java.
initialize()
void com.gluonapplication.ControllerValve.initialize ()
Definition at line 31 of file ControllerValve.java.
References com.gluonapplication.ControllerValve.data, com.gluonapplication.ViewData.data, com.gluonapplication.ControllerValve.name, and com.gluonapplication.ViewData.name.
OPEN_Clicked()
void com.gluonapplication.ControllerValve.OPEN_Clicked (MouseEvent event) package
Definition at line 125 of file ControllerValve.java.
References com.gluonapplication.ControllerValve.data, com.gluonapplication.DataSet.getDataElement(), com.gluonapplication.ControllerValve.name, com.gluonapplication.DataElement.name, com.gluonapplication.ControllerValve.setBit(), com.gluonapplication.ControlCommand.setCommand(), com.gluonapplication.DataElement.svrName, com.gluonapplication.DataElement.svrValue, and com.gluonapplication.ControlTypes.VALVE_COMMAND_CHANNELS.
OPEN_Pressed()
void com.gluonapplication.ControllerValve.OPEN_Pressed (MouseEvent event) package
Definition at line 200 of file ControllerValve.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerValve.style.
OPEN_Released()
void com.gluonapplication.ControllerValve.OPEN_Released (MouseEvent event) package
Definition at line 206 of file ControllerValve.java.
References com.gluonapplication.ControllerValve.style.
setBit()
static final byte com.gluonapplication.ControllerValve.setBit (byte _byte, int bitPosition, boolean bitValue) static
Definition at line 212 of file ControllerValve.java.
Referenced by com.gluonapplication.ControllerValve.CLOSE_Clicked(), and com.gluonapplication.ControllerValve.OPEN_Clicked().
Member Data Documentation
data
DataSet com.gluonapplication.ControllerValve.data package
Definition at line 26 of file ControllerValve.java.
Referenced by com.gluonapplication.ControllerValve.CLOSE_Clicked(), com.gluonapplication.ControllerValve.initialize(), and com.gluonapplication.ControllerValve.OPEN_Clicked().
name
String com.gluonapplication.ControllerValve.name = "" package
Definition at line 24 of file ControllerValve.java.
Referenced by com.gluonapplication.ControllerValve.CLOSE_Clicked(), com.gluonapplication.ControllerValve.initialize(), and com.gluonapplication.ControllerValve.OPEN_Clicked().
style
String com.gluonapplication.ControllerValve.style = "" package
Definition at line 22 of file ControllerValve.java.
Referenced by com.gluonapplication.ControllerValve.CLOSE_Pressed(), com.gluonapplication.ControllerValve.CLOSE_Released(), com.gluonapplication.ControllerValve.OPEN_Pressed(), and com.gluonapplication.ControllerValve.OPEN_Released().
The documentation for this class was generated from the following file:
ControllerValve.java