VACUUM Supervisor: com.gluonapplication.ControllerTubeStation Class Reference
com.gluonapplication.ControllerTubeStation Class Reference
Package Functions
void SpeedP21_Clicked (MouseEvent event)
void SpeedP21_Pressed (MouseEvent event)
void SpeedP21_Released (MouseEvent event)
void G21_Clicked (MouseEvent event)
void G21_Pressed (MouseEvent event)
void G21_Released (MouseEvent event)
void G22_Clicked (MouseEvent event)
void G22_Pressed (MouseEvent event)
void G22_Released (MouseEvent event)
void G31_Clicked (MouseEvent event)
void G31_Pressed (MouseEvent event)
void G31_Released (MouseEvent event)
void Ga1_Clicked (MouseEvent event)
void Ga1_Pressed (MouseEvent event)
void Ga1_Released (MouseEvent event)
void Ga2_Clicked (MouseEvent event)
void Ga2_Pressed (MouseEvent event)
void Ga2_Released (MouseEvent event)
void Ga3_Clicked (MouseEvent event)
void Ga3_Pressed (MouseEvent event)
void Ga3_Released (MouseEvent event)
void Ga4_Clicked (MouseEvent event)
void Ga4_Pressed (MouseEvent event)
void Ga4_Released (MouseEvent event)
void Ga5_Clicked (MouseEvent event)
void Ga5_Pressed (MouseEvent event)
void Ga5_Released (MouseEvent event)
void P21_Clicked (MouseEvent event)
void P21_Pressed (MouseEvent event)
void P21_Released (MouseEvent event)
void P22_Clicked (MouseEvent event)
void P22_Pressed (MouseEvent event)
void P22_Released (MouseEvent event)
void P31_Clicked (MouseEvent event)
void P31_Pressed (MouseEvent event)
void P31_Released (MouseEvent event)
void P32_Clicked (MouseEvent event)
void P32_Pressed (MouseEvent event)
void P32_Released (MouseEvent event)
void P33_Clicked (MouseEvent event)
void P33_Pressed (MouseEvent event)
void P33_Released (MouseEvent event)
void PressureG21_Clicked (MouseEvent event)
void PressureG21_Pressed (MouseEvent event)
void PressureG21_Released (MouseEvent event)
void PressureG22_Clicked (MouseEvent event)
void PressureG22_Pressed (MouseEvent event)
void PressureG22_Released (MouseEvent event)
void PressureG31_Clicked (MouseEvent event)
void PressureG31_Pressed (MouseEvent event)
void PressureG31_Released (MouseEvent event)
void PressureGa1_Clicked (MouseEvent event)
void PressureGa1_Pressed (MouseEvent event)
void PressureGa1_Released (MouseEvent event)
void PressureGa2_Clicked (MouseEvent event)
void PressureGa2_Pressed (MouseEvent event)
void PressureGa2_Released (MouseEvent event)
void PressureGa3_Clicked (MouseEvent event)
void PressureGa3_Pressed (MouseEvent event)
void PressureGa3_Released (MouseEvent event)
void PressureGa4_Clicked (MouseEvent event)
void PressureGa4_Pressed (MouseEvent event)
void PressureGa4_Released (MouseEvent event)
void V11_Clicked (MouseEvent event)
void V11_Pressed (MouseEvent event)
void V11_Released (MouseEvent event)
void V21_Clicked (MouseEvent event)
void V21_Pressed (MouseEvent event)
void V21_Released (MouseEvent event)
void V22_Clicked (MouseEvent event)
void V22_Pressed (MouseEvent event)
void V22_Released (MouseEvent event)
void V23_Clicked (MouseEvent event)
void V23_Pressed (MouseEvent event)
void V23_Released (MouseEvent event)
void V25_Clicked (MouseEvent event)
void V25_Pressed (MouseEvent event)
void V25_Released (MouseEvent event)
void V31_Clicked (MouseEvent event)
void V31_Pressed (MouseEvent event)
void V31_Released (MouseEvent event)
void V32_Clicked (MouseEvent event)
void V32_Pressed (MouseEvent event)
void V32_Released (MouseEvent event)
void V91_Clicked (MouseEvent event)
void V91_Pressed (MouseEvent event)
void V91_released (MouseEvent event)
void Va1_Clicked (MouseEvent event)
void Va1_Pressed (MouseEvent event)
void Va1_Released (MouseEvent event)
void Va2_Clicked (MouseEvent event)
void Va2_Pressed (MouseEvent event)
void Va2_Released (MouseEvent event)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowRGALayer (String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 12 of file ControllerTubeStation.java.
Member Function Documentation
G21_Clicked()
void com.gluonapplication.ControllerTubeStation.G21_Clicked (MouseEvent event) package
Definition at line 196 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G21_Pressed()
void com.gluonapplication.ControllerTubeStation.G21_Pressed (MouseEvent event) package
Definition at line 201 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
G21_Released()
void com.gluonapplication.ControllerTubeStation.G21_Released (MouseEvent event) package
Definition at line 207 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
G22_Clicked()
void com.gluonapplication.ControllerTubeStation.G22_Clicked (MouseEvent event) package
Definition at line 212 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G22_Pressed()
void com.gluonapplication.ControllerTubeStation.G22_Pressed (MouseEvent event) package
Definition at line 217 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
G22_Released()
void com.gluonapplication.ControllerTubeStation.G22_Released (MouseEvent event) package
Definition at line 223 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
G31_Clicked()
void com.gluonapplication.ControllerTubeStation.G31_Clicked (MouseEvent event) package
Definition at line 228 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G31_Pressed()
void com.gluonapplication.ControllerTubeStation.G31_Pressed (MouseEvent event) package
Definition at line 233 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
G31_Released()
void com.gluonapplication.ControllerTubeStation.G31_Released (MouseEvent event) package
Definition at line 239 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Ga1_Clicked()
void com.gluonapplication.ControllerTubeStation.Ga1_Clicked (MouseEvent event) package
Definition at line 244 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga1_Pressed()
void com.gluonapplication.ControllerTubeStation.Ga1_Pressed (MouseEvent event) package
Definition at line 249 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Ga1_Released()
void com.gluonapplication.ControllerTubeStation.Ga1_Released (MouseEvent event) package
Definition at line 255 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Ga2_Clicked()
void com.gluonapplication.ControllerTubeStation.Ga2_Clicked (MouseEvent event) package
Definition at line 260 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga2_Pressed()
void com.gluonapplication.ControllerTubeStation.Ga2_Pressed (MouseEvent event) package
Definition at line 265 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Ga2_Released()
void com.gluonapplication.ControllerTubeStation.Ga2_Released (MouseEvent event) package
Definition at line 271 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Ga3_Clicked()
void com.gluonapplication.ControllerTubeStation.Ga3_Clicked (MouseEvent event) package
Definition at line 276 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga3_Pressed()
void com.gluonapplication.ControllerTubeStation.Ga3_Pressed (MouseEvent event) package
Definition at line 281 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Ga3_Released()
void com.gluonapplication.ControllerTubeStation.Ga3_Released (MouseEvent event) package
Definition at line 287 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Ga4_Clicked()
void com.gluonapplication.ControllerTubeStation.Ga4_Clicked (MouseEvent event) package
Definition at line 292 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga4_Pressed()
void com.gluonapplication.ControllerTubeStation.Ga4_Pressed (MouseEvent event) package
Definition at line 297 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Ga4_Released()
void com.gluonapplication.ControllerTubeStation.Ga4_Released (MouseEvent event) package
Definition at line 303 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Ga5_Clicked()
void com.gluonapplication.ControllerTubeStation.Ga5_Clicked (MouseEvent event) package
Definition at line 308 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowRGALayer().
Ga5_Pressed()
void com.gluonapplication.ControllerTubeStation.Ga5_Pressed (MouseEvent event) package
Definition at line 313 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Ga5_Released()
void com.gluonapplication.ControllerTubeStation.Ga5_Released (MouseEvent event) package
Definition at line 319 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
P21_Clicked()
void com.gluonapplication.ControllerTubeStation.P21_Clicked (MouseEvent event) package
Definition at line 324 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTurboLayer().
P21_Pressed()
void com.gluonapplication.ControllerTubeStation.P21_Pressed (MouseEvent event) package
Definition at line 329 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
P21_Released()
void com.gluonapplication.ControllerTubeStation.P21_Released (MouseEvent event) package
Definition at line 335 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
P22_Clicked()
void com.gluonapplication.ControllerTubeStation.P22_Clicked (MouseEvent event) package
Definition at line 340 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P22_Pressed()
void com.gluonapplication.ControllerTubeStation.P22_Pressed (MouseEvent event) package
Definition at line 345 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
P22_Released()
void com.gluonapplication.ControllerTubeStation.P22_Released (MouseEvent event) package
Definition at line 351 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
P31_Clicked()
void com.gluonapplication.ControllerTubeStation.P31_Clicked (MouseEvent event) package
Definition at line 356 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTitaneLayer().
P31_Pressed()
void com.gluonapplication.ControllerTubeStation.P31_Pressed (MouseEvent event) package
Definition at line 361 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
P31_Released()
void com.gluonapplication.ControllerTubeStation.P31_Released (MouseEvent event) package
Definition at line 367 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
P32_Clicked()
void com.gluonapplication.ControllerTubeStation.P32_Clicked (MouseEvent event) package
Definition at line 372 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTitaneLayer().
P32_Pressed()
void com.gluonapplication.ControllerTubeStation.P32_Pressed (MouseEvent event) package
Definition at line 377 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
P32_Released()
void com.gluonapplication.ControllerTubeStation.P32_Released (MouseEvent event) package
Definition at line 383 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
P33_Clicked()
void com.gluonapplication.ControllerTubeStation.P33_Clicked (MouseEvent event) package
Definition at line 388 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowIonicLayer().
P33_Pressed()
void com.gluonapplication.ControllerTubeStation.P33_Pressed (MouseEvent event) package
Definition at line 393 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
P33_Released()
void com.gluonapplication.ControllerTubeStation.P33_Released (MouseEvent event) package
Definition at line 399 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureG21_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureG21_Clicked (MouseEvent event) package
Definition at line 404 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG21_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureG21_Pressed (MouseEvent event) package
Definition at line 409 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureG21_Released()
void com.gluonapplication.ControllerTubeStation.PressureG21_Released (MouseEvent event) package
Definition at line 415 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureG22_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureG22_Clicked (MouseEvent event) package
Definition at line 420 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG22_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureG22_Pressed (MouseEvent event) package
Definition at line 425 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureG22_Released()
void com.gluonapplication.ControllerTubeStation.PressureG22_Released (MouseEvent event) package
Definition at line 431 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureG31_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureG31_Clicked (MouseEvent event) package
Definition at line 436 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG31_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureG31_Pressed (MouseEvent event) package
Definition at line 441 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureG31_Released()
void com.gluonapplication.ControllerTubeStation.PressureG31_Released (MouseEvent event) package
Definition at line 447 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureGa1_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureGa1_Clicked (MouseEvent event) package
Definition at line 452 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa1_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureGa1_Pressed (MouseEvent event) package
Definition at line 457 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureGa1_Released()
void com.gluonapplication.ControllerTubeStation.PressureGa1_Released (MouseEvent event) package
Definition at line 463 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureGa2_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureGa2_Clicked (MouseEvent event) package
Definition at line 468 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa2_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureGa2_Pressed (MouseEvent event) package
Definition at line 473 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureGa2_Released()
void com.gluonapplication.ControllerTubeStation.PressureGa2_Released (MouseEvent event) package
Definition at line 479 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureGa3_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureGa3_Clicked (MouseEvent event) package
Definition at line 484 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa3_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureGa3_Pressed (MouseEvent event) package
Definition at line 489 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureGa3_Released()
void com.gluonapplication.ControllerTubeStation.PressureGa3_Released (MouseEvent event) package
Definition at line 495 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
PressureGa4_Clicked()
void com.gluonapplication.ControllerTubeStation.PressureGa4_Clicked (MouseEvent event) package
Definition at line 500 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa4_Pressed()
void com.gluonapplication.ControllerTubeStation.PressureGa4_Pressed (MouseEvent event) package
Definition at line 505 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
PressureGa4_Released()
void com.gluonapplication.ControllerTubeStation.PressureGa4_Released (MouseEvent event) package
Definition at line 511 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
SpeedP21_Clicked()
void com.gluonapplication.ControllerTubeStation.SpeedP21_Clicked (MouseEvent event) package
Definition at line 180 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
SpeedP21_Pressed()
void com.gluonapplication.ControllerTubeStation.SpeedP21_Pressed (MouseEvent event) package
Definition at line 185 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
SpeedP21_Released()
void com.gluonapplication.ControllerTubeStation.SpeedP21_Released (MouseEvent event) package
Definition at line 191 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V11_Clicked()
void com.gluonapplication.ControllerTubeStation.V11_Clicked (MouseEvent event) package
Definition at line 516 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V11_Pressed()
void com.gluonapplication.ControllerTubeStation.V11_Pressed (MouseEvent event) package
Definition at line 521 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V11_Released()
void com.gluonapplication.ControllerTubeStation.V11_Released (MouseEvent event) package
Definition at line 527 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V21_Clicked()
void com.gluonapplication.ControllerTubeStation.V21_Clicked (MouseEvent event) package
Definition at line 532 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V21_Pressed()
void com.gluonapplication.ControllerTubeStation.V21_Pressed (MouseEvent event) package
Definition at line 537 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V21_Released()
void com.gluonapplication.ControllerTubeStation.V21_Released (MouseEvent event) package
Definition at line 543 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V22_Clicked()
void com.gluonapplication.ControllerTubeStation.V22_Clicked (MouseEvent event) package
Definition at line 548 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V22_Pressed()
void com.gluonapplication.ControllerTubeStation.V22_Pressed (MouseEvent event) package
Definition at line 553 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V22_Released()
void com.gluonapplication.ControllerTubeStation.V22_Released (MouseEvent event) package
Definition at line 559 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V23_Clicked()
void com.gluonapplication.ControllerTubeStation.V23_Clicked (MouseEvent event) package
Definition at line 564 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V23_Pressed()
void com.gluonapplication.ControllerTubeStation.V23_Pressed (MouseEvent event) package
Definition at line 569 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V23_Released()
void com.gluonapplication.ControllerTubeStation.V23_Released (MouseEvent event) package
Definition at line 575 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V25_Clicked()
void com.gluonapplication.ControllerTubeStation.V25_Clicked (MouseEvent event) package
Definition at line 580 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V25_Pressed()
void com.gluonapplication.ControllerTubeStation.V25_Pressed (MouseEvent event) package
Definition at line 585 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V25_Released()
void com.gluonapplication.ControllerTubeStation.V25_Released (MouseEvent event) package
Definition at line 591 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V31_Clicked()
void com.gluonapplication.ControllerTubeStation.V31_Clicked (MouseEvent event) package
Definition at line 596 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V31_Pressed()
void com.gluonapplication.ControllerTubeStation.V31_Pressed (MouseEvent event) package
Definition at line 601 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V31_Released()
void com.gluonapplication.ControllerTubeStation.V31_Released (MouseEvent event) package
Definition at line 607 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V32_Clicked()
void com.gluonapplication.ControllerTubeStation.V32_Clicked (MouseEvent event) package
Definition at line 612 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V32_Pressed()
void com.gluonapplication.ControllerTubeStation.V32_Pressed (MouseEvent event) package
Definition at line 617 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V32_Released()
void com.gluonapplication.ControllerTubeStation.V32_Released (MouseEvent event) package
Definition at line 623 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
V91_Clicked()
void com.gluonapplication.ControllerTubeStation.V91_Clicked (MouseEvent event) package
Definition at line 628 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V91_Pressed()
void com.gluonapplication.ControllerTubeStation.V91_Pressed (MouseEvent event) package
Definition at line 633 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
V91_released()
void com.gluonapplication.ControllerTubeStation.V91_released (MouseEvent event) package
Definition at line 639 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Va1_Clicked()
void com.gluonapplication.ControllerTubeStation.Va1_Clicked (MouseEvent event) package
Definition at line 644 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Va1_Pressed()
void com.gluonapplication.ControllerTubeStation.Va1_Pressed (MouseEvent event) package
Definition at line 649 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Va1_Released()
void com.gluonapplication.ControllerTubeStation.Va1_Released (MouseEvent event) package
Definition at line 655 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Va2_Clicked()
void com.gluonapplication.ControllerTubeStation.Va2_Clicked (MouseEvent event) package
Definition at line 660 of file ControllerTubeStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Va2_Pressed()
void com.gluonapplication.ControllerTubeStation.Va2_Pressed (MouseEvent event) package
Definition at line 665 of file ControllerTubeStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeStation.style.
Va2_Released()
void com.gluonapplication.ControllerTubeStation.Va2_Released (MouseEvent event) package
Definition at line 671 of file ControllerTubeStation.java.
References com.gluonapplication.ControllerTubeStation.style.
Member Data Documentation
style
String com.gluonapplication.ControllerTubeStation.style = "" package
Definition at line 176 of file ControllerTubeStation.java.
Referenced by com.gluonapplication.ControllerTubeStation.G21_Pressed(), com.gluonapplication.ControllerTubeStation.G21_Released(), com.gluonapplication.ControllerTubeStation.G22_Pressed(), com.gluonapplication.ControllerTubeStation.G22_Released(), com.gluonapplication.ControllerTubeStation.G31_Pressed(), com.gluonapplication.ControllerTubeStation.G31_Released(), com.gluonapplication.ControllerTubeStation.Ga1_Pressed(), com.gluonapplication.ControllerTubeStation.Ga1_Released(), com.gluonapplication.ControllerTubeStation.Ga2_Pressed(), com.gluonapplication.ControllerTubeStation.Ga2_Released(), com.gluonapplication.ControllerTubeStation.Ga3_Pressed(), com.gluonapplication.ControllerTubeStation.Ga3_Released(), com.gluonapplication.ControllerTubeStation.Ga4_Pressed(), com.gluonapplication.ControllerTubeStation.Ga4_Released(), com.gluonapplication.ControllerTubeStation.Ga5_Pressed(), com.gluonapplication.ControllerTubeStation.Ga5_Released(), com.gluonapplication.ControllerTubeStation.P21_Pressed(), com.gluonapplication.ControllerTubeStation.P21_Released(), com.gluonapplication.ControllerTubeStation.P22_Pressed(), com.gluonapplication.ControllerTubeStation.P22_Released(), com.gluonapplication.ControllerTubeStation.P31_Pressed(), com.gluonapplication.ControllerTubeStation.P31_Released(), com.gluonapplication.ControllerTubeStation.P32_Pressed(), com.gluonapplication.ControllerTubeStation.P32_Released(), com.gluonapplication.ControllerTubeStation.P33_Pressed(), com.gluonapplication.ControllerTubeStation.P33_Released(), com.gluonapplication.ControllerTubeStation.PressureG21_Pressed(), com.gluonapplication.ControllerTubeStation.PressureG21_Released(), com.gluonapplication.ControllerTubeStation.PressureG22_Pressed(), com.gluonapplication.ControllerTubeStation.PressureG22_Released(), com.gluonapplication.ControllerTubeStation.PressureG31_Pressed(), com.gluonapplication.ControllerTubeStation.PressureG31_Released(), com.gluonapplication.ControllerTubeStation.PressureGa1_Pressed(), com.gluonapplication.ControllerTubeStation.PressureGa1_Released(), com.gluonapplication.ControllerTubeStation.PressureGa2_Pressed(), com.gluonapplication.ControllerTubeStation.PressureGa2_Released(), com.gluonapplication.ControllerTubeStation.PressureGa3_Pressed(), com.gluonapplication.ControllerTubeStation.PressureGa3_Released(), com.gluonapplication.ControllerTubeStation.PressureGa4_Pressed(), com.gluonapplication.ControllerTubeStation.PressureGa4_Released(), com.gluonapplication.ControllerTubeStation.SpeedP21_Pressed(), com.gluonapplication.ControllerTubeStation.SpeedP21_Released(), com.gluonapplication.ControllerTubeStation.V11_Pressed(), com.gluonapplication.ControllerTubeStation.V11_Released(), com.gluonapplication.ControllerTubeStation.V21_Pressed(), com.gluonapplication.ControllerTubeStation.V21_Released(), com.gluonapplication.ControllerTubeStation.V22_Pressed(), com.gluonapplication.ControllerTubeStation.V22_Released(), com.gluonapplication.ControllerTubeStation.V23_Pressed(), com.gluonapplication.ControllerTubeStation.V23_Released(), com.gluonapplication.ControllerTubeStation.V25_Pressed(), com.gluonapplication.ControllerTubeStation.V25_Released(), com.gluonapplication.ControllerTubeStation.V31_Pressed(), com.gluonapplication.ControllerTubeStation.V31_Released(), com.gluonapplication.ControllerTubeStation.V32_Pressed(), com.gluonapplication.ControllerTubeStation.V32_Released(), com.gluonapplication.ControllerTubeStation.V91_Pressed(), com.gluonapplication.ControllerTubeStation.V91_released(), com.gluonapplication.ControllerTubeStation.Va1_Pressed(), com.gluonapplication.ControllerTubeStation.Va1_Released(), com.gluonapplication.ControllerTubeStation.Va2_Pressed(), and com.gluonapplication.ControllerTubeStation.Va2_Released().
The documentation for this class was generated from the following file:
ControllerTubeStation.java