VACUUM Supervisor: com.gluonapplication.ControllerTubeLalStation Class Reference
com.gluonapplication.ControllerTubeLalStation Class Reference
Package Functions
void SpeedP21_Clicked (MouseEvent event)
void SpeedP21_Pressed (MouseEvent event)
void SpeedP21_Released (MouseEvent event)
void G21_Clicked (MouseEvent event)
void G21_Pressed (MouseEvent event)
void G21_Released (MouseEvent event)
void G22_Clicked (MouseEvent event)
void G22_Pressed (MouseEvent event)
void G22_Released (MouseEvent event)
void G31_Clicked (MouseEvent event)
void G31_Pressed (MouseEvent event)
void G31_Released (MouseEvent event)
void Ga1_Clicked (MouseEvent event)
void Ga1_Pressed (MouseEvent event)
void Ga1_Released (MouseEvent event)
void Ga2_Clicked (MouseEvent event)
void Ga2_Pressed (MouseEvent event)
void Ga2_Released (MouseEvent event)
void Ga3_Clicked (MouseEvent event)
void Ga3_Pressed (MouseEvent event)
void Ga3_Released (MouseEvent event)
void Ga4_Clicked (MouseEvent event)
void Ga4_Pressed (MouseEvent event)
void Ga4_Released (MouseEvent event)
void Ga5_Clicked (MouseEvent event)
void Ga5_Pressed (MouseEvent event)
void Ga5_Released (MouseEvent event)
void P21_Clicked (MouseEvent event)
void P21_Pressed (MouseEvent event)
void P21_Released (MouseEvent event)
void P22_Clicked (MouseEvent event)
void P22_Pressed (MouseEvent event)
void P22_Released (MouseEvent event)
void P31_Clicked (MouseEvent event)
void P31_Pressed (MouseEvent event)
void P31_Released (MouseEvent event)
void P32_Clicked (MouseEvent event)
void P32_Pressed (MouseEvent event)
void P32_Released (MouseEvent event)
void P33_Clicked (MouseEvent event)
void P33_Pressed (MouseEvent event)
void P33_Released (MouseEvent event)
void P23_Clicked (MouseEvent event)
void P23_Pressed (MouseEvent event)
void P23_Released (MouseEvent event)
void PressureG21_Clicked (MouseEvent event)
void PressureG21_Pressed (MouseEvent event)
void PressureG21_Released (MouseEvent event)
void PressureG22_Clicked (MouseEvent event)
void PressureG22_Pressed (MouseEvent event)
void PressureG22_Released (MouseEvent event)
void PressureG31_Clicked (MouseEvent event)
void PressureG31_Pressed (MouseEvent event)
void PressureG31_Released (MouseEvent event)
void PressureGa1_Clicked (MouseEvent event)
void PressureGa1_Pressed (MouseEvent event)
void PressureGa1_Released (MouseEvent event)
void PressureGa2_Clicked (MouseEvent event)
void PressureGa2_Pressed (MouseEvent event)
void PressureGa2_Released (MouseEvent event)
void PressureGa3_Clicked (MouseEvent event)
void PressureGa3_Pressed (MouseEvent event)
void PressureGa3_Released (MouseEvent event)
void PressureGa4_Clicked (MouseEvent event)
void PressureGa4_Pressed (MouseEvent event)
void PressureGa4_Released (MouseEvent event)
void V11_Clicked (MouseEvent event)
void V11_Pressed (MouseEvent event)
void V11_Released (MouseEvent event)
void V21_Clicked (MouseEvent event)
void V21_Pressed (MouseEvent event)
void V21_Released (MouseEvent event)
void V22_Clicked (MouseEvent event)
void V22_Pressed (MouseEvent event)
void V22_Released (MouseEvent event)
void V23_Clicked (MouseEvent event)
void V23_Pressed (MouseEvent event)
void V23_Released (MouseEvent event)
void V25_Clicked (MouseEvent event)
void V25_Pressed (MouseEvent event)
void V25_Released (MouseEvent event)
void V31_Clicked (MouseEvent event)
void V31_Pressed (MouseEvent event)
void V31_Released (MouseEvent event)
void V32_Clicked (MouseEvent event)
void V32_Pressed (MouseEvent event)
void V32_Released (MouseEvent event)
void V91_Clicked (MouseEvent event)
void V91_Pressed (MouseEvent event)
void V91_released (MouseEvent event)
void Va1_Clicked (MouseEvent event)
void Va1_Pressed (MouseEvent event)
void Va1_Released (MouseEvent event)
void Va2_Clicked (MouseEvent event)
void Va2_Pressed (MouseEvent event)
void Va2_Released (MouseEvent event)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowRGALayer (String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 12 of file ControllerTubeLalStation.java.
Member Function Documentation
G21_Clicked()
void com.gluonapplication.ControllerTubeLalStation.G21_Clicked (MouseEvent event) package
Definition at line 202 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G21_Pressed()
void com.gluonapplication.ControllerTubeLalStation.G21_Pressed (MouseEvent event) package
Definition at line 207 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
G21_Released()
void com.gluonapplication.ControllerTubeLalStation.G21_Released (MouseEvent event) package
Definition at line 213 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
G22_Clicked()
void com.gluonapplication.ControllerTubeLalStation.G22_Clicked (MouseEvent event) package
Definition at line 218 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G22_Pressed()
void com.gluonapplication.ControllerTubeLalStation.G22_Pressed (MouseEvent event) package
Definition at line 223 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
G22_Released()
void com.gluonapplication.ControllerTubeLalStation.G22_Released (MouseEvent event) package
Definition at line 229 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
G31_Clicked()
void com.gluonapplication.ControllerTubeLalStation.G31_Clicked (MouseEvent event) package
Definition at line 234 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G31_Pressed()
void com.gluonapplication.ControllerTubeLalStation.G31_Pressed (MouseEvent event) package
Definition at line 239 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
G31_Released()
void com.gluonapplication.ControllerTubeLalStation.G31_Released (MouseEvent event) package
Definition at line 245 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Ga1_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Ga1_Clicked (MouseEvent event) package
Definition at line 250 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga1_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Ga1_Pressed (MouseEvent event) package
Definition at line 255 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Ga1_Released()
void com.gluonapplication.ControllerTubeLalStation.Ga1_Released (MouseEvent event) package
Definition at line 261 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Ga2_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Ga2_Clicked (MouseEvent event) package
Definition at line 266 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga2_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Ga2_Pressed (MouseEvent event) package
Definition at line 271 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Ga2_Released()
void com.gluonapplication.ControllerTubeLalStation.Ga2_Released (MouseEvent event) package
Definition at line 277 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Ga3_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Ga3_Clicked (MouseEvent event) package
Definition at line 282 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga3_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Ga3_Pressed (MouseEvent event) package
Definition at line 287 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Ga3_Released()
void com.gluonapplication.ControllerTubeLalStation.Ga3_Released (MouseEvent event) package
Definition at line 293 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Ga4_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Ga4_Clicked (MouseEvent event) package
Definition at line 298 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Ga4_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Ga4_Pressed (MouseEvent event) package
Definition at line 303 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Ga4_Released()
void com.gluonapplication.ControllerTubeLalStation.Ga4_Released (MouseEvent event) package
Definition at line 309 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Ga5_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Ga5_Clicked (MouseEvent event) package
Definition at line 314 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowRGALayer().
Ga5_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Ga5_Pressed (MouseEvent event) package
Definition at line 319 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Ga5_Released()
void com.gluonapplication.ControllerTubeLalStation.Ga5_Released (MouseEvent event) package
Definition at line 325 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P21_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P21_Clicked (MouseEvent event) package
Definition at line 330 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTurboLayer().
P21_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P21_Pressed (MouseEvent event) package
Definition at line 335 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P21_Released()
void com.gluonapplication.ControllerTubeLalStation.P21_Released (MouseEvent event) package
Definition at line 341 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P22_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P22_Clicked (MouseEvent event) package
Definition at line 346 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P22_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P22_Pressed (MouseEvent event) package
Definition at line 351 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P22_Released()
void com.gluonapplication.ControllerTubeLalStation.P22_Released (MouseEvent event) package
Definition at line 357 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P23_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P23_Clicked (MouseEvent event) package
Definition at line 410 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowIonicLayer().
P23_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P23_Pressed (MouseEvent event) package
Definition at line 415 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P23_Released()
void com.gluonapplication.ControllerTubeLalStation.P23_Released (MouseEvent event) package
Definition at line 421 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P31_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P31_Clicked (MouseEvent event) package
Definition at line 362 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTitaneLayer().
P31_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P31_Pressed (MouseEvent event) package
Definition at line 367 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P31_Released()
void com.gluonapplication.ControllerTubeLalStation.P31_Released (MouseEvent event) package
Definition at line 373 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P32_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P32_Clicked (MouseEvent event) package
Definition at line 378 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTitaneLayer().
P32_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P32_Pressed (MouseEvent event) package
Definition at line 383 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P32_Released()
void com.gluonapplication.ControllerTubeLalStation.P32_Released (MouseEvent event) package
Definition at line 389 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
P33_Clicked()
void com.gluonapplication.ControllerTubeLalStation.P33_Clicked (MouseEvent event) package
Definition at line 394 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowIonicLayer().
P33_Pressed()
void com.gluonapplication.ControllerTubeLalStation.P33_Pressed (MouseEvent event) package
Definition at line 399 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
P33_Released()
void com.gluonapplication.ControllerTubeLalStation.P33_Released (MouseEvent event) package
Definition at line 405 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureG21_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureG21_Clicked (MouseEvent event) package
Definition at line 426 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG21_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureG21_Pressed (MouseEvent event) package
Definition at line 431 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureG21_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureG21_Released (MouseEvent event) package
Definition at line 437 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureG22_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureG22_Clicked (MouseEvent event) package
Definition at line 442 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG22_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureG22_Pressed (MouseEvent event) package
Definition at line 447 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureG22_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureG22_Released (MouseEvent event) package
Definition at line 453 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureG31_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureG31_Clicked (MouseEvent event) package
Definition at line 458 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG31_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureG31_Pressed (MouseEvent event) package
Definition at line 463 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureG31_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureG31_Released (MouseEvent event) package
Definition at line 469 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureGa1_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureGa1_Clicked (MouseEvent event) package
Definition at line 474 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa1_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureGa1_Pressed (MouseEvent event) package
Definition at line 479 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureGa1_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureGa1_Released (MouseEvent event) package
Definition at line 485 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureGa2_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureGa2_Clicked (MouseEvent event) package
Definition at line 490 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa2_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureGa2_Pressed (MouseEvent event) package
Definition at line 495 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureGa2_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureGa2_Released (MouseEvent event) package
Definition at line 501 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureGa3_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureGa3_Clicked (MouseEvent event) package
Definition at line 506 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa3_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureGa3_Pressed (MouseEvent event) package
Definition at line 511 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureGa3_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureGa3_Released (MouseEvent event) package
Definition at line 517 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
PressureGa4_Clicked()
void com.gluonapplication.ControllerTubeLalStation.PressureGa4_Clicked (MouseEvent event) package
Definition at line 522 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGa4_Pressed()
void com.gluonapplication.ControllerTubeLalStation.PressureGa4_Pressed (MouseEvent event) package
Definition at line 527 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
PressureGa4_Released()
void com.gluonapplication.ControllerTubeLalStation.PressureGa4_Released (MouseEvent event) package
Definition at line 533 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
SpeedP21_Clicked()
void com.gluonapplication.ControllerTubeLalStation.SpeedP21_Clicked (MouseEvent event) package
Definition at line 186 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
SpeedP21_Pressed()
void com.gluonapplication.ControllerTubeLalStation.SpeedP21_Pressed (MouseEvent event) package
Definition at line 191 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
SpeedP21_Released()
void com.gluonapplication.ControllerTubeLalStation.SpeedP21_Released (MouseEvent event) package
Definition at line 197 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V11_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V11_Clicked (MouseEvent event) package
Definition at line 538 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V11_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V11_Pressed (MouseEvent event) package
Definition at line 543 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V11_Released()
void com.gluonapplication.ControllerTubeLalStation.V11_Released (MouseEvent event) package
Definition at line 549 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V21_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V21_Clicked (MouseEvent event) package
Definition at line 554 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V21_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V21_Pressed (MouseEvent event) package
Definition at line 559 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V21_Released()
void com.gluonapplication.ControllerTubeLalStation.V21_Released (MouseEvent event) package
Definition at line 565 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V22_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V22_Clicked (MouseEvent event) package
Definition at line 570 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V22_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V22_Pressed (MouseEvent event) package
Definition at line 575 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V22_Released()
void com.gluonapplication.ControllerTubeLalStation.V22_Released (MouseEvent event) package
Definition at line 581 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V23_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V23_Clicked (MouseEvent event) package
Definition at line 586 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V23_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V23_Pressed (MouseEvent event) package
Definition at line 591 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V23_Released()
void com.gluonapplication.ControllerTubeLalStation.V23_Released (MouseEvent event) package
Definition at line 597 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V25_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V25_Clicked (MouseEvent event) package
Definition at line 602 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V25_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V25_Pressed (MouseEvent event) package
Definition at line 607 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V25_Released()
void com.gluonapplication.ControllerTubeLalStation.V25_Released (MouseEvent event) package
Definition at line 613 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V31_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V31_Clicked (MouseEvent event) package
Definition at line 618 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V31_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V31_Pressed (MouseEvent event) package
Definition at line 623 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V31_Released()
void com.gluonapplication.ControllerTubeLalStation.V31_Released (MouseEvent event) package
Definition at line 629 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V32_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V32_Clicked (MouseEvent event) package
Definition at line 634 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V32_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V32_Pressed (MouseEvent event) package
Definition at line 639 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V32_Released()
void com.gluonapplication.ControllerTubeLalStation.V32_Released (MouseEvent event) package
Definition at line 645 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
V91_Clicked()
void com.gluonapplication.ControllerTubeLalStation.V91_Clicked (MouseEvent event) package
Definition at line 650 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V91_Pressed()
void com.gluonapplication.ControllerTubeLalStation.V91_Pressed (MouseEvent event) package
Definition at line 655 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
V91_released()
void com.gluonapplication.ControllerTubeLalStation.V91_released (MouseEvent event) package
Definition at line 661 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Va1_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Va1_Clicked (MouseEvent event) package
Definition at line 666 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Va1_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Va1_Pressed (MouseEvent event) package
Definition at line 671 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Va1_Released()
void com.gluonapplication.ControllerTubeLalStation.Va1_Released (MouseEvent event) package
Definition at line 677 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Va2_Clicked()
void com.gluonapplication.ControllerTubeLalStation.Va2_Clicked (MouseEvent event) package
Definition at line 682 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Va2_Pressed()
void com.gluonapplication.ControllerTubeLalStation.Va2_Pressed (MouseEvent event) package
Definition at line 687 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeLalStation.style.
Va2_Released()
void com.gluonapplication.ControllerTubeLalStation.Va2_Released (MouseEvent event) package
Definition at line 693 of file ControllerTubeLalStation.java.
References com.gluonapplication.ControllerTubeLalStation.style.
Member Data Documentation
style
String com.gluonapplication.ControllerTubeLalStation.style = "" package
Definition at line 182 of file ControllerTubeLalStation.java.
Referenced by com.gluonapplication.ControllerTubeLalStation.G21_Pressed(), com.gluonapplication.ControllerTubeLalStation.G21_Released(), com.gluonapplication.ControllerTubeLalStation.G22_Pressed(), com.gluonapplication.ControllerTubeLalStation.G22_Released(), com.gluonapplication.ControllerTubeLalStation.G31_Pressed(), com.gluonapplication.ControllerTubeLalStation.G31_Released(), com.gluonapplication.ControllerTubeLalStation.Ga1_Pressed(), com.gluonapplication.ControllerTubeLalStation.Ga1_Released(), com.gluonapplication.ControllerTubeLalStation.Ga2_Pressed(), com.gluonapplication.ControllerTubeLalStation.Ga2_Released(), com.gluonapplication.ControllerTubeLalStation.Ga3_Pressed(), com.gluonapplication.ControllerTubeLalStation.Ga3_Released(), com.gluonapplication.ControllerTubeLalStation.Ga4_Pressed(), com.gluonapplication.ControllerTubeLalStation.Ga4_Released(), com.gluonapplication.ControllerTubeLalStation.Ga5_Pressed(), com.gluonapplication.ControllerTubeLalStation.Ga5_Released(), com.gluonapplication.ControllerTubeLalStation.P21_Pressed(), com.gluonapplication.ControllerTubeLalStation.P21_Released(), com.gluonapplication.ControllerTubeLalStation.P22_Pressed(), com.gluonapplication.ControllerTubeLalStation.P22_Released(), com.gluonapplication.ControllerTubeLalStation.P23_Pressed(), com.gluonapplication.ControllerTubeLalStation.P23_Released(), com.gluonapplication.ControllerTubeLalStation.P31_Pressed(), com.gluonapplication.ControllerTubeLalStation.P31_Released(), com.gluonapplication.ControllerTubeLalStation.P32_Pressed(), com.gluonapplication.ControllerTubeLalStation.P32_Released(), com.gluonapplication.ControllerTubeLalStation.P33_Pressed(), com.gluonapplication.ControllerTubeLalStation.P33_Released(), com.gluonapplication.ControllerTubeLalStation.PressureG21_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureG21_Released(), com.gluonapplication.ControllerTubeLalStation.PressureG22_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureG22_Released(), com.gluonapplication.ControllerTubeLalStation.PressureG31_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureG31_Released(), com.gluonapplication.ControllerTubeLalStation.PressureGa1_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureGa1_Released(), com.gluonapplication.ControllerTubeLalStation.PressureGa2_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureGa2_Released(), com.gluonapplication.ControllerTubeLalStation.PressureGa3_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureGa3_Released(), com.gluonapplication.ControllerTubeLalStation.PressureGa4_Pressed(), com.gluonapplication.ControllerTubeLalStation.PressureGa4_Released(), com.gluonapplication.ControllerTubeLalStation.SpeedP21_Pressed(), com.gluonapplication.ControllerTubeLalStation.SpeedP21_Released(), com.gluonapplication.ControllerTubeLalStation.V11_Pressed(), com.gluonapplication.ControllerTubeLalStation.V11_Released(), com.gluonapplication.ControllerTubeLalStation.V21_Pressed(), com.gluonapplication.ControllerTubeLalStation.V21_Released(), com.gluonapplication.ControllerTubeLalStation.V22_Pressed(), com.gluonapplication.ControllerTubeLalStation.V22_Released(), com.gluonapplication.ControllerTubeLalStation.V23_Pressed(), com.gluonapplication.ControllerTubeLalStation.V23_Released(), com.gluonapplication.ControllerTubeLalStation.V25_Pressed(), com.gluonapplication.ControllerTubeLalStation.V25_Released(), com.gluonapplication.ControllerTubeLalStation.V31_Pressed(), com.gluonapplication.ControllerTubeLalStation.V31_Released(), com.gluonapplication.ControllerTubeLalStation.V32_Pressed(), com.gluonapplication.ControllerTubeLalStation.V32_Released(), com.gluonapplication.ControllerTubeLalStation.V91_Pressed(), com.gluonapplication.ControllerTubeLalStation.V91_released(), com.gluonapplication.ControllerTubeLalStation.Va1_Pressed(), com.gluonapplication.ControllerTubeLalStation.Va1_Released(), com.gluonapplication.ControllerTubeLalStation.Va2_Pressed(), and com.gluonapplication.ControllerTubeLalStation.Va2_Released().
The documentation for this class was generated from the following file:
ControllerTubeLalStation.java