VACUUM Supervisor: com.gluonapplication.ControlCommand Class Reference
com.gluonapplication.ControlCommand Class Reference
Public Member Functions
void getMastership (String query)
void setAskedValue (String _askedValue)
String setCommand (String msgServer, String msgType, String msgStation, String msgChannel, String value, int delay, boolean askMastership, String query, boolean showAlert)
void run ()
Static Public Member Functions
static ControlCommand getInstance ()
Protected Member Functions
URLConnection getServerConnection (String url) throws MalformedURLException, IOException
A connection method called every time a connection to the servlet is needed.
Detailed Description
Definition at line 15 of file ControlCommand.java.
Member Function Documentation
getInstance()
static ControlCommand com.gluonapplication.ControlCommand.getInstance () static
Definition at line 46 of file ControlCommand.java.
getMastership()
void com.gluonapplication.ControlCommand.getMastership (String query)
Definition at line 74 of file ControlCommand.java.
References com.gluonapplication.ControlCommand.getServerConnection().
Referenced by com.gluonapplication.DialogAskMastership.DialogAskMastership(), com.gluonapplication.DialogOverTakeMastership.DialogOverTakeMastership(), and com.gluonapplication.ControlCommand.setCommand().
getServerConnection()
URLConnection com.gluonapplication.ControlCommand.getServerConnection (String url) throws MalformedURLException, IOException protected
The servlet path points to "jchv" which contains the main servlet for channel visualization.
Definition at line 61 of file ControlCommand.java.
Referenced by com.gluonapplication.ControlCommand.getMastership(), and com.gluonapplication.ControlCommand.run().
run()
void com.gluonapplication.ControlCommand.run ()
Definition at line 209 of file ControlCommand.java.
References com.gluonapplication.ControlCommand.getServerConnection().
setAskedValue()
void com.gluonapplication.ControlCommand.setAskedValue (String _askedValue)
Definition at line 121 of file ControlCommand.java.
Referenced by com.gluonapplication.DialogAskValue.DialogAskValue().
setCommand()
String com.gluonapplication.ControlCommand.setCommand (String msgServer, String msgType, String msgStation, String msgChannel, String value, int delay, boolean askMastership, String query, boolean showAlert)
Definition at line 125 of file ControlCommand.java.
References com.gluonapplication.ControlCommand.getMastership().
Referenced by com.gluonapplication.ControllerMiniTowerSqzActions.ByPassG22_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.ByPassGP_Clicked(), com.gluonapplication.ControllerLinkActions.ByPassRemote_Clicked(), com.gluonapplication.ControllerValve.CLOSE_Clicked(), com.gluonapplication.ControllerITRGauge.DEGASOFF_Clicked(), com.gluonapplication.ControllerXGSGauge.DEGASOFF_Clicked(), com.gluonapplication.ControllerITRGauge.DEGASON_Clicked(), com.gluonapplication.ControllerXGSGauge.DEGASON_Clicked(), com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Clicked(), com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Clicked(), com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Clicked(), com.gluonapplication.ControllerITRGauge.EMULTOFF_Clicked(), com.gluonapplication.ControllerITRGauge.EMULTON_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.EmultOnOff_Clicked(), com.gluonapplication.ControllerLinkActions.FanOnOff_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.FanOnOff_Clicked(), com.gluonapplication.ControllerTubeMCActions.FanOnOff_Clicked(), com.gluonapplication.ControllerTubeSqzActions.FanOnOff_Clicked(), com.gluonapplication.ControllerLinkActions.FanSpeed_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.FanSpeed_Clicked(), com.gluonapplication.ControllerTubeMCActions.FanSpeed_Clicked(), com.gluonapplication.ControllerTubeSqzActions.FanSpeed_Clicked(), com.gluonapplication.ControllerXGSGauge.FIL1OFF_Clicked(), com.gluonapplication.ControllerXGSGauge.FIL1ON_Clicked(), com.gluonapplication.ControllerXGSGauge.FIL2OFF_Clicked(), com.gluonapplication.ControllerXGSGauge.FIL2ON_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.Filament_Clicked(), com.gluonapplication.ControllerTitane.FilamentUsed_Clicked(), com.gluonapplication.ControllerIonic.FirstStepCurrent_Clicked(), com.gluonapplication.ControllerIonic.FirstStepVoltage_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Clicked(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Clicked(), com.gluonapplication.ControllerIonic.MaxCurrent_Clicked(), com.gluonapplication.ControllerIonic.MaxPower_Clicked(), com.gluonapplication.ControllerIonic.MaxVoltage_Clicked(), com.gluonapplication.ControllerDry.OFF_Clicked(), com.gluonapplication.ControllerIonic.OFF_Clicked(), com.gluonapplication.ControllerMaxiGauge.OFF_Clicked(), com.gluonapplication.ControllerTitane.OFF_Clicked(), com.gluonapplication.ControllerTurbo.OFF_Clicked(), com.gluonapplication.ControllerTurboT.OFF_Clicked(), com.gluonapplication.ControllerDry.ON_Clicked(), com.gluonapplication.ControllerIonic.ON_Clicked(), com.gluonapplication.ControllerMaxiGauge.ON_Clicked(), com.gluonapplication.ControllerTitane.ON_Clicked(), com.gluonapplication.ControllerTurbo.ON_Clicked(), com.gluonapplication.ControllerTurboT.ON_Clicked(), com.gluonapplication.ControllerValve.OPEN_Clicked(), com.gluonapplication.ControllerIonic.OperatingMode_Clicked(), com.gluonapplication.ControllerMobileVentingActions.OpExecute_Clicked(), com.gluonapplication.ControllerMobileVentingActions.OpStop_Clicked(), com.gluonapplication.ControllerCryoActions.PIDdisable_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Clicked(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Clicked(), com.gluonapplication.ControllerIonic.ProtectCurrent_Clicked(), com.gluonapplication.ControllerCryoLinkActions.RefillMode_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Clicked(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Clicked(), com.gluonapplication.ControllerCryoActions.Reset_Clicked(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Clicked(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Clicked(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Clicked(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Clicked(), com.gluonapplication.ControllerSupervisorActions.SafeCentral_Clicked(), com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Clicked(), com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Clicked(), com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Clicked(), com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Clicked(), com.gluonapplication.ControllerIonic.SecondStepCurrent_Clicked(), com.gluonapplication.ControllerIonic.SecondStepVoltage_Clicked(), com.gluonapplication.ControllerCryoActions.StartStop_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.StartStop_Clicked(), com.gluonapplication.ControllerTurbo.STYOFF_Clicked(), com.gluonapplication.ControllerTurboT.STYOFF_Clicked(), com.gluonapplication.ControllerTurbo.STYON_Clicked(), com.gluonapplication.ControllerTurboT.STYON_Clicked(), com.gluonapplication.ControllerTitane.SublimationCurrent_Clicked(), com.gluonapplication.ControllerTitane.SublimationPeriod_Clicked(), com.gluonapplication.ControllerTitane.SublimationTime_Clicked(), and com.gluonapplication.ControllerIonic.VoltageMode_Clicked().
The documentation for this class was generated from the following file:
ControlCommand.java