VACUUM Supervisor: com.gluonapplication.ControllerTowerBenchStation Class Reference
com.gluonapplication.ControllerTowerBenchStation Class Reference
Package Functions
void SpeedP51_Clicked (MouseEvent event)
void SpeedP51_Pressed (MouseEvent event)
void SpeedP51_Released (MouseEvent event)
void G41_Clicked (MouseEvent event)
void G41_Pressed (MouseEvent event)
void G41_Released (MouseEvent event)
void G51_Clicked (MouseEvent event)
void G51_Pressed (MouseEvent event)
void G51_Released (MouseEvent event)
void G61_Clicked (MouseEvent event)
void G61_Pressed (MouseEvent event)
void G61_Released (MouseEvent event)
void Gc1_Clicked (MouseEvent event)
void Gc1_Pressed (MouseEvent event)
void Gc1_Released (MouseEvent event)
void Gc2_Clicked (MouseEvent event)
void Gc2_Pressed (MouseEvent event)
void Gc2_Released (MouseEvent event)
void Gc3_Clicked (MouseEvent event)
void Gc3_Pressed (MouseEvent event)
void Gc3_Released (MouseEvent event)
void Gc4_Clicked (MouseEvent event)
void Gc4_Pressed (MouseEvent event)
void Gc4_Released (MouseEvent event)
void P41_Clicked (MouseEvent event)
void P41_Pressed (MouseEvent event)
void P41_Released (MouseEvent event)
void P51_Clicked (MouseEvent event)
void P51_Pressed (MouseEvent event)
void P51_Released (MouseEvent event)
void P61_Clicked (MouseEvent event)
void P61_Pressed (MouseEvent event)
void P61_Released (MouseEvent event)
void PressureG41_Clicked (MouseEvent event)
void PressureG41_Pressed (MouseEvent event)
void PressureG41_Released (MouseEvent event)
void PressureG51_Clicked (MouseEvent event)
void PressureG51_Pressed (MouseEvent event)
void PressureG51_Released (MouseEvent event)
void PressureG61_Clicked (MouseEvent event)
void PressureG61_Pressed (MouseEvent event)
void PressureG61_Released (MouseEvent event)
void PressureGc1_Clicked (MouseEvent event)
void PressureGc1_Pressed (MouseEvent event)
void PressureGc1_Released (MouseEvent event)
void PressureGc2_Clicked (MouseEvent event)
void PressureGc2_Pressed (MouseEvent event)
void PressureGc2_Released (MouseEvent event)
void PressureGc3_Clicked (MouseEvent event)
void PressureGc3_Pressed (MouseEvent event)
void PressureGc3_Released (MouseEvent event)
void V41_Clicked (MouseEvent event)
void V41_Pressed (MouseEvent event)
void V41_Released (MouseEvent event)
void V42_Clicked (MouseEvent event)
void V42_Pressed (MouseEvent event)
void V42_Released (MouseEvent event)
void V51_Clicked (MouseEvent event)
void V51_Pressed (MouseEvent event)
void V51_Released (MouseEvent event)
void V52_Clicked (MouseEvent event)
void V52_Pressed (MouseEvent event)
void V52_Released (MouseEvent event)
void V53_Clicked (MouseEvent event)
void V53_Pressed (MouseEvent event)
void V53_Released (MouseEvent event)
void V54_Clicked (MouseEvent event)
void V54_Pressed (MouseEvent event)
void V54_Released (MouseEvent event)
void V91_Clicked (MouseEvent event)
void V91_Pressed (MouseEvent event)
void V91_Released (MouseEvent event)
void V92_Clicked (MouseEvent event)
void V92_Pressed (MouseEvent event)
void V92_Released (MouseEvent event)
void Vc1_Clicked (MouseEvent event)
void Vc1_Pressed (MouseEvent event)
void Vc1_Released (MouseEvent event)
void Vc2_Clicked (MouseEvent event)
void Vc2_Pressed (MouseEvent event)
void Vc2_Released (MouseEvent event)
void RemotePumping_Clicked (MouseEvent event)
void RemotePumping_Pressed (MouseEvent event)
void RemotePumping_Released (MouseEvent event)
void CreateAndShowRGALayer (String name)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 13 of file ControllerTowerBenchStation.java.
Member Function Documentation
CreateAndShowRGALayer()
void com.gluonapplication.ControllerTowerBenchStation.CreateAndShowRGALayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 628 of file ControllerTowerBenchStation.java.
Referenced by com.gluonapplication.ControllerTowerBenchStation.Gc4_Clicked().
G41_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.G41_Clicked (MouseEvent event) package
Definition at line 188 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G41_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.G41_Pressed (MouseEvent event) package
Definition at line 193 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
G41_Released()
void com.gluonapplication.ControllerTowerBenchStation.G41_Released (MouseEvent event) package
Definition at line 199 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
G51_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.G51_Clicked (MouseEvent event) package
Definition at line 204 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G51_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.G51_Pressed (MouseEvent event) package
Definition at line 209 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
G51_Released()
void com.gluonapplication.ControllerTowerBenchStation.G51_Released (MouseEvent event) package
Definition at line 215 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
G61_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.G61_Clicked (MouseEvent event) package
Definition at line 220 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G61_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.G61_Pressed (MouseEvent event) package
Definition at line 225 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
G61_Released()
void com.gluonapplication.ControllerTowerBenchStation.G61_Released (MouseEvent event) package
Definition at line 231 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Gc1_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Gc1_Clicked (MouseEvent event) package
Definition at line 236 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Gc1_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Gc1_Pressed (MouseEvent event) package
Definition at line 241 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Gc1_Released()
void com.gluonapplication.ControllerTowerBenchStation.Gc1_Released (MouseEvent event) package
Definition at line 247 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Gc2_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Gc2_Clicked (MouseEvent event) package
Definition at line 252 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Gc2_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Gc2_Pressed (MouseEvent event) package
Definition at line 257 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Gc2_Released()
void com.gluonapplication.ControllerTowerBenchStation.Gc2_Released (MouseEvent event) package
Definition at line 263 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Gc3_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Gc3_Clicked (MouseEvent event) package
Definition at line 268 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
Gc3_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Gc3_Pressed (MouseEvent event) package
Definition at line 273 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Gc3_Released()
void com.gluonapplication.ControllerTowerBenchStation.Gc3_Released (MouseEvent event) package
Definition at line 279 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Gc4_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Gc4_Clicked (MouseEvent event) package
Definition at line 284 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.CreateAndShowRGALayer().
Gc4_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Gc4_Pressed (MouseEvent event) package
Definition at line 289 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Gc4_Released()
void com.gluonapplication.ControllerTowerBenchStation.Gc4_Released (MouseEvent event) package
Definition at line 295 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
P41_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.P41_Clicked (MouseEvent event) package
Definition at line 300 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P41_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.P41_Pressed (MouseEvent event) package
Definition at line 305 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
P41_Released()
void com.gluonapplication.ControllerTowerBenchStation.P41_Released (MouseEvent event) package
Definition at line 311 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
P51_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.P51_Clicked (MouseEvent event) package
Definition at line 316 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowTurboLayer().
P51_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.P51_Pressed (MouseEvent event) package
Definition at line 321 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
P51_Released()
void com.gluonapplication.ControllerTowerBenchStation.P51_Released (MouseEvent event) package
Definition at line 327 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
P61_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.P61_Clicked (MouseEvent event) package
Definition at line 332 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P61_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.P61_Pressed (MouseEvent event) package
Definition at line 337 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
P61_Released()
void com.gluonapplication.ControllerTowerBenchStation.P61_Released (MouseEvent event) package
Definition at line 343 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureG41_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureG41_Clicked (MouseEvent event) package
Definition at line 348 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG41_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureG41_Pressed (MouseEvent event) package
Definition at line 353 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureG41_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureG41_Released (MouseEvent event) package
Definition at line 359 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureG51_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureG51_Clicked (MouseEvent event) package
Definition at line 364 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG51_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureG51_Pressed (MouseEvent event) package
Definition at line 369 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureG51_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureG51_Released (MouseEvent event) package
Definition at line 375 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureG61_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureG61_Clicked (MouseEvent event) package
Definition at line 380 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG61_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureG61_Pressed (MouseEvent event) package
Definition at line 385 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureG61_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureG61_Released (MouseEvent event) package
Definition at line 391 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc1_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc1_Clicked (MouseEvent event) package
Definition at line 396 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGc1_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc1_Pressed (MouseEvent event) package
Definition at line 401 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc1_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc1_Released (MouseEvent event) package
Definition at line 407 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc2_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc2_Clicked (MouseEvent event) package
Definition at line 412 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGc2_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc2_Pressed (MouseEvent event) package
Definition at line 417 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc2_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc2_Released (MouseEvent event) package
Definition at line 423 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc3_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc3_Clicked (MouseEvent event) package
Definition at line 428 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureGc3_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc3_Pressed (MouseEvent event) package
Definition at line 433 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
PressureGc3_Released()
void com.gluonapplication.ControllerTowerBenchStation.PressureGc3_Released (MouseEvent event) package
Definition at line 439 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
RemotePumping_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.RemotePumping_Clicked (MouseEvent event) package
Definition at line 604 of file ControllerTowerBenchStation.java.
References com.gluonapplication.Main.remotePumps.
RemotePumping_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.RemotePumping_Pressed (MouseEvent event) package
Definition at line 618 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
RemotePumping_Released()
void com.gluonapplication.ControllerTowerBenchStation.RemotePumping_Released (MouseEvent event) package
Definition at line 624 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
SpeedP51_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.SpeedP51_Clicked (MouseEvent event) package
Definition at line 172 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
SpeedP51_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.SpeedP51_Pressed (MouseEvent event) package
Definition at line 177 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
SpeedP51_Released()
void com.gluonapplication.ControllerTowerBenchStation.SpeedP51_Released (MouseEvent event) package
Definition at line 183 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V41_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V41_Clicked (MouseEvent event) package
Definition at line 444 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V41_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V41_Pressed (MouseEvent event) package
Definition at line 449 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V41_Released()
void com.gluonapplication.ControllerTowerBenchStation.V41_Released (MouseEvent event) package
Definition at line 455 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V42_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V42_Clicked (MouseEvent event) package
Definition at line 460 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V42_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V42_Pressed (MouseEvent event) package
Definition at line 465 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V42_Released()
void com.gluonapplication.ControllerTowerBenchStation.V42_Released (MouseEvent event) package
Definition at line 471 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V51_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V51_Clicked (MouseEvent event) package
Definition at line 476 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V51_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V51_Pressed (MouseEvent event) package
Definition at line 481 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V51_Released()
void com.gluonapplication.ControllerTowerBenchStation.V51_Released (MouseEvent event) package
Definition at line 487 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V52_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V52_Clicked (MouseEvent event) package
Definition at line 492 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V52_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V52_Pressed (MouseEvent event) package
Definition at line 497 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V52_Released()
void com.gluonapplication.ControllerTowerBenchStation.V52_Released (MouseEvent event) package
Definition at line 503 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V53_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V53_Clicked (MouseEvent event) package
Definition at line 508 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V53_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V53_Pressed (MouseEvent event) package
Definition at line 513 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V53_Released()
void com.gluonapplication.ControllerTowerBenchStation.V53_Released (MouseEvent event) package
Definition at line 519 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V54_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V54_Clicked (MouseEvent event) package
Definition at line 524 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V54_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V54_Pressed (MouseEvent event) package
Definition at line 529 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V54_Released()
void com.gluonapplication.ControllerTowerBenchStation.V54_Released (MouseEvent event) package
Definition at line 535 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V91_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V91_Clicked (MouseEvent event) package
Definition at line 540 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V91_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V91_Pressed (MouseEvent event) package
Definition at line 545 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V91_Released()
void com.gluonapplication.ControllerTowerBenchStation.V91_Released (MouseEvent event) package
Definition at line 551 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
V92_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.V92_Clicked (MouseEvent event) package
Definition at line 556 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V92_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.V92_Pressed (MouseEvent event) package
Definition at line 561 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
V92_Released()
void com.gluonapplication.ControllerTowerBenchStation.V92_Released (MouseEvent event) package
Definition at line 567 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Vc1_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Vc1_Clicked (MouseEvent event) package
Definition at line 572 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Vc1_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Vc1_Pressed (MouseEvent event) package
Definition at line 577 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Vc1_Released()
void com.gluonapplication.ControllerTowerBenchStation.Vc1_Released (MouseEvent event) package
Definition at line 583 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Vc2_Clicked()
void com.gluonapplication.ControllerTowerBenchStation.Vc2_Clicked (MouseEvent event) package
Definition at line 588 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
Vc2_Pressed()
void com.gluonapplication.ControllerTowerBenchStation.Vc2_Pressed (MouseEvent event) package
Definition at line 593 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTowerBenchStation.style.
Vc2_Released()
void com.gluonapplication.ControllerTowerBenchStation.Vc2_Released (MouseEvent event) package
Definition at line 599 of file ControllerTowerBenchStation.java.
References com.gluonapplication.ControllerTowerBenchStation.style.
Member Data Documentation
style
String com.gluonapplication.ControllerTowerBenchStation.style = "" package
Definition at line 168 of file ControllerTowerBenchStation.java.
Referenced by com.gluonapplication.ControllerTowerBenchStation.G41_Pressed(), com.gluonapplication.ControllerTowerBenchStation.G41_Released(), com.gluonapplication.ControllerTowerBenchStation.G51_Pressed(), com.gluonapplication.ControllerTowerBenchStation.G51_Released(), com.gluonapplication.ControllerTowerBenchStation.G61_Pressed(), com.gluonapplication.ControllerTowerBenchStation.G61_Released(), com.gluonapplication.ControllerTowerBenchStation.Gc1_Pressed(), com.gluonapplication.ControllerTowerBenchStation.Gc1_Released(), com.gluonapplication.ControllerTowerBenchStation.Gc2_Pressed(), com.gluonapplication.ControllerTowerBenchStation.Gc2_Released(), com.gluonapplication.ControllerTowerBenchStation.Gc3_Pressed(), com.gluonapplication.ControllerTowerBenchStation.Gc3_Released(), com.gluonapplication.ControllerTowerBenchStation.Gc4_Pressed(), com.gluonapplication.ControllerTowerBenchStation.Gc4_Released(), com.gluonapplication.ControllerTowerBenchStation.P41_Pressed(), com.gluonapplication.ControllerTowerBenchStation.P41_Released(), com.gluonapplication.ControllerTowerBenchStation.P51_Pressed(), com.gluonapplication.ControllerTowerBenchStation.P51_Released(), com.gluonapplication.ControllerTowerBenchStation.P61_Pressed(), com.gluonapplication.ControllerTowerBenchStation.P61_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureG41_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureG41_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureG51_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureG51_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureG61_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureG61_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureGc1_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureGc1_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureGc2_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureGc2_Released(), com.gluonapplication.ControllerTowerBenchStation.PressureGc3_Pressed(), com.gluonapplication.ControllerTowerBenchStation.PressureGc3_Released(), com.gluonapplication.ControllerTowerBenchStation.RemotePumping_Pressed(), com.gluonapplication.ControllerTowerBenchStation.RemotePumping_Released(), com.gluonapplication.ControllerTowerBenchStation.SpeedP51_Pressed(), com.gluonapplication.ControllerTowerBenchStation.SpeedP51_Released(), com.gluonapplication.ControllerTowerBenchStation.V41_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V41_Released(), com.gluonapplication.ControllerTowerBenchStation.V42_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V42_Released(), com.gluonapplication.ControllerTowerBenchStation.V51_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V51_Released(), com.gluonapplication.ControllerTowerBenchStation.V52_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V52_Released(), com.gluonapplication.ControllerTowerBenchStation.V53_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V53_Released(), com.gluonapplication.ControllerTowerBenchStation.V54_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V54_Released(), com.gluonapplication.ControllerTowerBenchStation.V91_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V91_Released(), com.gluonapplication.ControllerTowerBenchStation.V92_Pressed(), com.gluonapplication.ControllerTowerBenchStation.V92_Released(), com.gluonapplication.ControllerTowerBenchStation.Vc1_Pressed(), com.gluonapplication.ControllerTowerBenchStation.Vc1_Released(), com.gluonapplication.ControllerTowerBenchStation.Vc2_Pressed(), and com.gluonapplication.ControllerTowerBenchStation.Vc2_Released().
The documentation for this class was generated from the following file:
ControllerTowerBenchStation.java