VACUUM Supervisor: com.gluonapplication.ControllerMiniTowerSqzActions Class Reference
com.gluonapplication.ControllerMiniTowerSqzActions Class Reference
Public Member Functions
void initialize ()
Package Functions
void FanOnOff_Clicked (MouseEvent event)
void FanOnOff_Pressed (MouseEvent event)
void FanOnOff_Released (MouseEvent event)
void FanSpeed_Clicked (MouseEvent event)
void FanSpeed_Pressed (MouseEvent event)
void FanSpeed_Released (MouseEvent event)
void ByPassG22_Clicked (MouseEvent event)
void ByPassG22_Pressed (MouseEvent event)
void ByPassG22_Released (MouseEvent event)
void ByPassGP_Clicked (MouseEvent event)
void ByPassGP_Pressed (MouseEvent event)
void ByPassGP_Released (MouseEvent event)
void EmultOnOff_Clicked (MouseEvent event)
void EmultOnOff_Pressed (MouseEvent event)
void EmultOnOff_Released (MouseEvent event)
void StartStop_Clicked (MouseEvent event)
void StartStop_Pressed (MouseEvent event)
void StartStop_Released (MouseEvent event)
void Filament_Clicked (MouseEvent event)
void Filament_Pressed (MouseEvent event)
void Filament_Released (MouseEvent event)
Package Attributes
String name = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 8 of file ControllerMiniTowerSqzActions.java.
Member Function Documentation
ByPassG22_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassG22_Clicked (MouseEvent event) package
Definition at line 90 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
ByPassG22_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassG22_Pressed (MouseEvent event) package
Definition at line 100 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
ByPassG22_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassG22_Released (MouseEvent event) package
Definition at line 106 of file ControllerMiniTowerSqzActions.java.
ByPassGP_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassGP_Clicked (MouseEvent event) package
Definition at line 111 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
ByPassGP_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassGP_Pressed (MouseEvent event) package
Definition at line 121 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
ByPassGP_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.ByPassGP_Released (MouseEvent event) package
Definition at line 127 of file ControllerMiniTowerSqzActions.java.
EmultOnOff_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.EmultOnOff_Clicked (MouseEvent event) package
Definition at line 132 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
EmultOnOff_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.EmultOnOff_Pressed (MouseEvent event) package
Definition at line 142 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
EmultOnOff_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.EmultOnOff_Released (MouseEvent event) package
Definition at line 148 of file ControllerMiniTowerSqzActions.java.
FanOnOff_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanOnOff_Clicked (MouseEvent event) package
Definition at line 48 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
FanOnOff_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanOnOff_Pressed (MouseEvent event) package
Definition at line 58 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
FanOnOff_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanOnOff_Released (MouseEvent event) package
Definition at line 64 of file ControllerMiniTowerSqzActions.java.
FanSpeed_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanSpeed_Clicked (MouseEvent event) package
Definition at line 69 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
FanSpeed_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanSpeed_Pressed (MouseEvent event) package
Definition at line 79 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
FanSpeed_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.FanSpeed_Released (MouseEvent event) package
Definition at line 85 of file ControllerMiniTowerSqzActions.java.
Filament_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.Filament_Clicked (MouseEvent event) package
Definition at line 174 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
Filament_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.Filament_Pressed (MouseEvent event) package
Definition at line 180 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
Filament_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.Filament_Released (MouseEvent event) package
Definition at line 186 of file ControllerMiniTowerSqzActions.java.
initialize()
void com.gluonapplication.ControllerMiniTowerSqzActions.initialize ()
Definition at line 42 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ViewData.name.
StartStop_Clicked()
void com.gluonapplication.ControllerMiniTowerSqzActions.StartStop_Clicked (MouseEvent event) package
Definition at line 153 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.MINITOWERSQZACTIONS_COMMAND_CHANNELS, com.gluonapplication.ControllerMiniTowerSqzActions.name, and com.gluonapplication.ControlCommand.setCommand().
StartStop_Pressed()
void com.gluonapplication.ControllerMiniTowerSqzActions.StartStop_Pressed (MouseEvent event) package
Definition at line 163 of file ControllerMiniTowerSqzActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED.
StartStop_Released()
void com.gluonapplication.ControllerMiniTowerSqzActions.StartStop_Released (MouseEvent event) package
Definition at line 169 of file ControllerMiniTowerSqzActions.java.
Member Data Documentation
name
String com.gluonapplication.ControllerMiniTowerSqzActions.name = "" package
Definition at line 37 of file ControllerMiniTowerSqzActions.java.
Referenced by com.gluonapplication.ControllerMiniTowerSqzActions.ByPassG22_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.ByPassGP_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.EmultOnOff_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.FanOnOff_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.FanSpeed_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.Filament_Clicked(), com.gluonapplication.ControllerMiniTowerSqzActions.initialize(), and com.gluonapplication.ControllerMiniTowerSqzActions.StartStop_Clicked().
The documentation for this class was generated from the following file:
ControllerMiniTowerSqzActions.java