VACUUM Supervisor: com.gluonapplication.ControllerGlobalFlagsPlus Class Reference
com.gluonapplication.ControllerGlobalFlagsPlus Class Reference
Package Functions
void ResetNE_Clicked (MouseEvent event)
void ResetNE_Pressed (MouseEvent event)
void ResetNE_Released (MouseEvent event)
void ResetNI_Clicked (MouseEvent event)
void ResetNI_Pressed (MouseEvent event)
void ResetNI_Released (MouseEvent event)
void ResetWE_Clicked (MouseEvent event)
void ResetWE_Pressed (MouseEvent event)
void ResetWE_Released (MouseEvent event)
void ResetWI_Clicked (MouseEvent event)
void ResetWI_Pressed (MouseEvent event)
void ResetWI_Released (MouseEvent event)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 9 of file ControllerGlobalFlagsPlus.java.
Member Function Documentation
ResetNE_Clicked()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Clicked (MouseEvent event) package
Definition at line 157 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlCommand.setCommand().
ResetNE_Pressed()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Pressed (MouseEvent event) package
Definition at line 162 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetNE_Released()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Released (MouseEvent event) package
Definition at line 168 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetNI_Clicked()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Clicked (MouseEvent event) package
Definition at line 173 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlCommand.setCommand().
ResetNI_Pressed()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Pressed (MouseEvent event) package
Definition at line 178 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetNI_Released()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Released (MouseEvent event) package
Definition at line 184 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetWE_Clicked()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Clicked (MouseEvent event) package
Definition at line 189 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlCommand.setCommand().
ResetWE_Pressed()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Pressed (MouseEvent event) package
Definition at line 194 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetWE_Released()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Released (MouseEvent event) package
Definition at line 200 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetWI_Clicked()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Clicked (MouseEvent event) package
Definition at line 205 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlCommand.setCommand().
ResetWI_Pressed()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Pressed (MouseEvent event) package
Definition at line 210 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerGlobalFlagsPlus.style.
ResetWI_Released()
void com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Released (MouseEvent event) package
Definition at line 216 of file ControllerGlobalFlagsPlus.java.
References com.gluonapplication.ControllerGlobalFlagsPlus.style.
Member Data Documentation
style
String com.gluonapplication.ControllerGlobalFlagsPlus.style = "" package
Definition at line 152 of file ControllerGlobalFlagsPlus.java.
Referenced by com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Pressed(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetNE_Released(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Pressed(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetNI_Released(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Pressed(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetWE_Released(), com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Pressed(), and com.gluonapplication.ControllerGlobalFlagsPlus.ResetWI_Released().
The documentation for this class was generated from the following file:
ControllerGlobalFlagsPlus.java