VACUUM Supervisor: com.gluonapplication.ControllerSupervisorActions Class Reference
com.gluonapplication.ControllerSupervisorActions Class Reference
Package Functions
void EmergencyCB_Clicked (MouseEvent event)
void EmergencyCB_Pressed (MouseEvent event)
void EmergencyCB_Released (MouseEvent event)
void EmergencyNE_Clicked (MouseEvent event)
void EmergencyNE_Pressed (MouseEvent event)
void EmergencyNE_Released (MouseEvent event)
void EmergencyWE_Clicked (MouseEvent event)
void EmergencyWE_Pressed (MouseEvent event)
void EmergencyWE_Released (MouseEvent event)
void LN2TankNI_Clicked (MouseEvent event)
void LN2TankNI_Pressed (MouseEvent event)
void LN2TankNI_Released (MouseEvent event)
void LN2TankNE_Clicked (MouseEvent event)
void LN2TankNE_Pressed (MouseEvent event)
void LN2TankNE_Released (MouseEvent event)
void LN2TankWE_Clicked (MouseEvent event)
void LN2TankWE_Pressed (MouseEvent event)
void LN2TankWE_Released (MouseEvent event)
void LN2TankWI_Clicked (MouseEvent event)
void LN2TankWI_Pressed (MouseEvent event)
void LN2TankWI_Released (MouseEvent event)
void LN2TankNI_2_Clicked (MouseEvent event)
void LN2TankNI_2_Pressed (MouseEvent event)
void LN2TankNI_2_Released (MouseEvent event)
void LN2TankWI_2_Clicked (MouseEvent event)
void LN2TankWI_2_Pressed (MouseEvent event)
void LN2TankWI_2_Released (MouseEvent event)
void LN2TankNE_2_Clicked (MouseEvent event)
void LN2TankNE_2_Pressed (MouseEvent event)
void LN2TankNE_2_Released (MouseEvent event)
void LN2TankWE_2_Clicked (MouseEvent event)
void LN2TankWE_2_Pressed (MouseEvent event)
void LN2TankWE_2_Released (MouseEvent event)
void PrimaryPumpingBS_Clicked (MouseEvent event)
void PrimaryPumpingBS_Pressed (MouseEvent event)
void PrimaryPumpingBS_Released (MouseEvent event)
void PrimaryPumpingDET_Clicked (MouseEvent event)
void PrimaryPumpingDET_Pressed (MouseEvent event)
void PrimaryPumpingDET_Released (MouseEvent event)
void PrimaryPumpingIB_Clicked (MouseEvent event)
void PrimaryPumpingIB_Pressed (MouseEvent event)
void PrimaryPumpingIB_Released (MouseEvent event)
void PrimaryPumpingMC_Clicked (MouseEvent event)
void PrimaryPumpingMC_Pressed (MouseEvent event)
void PrimaryPumpingMC_Released (MouseEvent event)
void PrimaryPumpingNE_Clicked (MouseEvent event)
void PrimaryPumpingNE_Pressed (MouseEvent event)
void PrimaryPumpingNE_Released (MouseEvent event)
void PrimaryPumpingNI_Clicked (MouseEvent event)
void PrimaryPumpingNI_Pressed (MouseEvent event)
void PrimaryPumpingNI_Released (MouseEvent event)
void PrimaryPumpingPR_Clicked (MouseEvent event)
void PrimaryPumpingPR_Pressed (MouseEvent event)
void PrimaryPumpingPR_Released (MouseEvent event)
void PrimaryPumpingSR_Clicked (MouseEvent event)
void PrimaryPumpingSR_Pressed (MouseEvent event)
void PrimaryPumpingSR_Released (MouseEvent event)
void PrimaryPumpingWE_Clicked (MouseEvent event)
void PrimaryPumpingWE_Pressed (MouseEvent event)
void PrimaryPumpingWE_Released (MouseEvent event)
void PrimaryPumpingWI_Clicked (MouseEvent event)
void PrimaryPumpingWI_Pressed (MouseEvent event)
void PrimaryPumpingWI_Released (MouseEvent event)
void RemotePumpingBS_Clicked (MouseEvent event)
void RemotePumpingBS_Pressed (MouseEvent event)
void RemotePumpingBS_Released (MouseEvent event)
void RemotePumpingDET_Clicked (MouseEvent event)
void RemotePumpingDET_Pressed (MouseEvent event)
void RemotePumpingDET_Released (MouseEvent event)
void RemotePumpingIB_Clicked (MouseEvent event)
void RemotePumpingIB_Pressed (MouseEvent event)
void RemotePumpingIB_Released (MouseEvent event)
void RemotePumpingNI_Clicked (MouseEvent event)
void RemotePumpingNI_Pressed (MouseEvent event)
void RemotePumpingNI_Released (MouseEvent event)
void RemotePumpingPR_Clicked (MouseEvent event)
void RemotePumpingPR_Pressed (MouseEvent event)
void RemotePumpingPR_Released (MouseEvent event)
void RemotePumpingSR_Clicked (MouseEvent event)
void RemotePumpingSR_Pressed (MouseEvent event)
void RemotePumpingSR_Released (MouseEvent event)
void RemotePumpingWI_Clicked (MouseEvent event)
void RemotePumpingWI_Pressed (MouseEvent event)
void RemotePumpingWI_Released (MouseEvent event)
void SafeCentral_Clicked (MouseEvent event)
void SafeCentral_Pressed (MouseEvent event)
void SafeCentral_Released (MouseEvent event)
void SafeNorthArm_Clicked (MouseEvent event)
void SafeNorthArm_Pressed (MouseEvent event)
void SafeNorthArm_Released (MouseEvent event)
void SafeNorthEnd_Clicked (MouseEvent event)
void SafeNorthEnd_Pressed (MouseEvent event)
void SafeNorthEnd_Released (MouseEvent event)
void SafeWestArm_Clicked (MouseEvent event)
void SafeWestArm_Pressed (MouseEvent event)
void SafeWestArm_Released (MouseEvent event)
void SafeWestEnd_Clicked (MouseEvent event)
void SafeWestEnd_Pressed (MouseEvent event)
void SafeWestEnd_Released (MouseEvent event)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 8 of file ControllerSupervisorActions.java.
Member Function Documentation
EmergencyCB_Clicked()
void com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Clicked (MouseEvent event) package
Definition at line 120 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
EmergencyCB_Pressed()
void com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Pressed (MouseEvent event) package
Definition at line 130 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
EmergencyCB_Released()
void com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Released (MouseEvent event) package
Definition at line 137 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
EmergencyNE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Clicked (MouseEvent event) package
Definition at line 143 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
EmergencyNE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Pressed (MouseEvent event) package
Definition at line 153 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
EmergencyNE_Released()
void com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Released (MouseEvent event) package
Definition at line 159 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
EmergencyWE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Clicked (MouseEvent event) package
Definition at line 164 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
EmergencyWE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Pressed (MouseEvent event) package
Definition at line 174 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
EmergencyWE_Released()
void com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Released (MouseEvent event) package
Definition at line 180 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNE_2_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Clicked (MouseEvent event) package
Definition at line 311 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankNE_2_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Pressed (MouseEvent event) package
Definition at line 321 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNE_2_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Released (MouseEvent event) package
Definition at line 327 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Clicked (MouseEvent event) package
Definition at line 206 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankNE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Pressed (MouseEvent event) package
Definition at line 216 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNE_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Released (MouseEvent event) package
Definition at line 222 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNI_2_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Clicked (MouseEvent event) package
Definition at line 269 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankNI_2_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Pressed (MouseEvent event) package
Definition at line 279 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNI_2_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Released (MouseEvent event) package
Definition at line 285 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Clicked (MouseEvent event) package
Definition at line 185 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankNI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Pressed (MouseEvent event) package
Definition at line 195 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankNI_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Released (MouseEvent event) package
Definition at line 201 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWE_2_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Clicked (MouseEvent event) package
Definition at line 332 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankWE_2_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Pressed (MouseEvent event) package
Definition at line 342 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWE_2_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Released (MouseEvent event) package
Definition at line 348 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Clicked (MouseEvent event) package
Definition at line 227 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankWE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Pressed (MouseEvent event) package
Definition at line 237 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWE_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Released (MouseEvent event) package
Definition at line 243 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWI_2_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Clicked (MouseEvent event) package
Definition at line 290 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankWI_2_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Pressed (MouseEvent event) package
Definition at line 300 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWI_2_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Released (MouseEvent event) package
Definition at line 306 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Clicked (MouseEvent event) package
Definition at line 248 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
LN2TankWI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Pressed (MouseEvent event) package
Definition at line 258 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
LN2TankWI_Released()
void com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Released (MouseEvent event) package
Definition at line 264 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingBS_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Clicked (MouseEvent event) package
Definition at line 352 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingBS_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Pressed (MouseEvent event) package
Definition at line 362 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingBS_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Released (MouseEvent event) package
Definition at line 368 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingDET_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Clicked (MouseEvent event) package
Definition at line 373 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingDET_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Pressed (MouseEvent event) package
Definition at line 383 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingDET_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Released (MouseEvent event) package
Definition at line 389 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingIB_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Clicked (MouseEvent event) package
Definition at line 394 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingIB_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Pressed (MouseEvent event) package
Definition at line 404 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingIB_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Released (MouseEvent event) package
Definition at line 410 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingMC_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Clicked (MouseEvent event) package
Definition at line 415 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingMC_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Pressed (MouseEvent event) package
Definition at line 425 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingMC_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Released (MouseEvent event) package
Definition at line 431 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingNE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Clicked (MouseEvent event) package
Definition at line 436 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingNE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Pressed (MouseEvent event) package
Definition at line 446 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingNE_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Released (MouseEvent event) package
Definition at line 452 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingNI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Clicked (MouseEvent event) package
Definition at line 457 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingNI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Pressed (MouseEvent event) package
Definition at line 467 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingNI_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Released (MouseEvent event) package
Definition at line 473 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingPR_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Clicked (MouseEvent event) package
Definition at line 478 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingPR_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Pressed (MouseEvent event) package
Definition at line 488 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingPR_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Released (MouseEvent event) package
Definition at line 494 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingSR_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Clicked (MouseEvent event) package
Definition at line 499 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingSR_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Pressed (MouseEvent event) package
Definition at line 509 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingSR_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Released (MouseEvent event) package
Definition at line 515 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingWE_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Clicked (MouseEvent event) package
Definition at line 520 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingWE_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Pressed (MouseEvent event) package
Definition at line 530 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingWE_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Released (MouseEvent event) package
Definition at line 536 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingWI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Clicked (MouseEvent event) package
Definition at line 541 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
PrimaryPumpingWI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Pressed (MouseEvent event) package
Definition at line 551 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
PrimaryPumpingWI_Released()
void com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Released (MouseEvent event) package
Definition at line 557 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingBS_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Clicked (MouseEvent event) package
Definition at line 562 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingBS_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Pressed (MouseEvent event) package
Definition at line 572 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingBS_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Released (MouseEvent event) package
Definition at line 578 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingDET_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Clicked (MouseEvent event) package
Definition at line 583 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingDET_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Pressed (MouseEvent event) package
Definition at line 593 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingDET_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Released (MouseEvent event) package
Definition at line 599 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingIB_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Clicked (MouseEvent event) package
Definition at line 604 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingIB_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Pressed (MouseEvent event) package
Definition at line 614 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingIB_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Released (MouseEvent event) package
Definition at line 620 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingNI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Clicked (MouseEvent event) package
Definition at line 625 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingNI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Pressed (MouseEvent event) package
Definition at line 635 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingNI_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Released (MouseEvent event) package
Definition at line 641 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingPR_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Clicked (MouseEvent event) package
Definition at line 646 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingPR_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Pressed (MouseEvent event) package
Definition at line 656 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingPR_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Released (MouseEvent event) package
Definition at line 662 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingSR_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Clicked (MouseEvent event) package
Definition at line 667 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingSR_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Pressed (MouseEvent event) package
Definition at line 677 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingSR_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Released (MouseEvent event) package
Definition at line 683 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingWI_Clicked()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Clicked (MouseEvent event) package
Definition at line 688 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
RemotePumpingWI_Pressed()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Pressed (MouseEvent event) package
Definition at line 698 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
RemotePumpingWI_Released()
void com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Released (MouseEvent event) package
Definition at line 704 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
SafeCentral_Clicked()
void com.gluonapplication.ControllerSupervisorActions.SafeCentral_Clicked (MouseEvent event) package
Definition at line 709 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
SafeCentral_Pressed()
void com.gluonapplication.ControllerSupervisorActions.SafeCentral_Pressed (MouseEvent event) package
Definition at line 719 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
SafeCentral_Released()
void com.gluonapplication.ControllerSupervisorActions.SafeCentral_Released (MouseEvent event) package
Definition at line 725 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
SafeNorthArm_Clicked()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Clicked (MouseEvent event) package
Definition at line 730 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
SafeNorthArm_Pressed()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Pressed (MouseEvent event) package
Definition at line 740 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
SafeNorthArm_Released()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Released (MouseEvent event) package
Definition at line 746 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
SafeNorthEnd_Clicked()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Clicked (MouseEvent event) package
Definition at line 751 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
SafeNorthEnd_Pressed()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Pressed (MouseEvent event) package
Definition at line 761 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
SafeNorthEnd_Released()
void com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Released (MouseEvent event) package
Definition at line 767 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
SafeWestArm_Clicked()
void com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Clicked (MouseEvent event) package
Definition at line 772 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
SafeWestArm_Pressed()
void com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Pressed (MouseEvent event) package
Definition at line 782 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
SafeWestArm_Released()
void com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Released (MouseEvent event) package
Definition at line 788 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
SafeWestEnd_Clicked()
void com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Clicked (MouseEvent event) package
Definition at line 793 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlCommand.setCommand(), and com.gluonapplication.ControlTypes.SUPERVISORACTIONS_COMMAND_CHANNELS.
SafeWestEnd_Pressed()
void com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Pressed (MouseEvent event) package
Definition at line 803 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerSupervisorActions.style.
SafeWestEnd_Released()
void com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Released (MouseEvent event) package
Definition at line 809 of file ControllerSupervisorActions.java.
References com.gluonapplication.ControllerSupervisorActions.style.
Member Data Documentation
style
String com.gluonapplication.ControllerSupervisorActions.style = "" package
Definition at line 115 of file ControllerSupervisorActions.java.
Referenced by com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Pressed(), com.gluonapplication.ControllerSupervisorActions.EmergencyCB_Released(), com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Pressed(), com.gluonapplication.ControllerSupervisorActions.EmergencyNE_Released(), com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Pressed(), com.gluonapplication.ControllerSupervisorActions.EmergencyWE_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_2_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankNE_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_2_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankNI_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_2_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankWE_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_2_Released(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Pressed(), com.gluonapplication.ControllerSupervisorActions.LN2TankWI_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingBS_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingDET_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingIB_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingMC_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNE_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingNI_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingPR_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingSR_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWE_Released(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Pressed(), com.gluonapplication.ControllerSupervisorActions.PrimaryPumpingWI_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingBS_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingDET_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingIB_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingNI_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingPR_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingSR_Released(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Pressed(), com.gluonapplication.ControllerSupervisorActions.RemotePumpingWI_Released(), com.gluonapplication.ControllerSupervisorActions.SafeCentral_Pressed(), com.gluonapplication.ControllerSupervisorActions.SafeCentral_Released(), com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Pressed(), com.gluonapplication.ControllerSupervisorActions.SafeNorthArm_Released(), com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Pressed(), com.gluonapplication.ControllerSupervisorActions.SafeNorthEnd_Released(), com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Pressed(), com.gluonapplication.ControllerSupervisorActions.SafeWestArm_Released(), com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Pressed(), and com.gluonapplication.ControllerSupervisorActions.SafeWestEnd_Released().
The documentation for this class was generated from the following file:
ControllerSupervisorActions.java