VACUUM Supervisor: com.gluonapplication.ControllerLink Class Reference
com.gluonapplication.ControllerLink Class Reference
Package Functions
void SpeedP21_Clicked (MouseEvent event)
void SpeedP21_Pressed (MouseEvent event)
void SpeedP21_Released (MouseEvent event)
void G21_Clicked (MouseEvent event)
void G21_Pressed (MouseEvent event)
void G21_Released (MouseEvent event)
void G22_Clicked (MouseEvent event)
void G22_Pressed (MouseEvent event)
void G22_Released (MouseEvent event)
void P21_Clicked (MouseEvent event)
void P21_Pressed (MouseEvent event)
void P21_Released (MouseEvent event)
void P22_Clicked (MouseEvent event)
void P22_Pressed (MouseEvent event)
void P22_Released (MouseEvent event)
void PressureG21_Clicked (MouseEvent event)
void PressureG21_Pressed (MouseEvent event)
void PressureG21_Released (MouseEvent event)
void PressureG22_Clicked (MouseEvent event)
void PressureG22_Pressed (MouseEvent event)
void PressureG22_Released (MouseEvent event)
void Ge4_Clicked (MouseEvent event)
void Ge4_Pressed (MouseEvent event)
void Ge4_Released (MouseEvent event)
void V21_Clicked (MouseEvent event)
void V21_Pressed (MouseEvent event)
void V21_Released (MouseEvent event)
void V22_Clicked (MouseEvent event)
void V22_Pressed (MouseEvent event)
void V22_Released (MouseEvent event)
void V23_Clicked (MouseEvent event)
void V23_Pressed (MouseEvent event)
void V23_Released (MouseEvent event)
void RemotePumping_Clicked (MouseEvent event)
void RemotePumping_Pressed (MouseEvent event)
void RemotePumping_Released (MouseEvent event)
void CreateAndShowRGALayer (String name)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowValveLayer (String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 13 of file ControllerLink.java.
Member Function Documentation
CreateAndShowRGALayer()
void com.gluonapplication.ControllerLink.CreateAndShowRGALayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 279 of file ControllerLink.java.
References com.gluonapplication.ViewData.name.
Referenced by com.gluonapplication.ControllerLink.Ge4_Clicked().
G21_Clicked()
void com.gluonapplication.ControllerLink.G21_Clicked (MouseEvent event) package
Definition at line 94 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G21_Pressed()
void com.gluonapplication.ControllerLink.G21_Pressed (MouseEvent event) package
Definition at line 99 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
G21_Released()
void com.gluonapplication.ControllerLink.G21_Released (MouseEvent event) package
Definition at line 105 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
G22_Clicked()
void com.gluonapplication.ControllerLink.G22_Clicked (MouseEvent event) package
Definition at line 110 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowGaugeLayer().
G22_Pressed()
void com.gluonapplication.ControllerLink.G22_Pressed (MouseEvent event) package
Definition at line 115 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
G22_Released()
void com.gluonapplication.ControllerLink.G22_Released (MouseEvent event) package
Definition at line 121 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
Ge4_Clicked()
void com.gluonapplication.ControllerLink.Ge4_Clicked (MouseEvent event) package
Definition at line 191 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.CreateAndShowRGALayer().
Ge4_Pressed()
void com.gluonapplication.ControllerLink.Ge4_Pressed (MouseEvent event) package
Definition at line 196 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
Ge4_Released()
void com.gluonapplication.ControllerLink.Ge4_Released (MouseEvent event) package
Definition at line 202 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
P21_Clicked()
void com.gluonapplication.ControllerLink.P21_Clicked (MouseEvent event) package
Definition at line 126 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowTurboLayer().
P21_Pressed()
void com.gluonapplication.ControllerLink.P21_Pressed (MouseEvent event) package
Definition at line 131 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
P21_Released()
void com.gluonapplication.ControllerLink.P21_Released (MouseEvent event) package
Definition at line 137 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
P22_Clicked()
void com.gluonapplication.ControllerLink.P22_Clicked (MouseEvent event) package
Definition at line 142 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowDryLayer().
P22_Pressed()
void com.gluonapplication.ControllerLink.P22_Pressed (MouseEvent event) package
Definition at line 147 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
P22_Released()
void com.gluonapplication.ControllerLink.P22_Released (MouseEvent event) package
Definition at line 153 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
PressureG21_Clicked()
void com.gluonapplication.ControllerLink.PressureG21_Clicked (MouseEvent event) package
Definition at line 159 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG21_Pressed()
void com.gluonapplication.ControllerLink.PressureG21_Pressed (MouseEvent event) package
Definition at line 164 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
PressureG21_Released()
void com.gluonapplication.ControllerLink.PressureG21_Released (MouseEvent event) package
Definition at line 170 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
PressureG22_Clicked()
void com.gluonapplication.ControllerLink.PressureG22_Clicked (MouseEvent event) package
Definition at line 175 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
PressureG22_Pressed()
void com.gluonapplication.ControllerLink.PressureG22_Pressed (MouseEvent event) package
Definition at line 180 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
PressureG22_Released()
void com.gluonapplication.ControllerLink.PressureG22_Released (MouseEvent event) package
Definition at line 186 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
RemotePumping_Clicked()
void com.gluonapplication.ControllerLink.RemotePumping_Clicked (MouseEvent event) package
Definition at line 255 of file ControllerLink.java.
References com.gluonapplication.Main.remotePumps.
RemotePumping_Pressed()
void com.gluonapplication.ControllerLink.RemotePumping_Pressed (MouseEvent event) package
Definition at line 269 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
RemotePumping_Released()
void com.gluonapplication.ControllerLink.RemotePumping_Released (MouseEvent event) package
Definition at line 275 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
SpeedP21_Clicked()
void com.gluonapplication.ControllerLink.SpeedP21_Clicked (MouseEvent event) package
Definition at line 78 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowPlotLayer().
SpeedP21_Pressed()
void com.gluonapplication.ControllerLink.SpeedP21_Pressed (MouseEvent event) package
Definition at line 83 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
SpeedP21_Released()
void com.gluonapplication.ControllerLink.SpeedP21_Released (MouseEvent event) package
Definition at line 89 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
V21_Clicked()
void com.gluonapplication.ControllerLink.V21_Clicked (MouseEvent event) package
Definition at line 207 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V21_Pressed()
void com.gluonapplication.ControllerLink.V21_Pressed (MouseEvent event) package
Definition at line 212 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
V21_Released()
void com.gluonapplication.ControllerLink.V21_Released (MouseEvent event) package
Definition at line 218 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
V22_Clicked()
void com.gluonapplication.ControllerLink.V22_Clicked (MouseEvent event) package
Definition at line 223 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V22_Pressed()
void com.gluonapplication.ControllerLink.V22_Pressed (MouseEvent event) package
Definition at line 228 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
V22_Released()
void com.gluonapplication.ControllerLink.V22_Released (MouseEvent event) package
Definition at line 234 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
V23_Clicked()
void com.gluonapplication.ControllerLink.V23_Clicked (MouseEvent event) package
Definition at line 239 of file ControllerLink.java.
References com.gluonapplication.ControlLayer.CreateAndShowValveLayer().
V23_Pressed()
void com.gluonapplication.ControllerLink.V23_Pressed (MouseEvent event) package
Definition at line 244 of file ControllerLink.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerLink.style.
V23_Released()
void com.gluonapplication.ControllerLink.V23_Released (MouseEvent event) package
Definition at line 250 of file ControllerLink.java.
References com.gluonapplication.ControllerLink.style.
Member Data Documentation
style
String com.gluonapplication.ControllerLink.style = "" package
Definition at line 75 of file ControllerLink.java.
Referenced by com.gluonapplication.ControllerLink.G21_Pressed(), com.gluonapplication.ControllerLink.G21_Released(), com.gluonapplication.ControllerLink.G22_Pressed(), com.gluonapplication.ControllerLink.G22_Released(), com.gluonapplication.ControllerLink.Ge4_Pressed(), com.gluonapplication.ControllerLink.Ge4_Released(), com.gluonapplication.ControllerLink.P21_Pressed(), com.gluonapplication.ControllerLink.P21_Released(), com.gluonapplication.ControllerLink.P22_Pressed(), com.gluonapplication.ControllerLink.P22_Released(), com.gluonapplication.ControllerLink.PressureG21_Pressed(), com.gluonapplication.ControllerLink.PressureG21_Released(), com.gluonapplication.ControllerLink.PressureG22_Pressed(), com.gluonapplication.ControllerLink.PressureG22_Released(), com.gluonapplication.ControllerLink.RemotePumping_Pressed(), com.gluonapplication.ControllerLink.RemotePumping_Released(), com.gluonapplication.ControllerLink.SpeedP21_Pressed(), com.gluonapplication.ControllerLink.SpeedP21_Released(), com.gluonapplication.ControllerLink.V21_Pressed(), com.gluonapplication.ControllerLink.V21_Released(), com.gluonapplication.ControllerLink.V22_Pressed(), com.gluonapplication.ControllerLink.V22_Released(), com.gluonapplication.ControllerLink.V23_Pressed(), and com.gluonapplication.ControllerLink.V23_Released().
The documentation for this class was generated from the following file:
ControllerLink.java