VACUUM Supervisor: com.gluonapplication.ControllerTubeW Class Reference
com.gluonapplication.ControllerTubeW Class Reference
Package Functions
void CB_Clicked (MouseEvent event)
void CB_Pressed (MouseEvent event)
void CB_Released (MouseEvent event)
void WE_Clicked (MouseEvent event)
void WE_Pressed (MouseEvent event)
void WE_Released (MouseEvent event)
void Station1200W_Clicked (MouseEvent event)
void Station1200W_Pressed (MouseEvent event)
void Station1200W_Released (MouseEvent event)
void Station2400W_Clicked (MouseEvent event)
void Station2400W_Pressed (MouseEvent event)
void Station2400W_Released (MouseEvent event)
void Station1800W_Clicked (MouseEvent event)
void Station1800W_Pressed (MouseEvent event)
void Station1800W_Released (MouseEvent event)
void Station3000W_Clicked (MouseEvent event)
void Station3000W_Pressed (MouseEvent event)
void Station3000W_Released (MouseEvent event)
void Station300W_Clicked (MouseEvent event)
void Station300W_Pressed (MouseEvent event)
void Station300W_Released (MouseEvent event)
void Station600W_Clicked (MouseEvent event)
void Station600W_Pressed (MouseEvent event)
void Station600W_Released (MouseEvent event)
void V1200W_Clicked (MouseEvent event)
void V1200W_Pressed (MouseEvent event)
void V1200W_Released (MouseEvent event)
void V1800W_Clicked (MouseEvent event)
void V1800W_Pressed (MouseEvent event)
void V1800W_Released (MouseEvent event)
void V2400W_Clicked (MouseEvent event)
void V2400W_Pressed (MouseEvent event)
void V2400W_Released (MouseEvent event)
void V3000W_Clicked (MouseEvent event)
void V3000W_Pressed (MouseEvent event)
void V3000W_Released (MouseEvent event)
void V300W_Clicked (MouseEvent event)
void V300W_Pressed (MouseEvent event)
void V300W_Released (MouseEvent event)
void V600W_Clicked (MouseEvent event)
void V600W_Pressed (MouseEvent event)
void V600W_Released (MouseEvent event)
void V1200W1_Clicked (MouseEvent event)
void V1200W1_Pressed (MouseEvent event)
void V1200W1_Released (MouseEvent event)
void V1800W1_Clicked (MouseEvent event)
void V1800W1_Pressed (MouseEvent event)
void V1800W1_Released (MouseEvent event)
void V2400W1_Clicked (MouseEvent event)
void V2400W1_Pressed (MouseEvent event)
void V2400W1_Released (MouseEvent event)
void V3000W1_Clicked (MouseEvent event)
void V3000W1_Pressed (MouseEvent event)
void V3000W1_Released (MouseEvent event)
void V300W1_Clicked (MouseEvent event)
void V300W1_Pressed (MouseEvent event)
void V300W1_Released (MouseEvent event)
void V600W1_Clicked (MouseEvent event)
void V600W1_Pressed (MouseEvent event)
void V600W1_Released (MouseEvent event)
void VWE_Clicked (MouseEvent event)
void VWE_Pressed (MouseEvent event)
void VWE_Released (MouseEvent event)
void VWI_Clicked (MouseEvent event)
void VWI_Pressed (MouseEvent event)
void VWI_Released (MouseEvent event)
void Ge4_1500W_Clicked (MouseEvent event)
void Ge4_1500W_Pressed (MouseEvent event)
void Ge4_1500W_Released (MouseEvent event)
void CreateAndShowValveLayer (String name)
void CreateAndShowRGALayer (String name)
Package Functions inherited from com.gluonapplication.ControlLayer
void CreateAndShowGaugeLayer (String fxml, String name)
void CreateAndShowDryLayer (String name)
void CreateAndShowTurboLayer (String fxml, String name)
void CreateAndShowIonicLayer (String fxml, String name)
void CreateAndShowTitaneLayer (String fxml, String name)
void CreateAndShowPlotLayer (String name)
Package Attributes
String style = ""
Additional Inherited Members
Public Attributes inherited from com.gluonapplication.ControlTypes
String DECORATION_STYLE_PUSHED = " -fx-border-color: #cfcfcf; -fx-border-width: 1; -fx-border-radius: 5; -fx-text-fill: black; -fx-background-radius: 5; -fx-background-color: #cfcfcf; -fx-opacity: 0.5"
Hashtable< String, String > VALVE_COMMAND_CHANNELS
Hashtable< String, String > VALVE_CRYOLINK_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LAL_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_SQZ_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKPR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_LINKSR_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKDET_COMMAND_CHANNELS
Hashtable< String, String > GAUGE_CRYOLINKIB_COMMAND_CHANNELS
Hashtable< String, String > SUPERVISORACTIONS_COMMAND_CHANNELS
Hashtable< String, String > CRYOACTIONS_COMMAND_CHANNELS
Hashtable< String, String > DRY_COMMAND_CHANNELS
Hashtable< String, String > TURBO_COMMAND_CHANNELS
Hashtable< String, String > TITANE_COMMAND_CHANNELS
Hashtable< String, String > IONIC_COMMAND_CHANNELS
Hashtable< String, String > CRYOLINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MINITOWERSQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > LINKACTIONS_COMMAND_CHANNELS
Hashtable< String, String > TUBESQZACTIONS_COMMAND_CHANNELS
Hashtable< String, String > MOBILEVENTINGACTIONS_COMMAND_CHANNELS
Detailed Description
Definition at line 13 of file ControllerTubeW.java.
Member Function Documentation
CB_Clicked()
void com.gluonapplication.ControllerTubeW.CB_Clicked (MouseEvent event) package
Definition at line 151 of file ControllerTubeW.java.
References com.gluonapplication.Main.cb.
CB_Pressed()
void com.gluonapplication.ControllerTubeW.CB_Pressed (MouseEvent event) package
Definition at line 165 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
CB_Released()
void com.gluonapplication.ControllerTubeW.CB_Released (MouseEvent event) package
Definition at line 171 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
CreateAndShowRGALayer()
void com.gluonapplication.ControllerTubeW.CreateAndShowRGALayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 608 of file ControllerTubeW.java.
Referenced by com.gluonapplication.ControllerTubeW.Ge4_1500W_Clicked().
CreateAndShowValveLayer()
void com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer (String name) package
Reimplemented from com.gluonapplication.ControlLayer.
Definition at line 591 of file ControllerTubeW.java.
Referenced by com.gluonapplication.ControllerTubeW.V1200W1_Clicked(), com.gluonapplication.ControllerTubeW.V1200W_Clicked(), com.gluonapplication.ControllerTubeW.V1800W1_Clicked(), com.gluonapplication.ControllerTubeW.V1800W_Clicked(), com.gluonapplication.ControllerTubeW.V2400W1_Clicked(), com.gluonapplication.ControllerTubeW.V2400W_Clicked(), com.gluonapplication.ControllerTubeW.V3000W1_Clicked(), com.gluonapplication.ControllerTubeW.V3000W_Clicked(), com.gluonapplication.ControllerTubeW.V300W1_Clicked(), com.gluonapplication.ControllerTubeW.V300W_Clicked(), com.gluonapplication.ControllerTubeW.V600W1_Clicked(), com.gluonapplication.ControllerTubeW.V600W_Clicked(), com.gluonapplication.ControllerTubeW.VWE_Clicked(), and com.gluonapplication.ControllerTubeW.VWI_Clicked().
Ge4_1500W_Clicked()
void com.gluonapplication.ControllerTubeW.Ge4_1500W_Clicked (MouseEvent event) package
Definition at line 575 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowRGALayer().
Ge4_1500W_Pressed()
void com.gluonapplication.ControllerTubeW.Ge4_1500W_Pressed (MouseEvent event) package
Definition at line 580 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Ge4_1500W_Released()
void com.gluonapplication.ControllerTubeW.Ge4_1500W_Released (MouseEvent event) package
Definition at line 586 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station1200W_Clicked()
void com.gluonapplication.ControllerTubeW.Station1200W_Clicked (MouseEvent event) package
Definition at line 201 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube1200W.
Station1200W_Pressed()
void com.gluonapplication.ControllerTubeW.Station1200W_Pressed (MouseEvent event) package
Definition at line 215 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station1200W_Released()
void com.gluonapplication.ControllerTubeW.Station1200W_Released (MouseEvent event) package
Definition at line 221 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station1800W_Clicked()
void com.gluonapplication.ControllerTubeW.Station1800W_Clicked (MouseEvent event) package
Definition at line 251 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube1800W.
Station1800W_Pressed()
void com.gluonapplication.ControllerTubeW.Station1800W_Pressed (MouseEvent event) package
Definition at line 265 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station1800W_Released()
void com.gluonapplication.ControllerTubeW.Station1800W_Released (MouseEvent event) package
Definition at line 271 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station2400W_Clicked()
void com.gluonapplication.ControllerTubeW.Station2400W_Clicked (MouseEvent event) package
Definition at line 226 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube2400W.
Station2400W_Pressed()
void com.gluonapplication.ControllerTubeW.Station2400W_Pressed (MouseEvent event) package
Definition at line 240 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station2400W_Released()
void com.gluonapplication.ControllerTubeW.Station2400W_Released (MouseEvent event) package
Definition at line 246 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station3000W_Clicked()
void com.gluonapplication.ControllerTubeW.Station3000W_Clicked (MouseEvent event) package
Definition at line 276 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube3000W.
Station3000W_Pressed()
void com.gluonapplication.ControllerTubeW.Station3000W_Pressed (MouseEvent event) package
Definition at line 290 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station3000W_Released()
void com.gluonapplication.ControllerTubeW.Station3000W_Released (MouseEvent event) package
Definition at line 296 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station300W_Clicked()
void com.gluonapplication.ControllerTubeW.Station300W_Clicked (MouseEvent event) package
Definition at line 301 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube300W.
Station300W_Pressed()
void com.gluonapplication.ControllerTubeW.Station300W_Pressed (MouseEvent event) package
Definition at line 315 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station300W_Released()
void com.gluonapplication.ControllerTubeW.Station300W_Released (MouseEvent event) package
Definition at line 321 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Station600W_Clicked()
void com.gluonapplication.ControllerTubeW.Station600W_Clicked (MouseEvent event) package
Definition at line 326 of file ControllerTubeW.java.
References com.gluonapplication.Main.tube600W.
Station600W_Pressed()
void com.gluonapplication.ControllerTubeW.Station600W_Pressed (MouseEvent event) package
Definition at line 340 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
Station600W_Released()
void com.gluonapplication.ControllerTubeW.Station600W_Released (MouseEvent event) package
Definition at line 346 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V1200W1_Clicked()
void com.gluonapplication.ControllerTubeW.V1200W1_Clicked (MouseEvent event) package
Definition at line 447 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V1200W1_Pressed()
void com.gluonapplication.ControllerTubeW.V1200W1_Pressed (MouseEvent event) package
Definition at line 452 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V1200W1_Released()
void com.gluonapplication.ControllerTubeW.V1200W1_Released (MouseEvent event) package
Definition at line 458 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V1200W_Clicked()
void com.gluonapplication.ControllerTubeW.V1200W_Clicked (MouseEvent event) package
Definition at line 351 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V1200W_Pressed()
void com.gluonapplication.ControllerTubeW.V1200W_Pressed (MouseEvent event) package
Definition at line 356 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V1200W_Released()
void com.gluonapplication.ControllerTubeW.V1200W_Released (MouseEvent event) package
Definition at line 362 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V1800W1_Clicked()
void com.gluonapplication.ControllerTubeW.V1800W1_Clicked (MouseEvent event) package
Definition at line 463 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V1800W1_Pressed()
void com.gluonapplication.ControllerTubeW.V1800W1_Pressed (MouseEvent event) package
Definition at line 468 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V1800W1_Released()
void com.gluonapplication.ControllerTubeW.V1800W1_Released (MouseEvent event) package
Definition at line 474 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V1800W_Clicked()
void com.gluonapplication.ControllerTubeW.V1800W_Clicked (MouseEvent event) package
Definition at line 367 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V1800W_Pressed()
void com.gluonapplication.ControllerTubeW.V1800W_Pressed (MouseEvent event) package
Definition at line 372 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V1800W_Released()
void com.gluonapplication.ControllerTubeW.V1800W_Released (MouseEvent event) package
Definition at line 378 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V2400W1_Clicked()
void com.gluonapplication.ControllerTubeW.V2400W1_Clicked (MouseEvent event) package
Definition at line 479 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V2400W1_Pressed()
void com.gluonapplication.ControllerTubeW.V2400W1_Pressed (MouseEvent event) package
Definition at line 484 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V2400W1_Released()
void com.gluonapplication.ControllerTubeW.V2400W1_Released (MouseEvent event) package
Definition at line 490 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V2400W_Clicked()
void com.gluonapplication.ControllerTubeW.V2400W_Clicked (MouseEvent event) package
Definition at line 383 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V2400W_Pressed()
void com.gluonapplication.ControllerTubeW.V2400W_Pressed (MouseEvent event) package
Definition at line 388 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V2400W_Released()
void com.gluonapplication.ControllerTubeW.V2400W_Released (MouseEvent event) package
Definition at line 394 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V3000W1_Clicked()
void com.gluonapplication.ControllerTubeW.V3000W1_Clicked (MouseEvent event) package
Definition at line 495 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V3000W1_Pressed()
void com.gluonapplication.ControllerTubeW.V3000W1_Pressed (MouseEvent event) package
Definition at line 500 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V3000W1_Released()
void com.gluonapplication.ControllerTubeW.V3000W1_Released (MouseEvent event) package
Definition at line 506 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V3000W_Clicked()
void com.gluonapplication.ControllerTubeW.V3000W_Clicked (MouseEvent event) package
Definition at line 399 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V3000W_Pressed()
void com.gluonapplication.ControllerTubeW.V3000W_Pressed (MouseEvent event) package
Definition at line 404 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V3000W_Released()
void com.gluonapplication.ControllerTubeW.V3000W_Released (MouseEvent event) package
Definition at line 410 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V300W1_Clicked()
void com.gluonapplication.ControllerTubeW.V300W1_Clicked (MouseEvent event) package
Definition at line 511 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V300W1_Pressed()
void com.gluonapplication.ControllerTubeW.V300W1_Pressed (MouseEvent event) package
Definition at line 516 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V300W1_Released()
void com.gluonapplication.ControllerTubeW.V300W1_Released (MouseEvent event) package
Definition at line 522 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V300W_Clicked()
void com.gluonapplication.ControllerTubeW.V300W_Clicked (MouseEvent event) package
Definition at line 415 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V300W_Pressed()
void com.gluonapplication.ControllerTubeW.V300W_Pressed (MouseEvent event) package
Definition at line 420 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V300W_Released()
void com.gluonapplication.ControllerTubeW.V300W_Released (MouseEvent event) package
Definition at line 426 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V600W1_Clicked()
void com.gluonapplication.ControllerTubeW.V600W1_Clicked (MouseEvent event) package
Definition at line 527 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V600W1_Pressed()
void com.gluonapplication.ControllerTubeW.V600W1_Pressed (MouseEvent event) package
Definition at line 532 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V600W1_Released()
void com.gluonapplication.ControllerTubeW.V600W1_Released (MouseEvent event) package
Definition at line 538 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
V600W_Clicked()
void com.gluonapplication.ControllerTubeW.V600W_Clicked (MouseEvent event) package
Definition at line 431 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
V600W_Pressed()
void com.gluonapplication.ControllerTubeW.V600W_Pressed (MouseEvent event) package
Definition at line 436 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
V600W_Released()
void com.gluonapplication.ControllerTubeW.V600W_Released (MouseEvent event) package
Definition at line 442 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
VWE_Clicked()
void com.gluonapplication.ControllerTubeW.VWE_Clicked (MouseEvent event) package
Definition at line 543 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
VWE_Pressed()
void com.gluonapplication.ControllerTubeW.VWE_Pressed (MouseEvent event) package
Definition at line 548 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
VWE_Released()
void com.gluonapplication.ControllerTubeW.VWE_Released (MouseEvent event) package
Definition at line 554 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
VWI_Clicked()
void com.gluonapplication.ControllerTubeW.VWI_Clicked (MouseEvent event) package
Definition at line 559 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.CreateAndShowValveLayer().
VWI_Pressed()
void com.gluonapplication.ControllerTubeW.VWI_Pressed (MouseEvent event) package
Definition at line 564 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
VWI_Released()
void com.gluonapplication.ControllerTubeW.VWI_Released (MouseEvent event) package
Definition at line 570 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
WE_Clicked()
void com.gluonapplication.ControllerTubeW.WE_Clicked (MouseEvent event) package
Definition at line 176 of file ControllerTubeW.java.
References com.gluonapplication.Main.we.
WE_Pressed()
void com.gluonapplication.ControllerTubeW.WE_Pressed (MouseEvent event) package
Definition at line 190 of file ControllerTubeW.java.
References com.gluonapplication.ControlTypes.DECORATION_STYLE_PUSHED, and com.gluonapplication.ControllerTubeW.style.
WE_Released()
void com.gluonapplication.ControllerTubeW.WE_Released (MouseEvent event) package
Definition at line 196 of file ControllerTubeW.java.
References com.gluonapplication.ControllerTubeW.style.
Member Data Documentation
style
String com.gluonapplication.ControllerTubeW.style = "" package
Definition at line 147 of file ControllerTubeW.java.
Referenced by com.gluonapplication.ControllerTubeW.CB_Pressed(), com.gluonapplication.ControllerTubeW.CB_Released(), com.gluonapplication.ControllerTubeW.Ge4_1500W_Pressed(), com.gluonapplication.ControllerTubeW.Ge4_1500W_Released(), com.gluonapplication.ControllerTubeW.Station1200W_Pressed(), com.gluonapplication.ControllerTubeW.Station1200W_Released(), com.gluonapplication.ControllerTubeW.Station1800W_Pressed(), com.gluonapplication.ControllerTubeW.Station1800W_Released(), com.gluonapplication.ControllerTubeW.Station2400W_Pressed(), com.gluonapplication.ControllerTubeW.Station2400W_Released(), com.gluonapplication.ControllerTubeW.Station3000W_Pressed(), com.gluonapplication.ControllerTubeW.Station3000W_Released(), com.gluonapplication.ControllerTubeW.Station300W_Pressed(), com.gluonapplication.ControllerTubeW.Station300W_Released(), com.gluonapplication.ControllerTubeW.Station600W_Pressed(), com.gluonapplication.ControllerTubeW.Station600W_Released(), com.gluonapplication.ControllerTubeW.V1200W1_Pressed(), com.gluonapplication.ControllerTubeW.V1200W1_Released(), com.gluonapplication.ControllerTubeW.V1200W_Pressed(), com.gluonapplication.ControllerTubeW.V1200W_Released(), com.gluonapplication.ControllerTubeW.V1800W1_Pressed(), com.gluonapplication.ControllerTubeW.V1800W1_Released(), com.gluonapplication.ControllerTubeW.V1800W_Pressed(), com.gluonapplication.ControllerTubeW.V1800W_Released(), com.gluonapplication.ControllerTubeW.V2400W1_Pressed(), com.gluonapplication.ControllerTubeW.V2400W1_Released(), com.gluonapplication.ControllerTubeW.V2400W_Pressed(), com.gluonapplication.ControllerTubeW.V2400W_Released(), com.gluonapplication.ControllerTubeW.V3000W1_Pressed(), com.gluonapplication.ControllerTubeW.V3000W1_Released(), com.gluonapplication.ControllerTubeW.V3000W_Pressed(), com.gluonapplication.ControllerTubeW.V3000W_Released(), com.gluonapplication.ControllerTubeW.V300W1_Pressed(), com.gluonapplication.ControllerTubeW.V300W1_Released(), com.gluonapplication.ControllerTubeW.V300W_Pressed(), com.gluonapplication.ControllerTubeW.V300W_Released(), com.gluonapplication.ControllerTubeW.V600W1_Pressed(), com.gluonapplication.ControllerTubeW.V600W1_Released(), com.gluonapplication.ControllerTubeW.V600W_Pressed(), com.gluonapplication.ControllerTubeW.V600W_Released(), com.gluonapplication.ControllerTubeW.VWE_Pressed(), com.gluonapplication.ControllerTubeW.VWE_Released(), com.gluonapplication.ControllerTubeW.VWI_Pressed(), com.gluonapplication.ControllerTubeW.VWI_Released(), com.gluonapplication.ControllerTubeW.WE_Pressed(), and com.gluonapplication.ControllerTubeW.WE_Released().
The documentation for this class was generated from the following file:
ControllerTubeW.java